### ISSUE TITLE
Logout fails due to ignored Cache-Control

### ISSUE THREAD

**Issue by ner00** [prasathmani/tinyfilemanager#1003]
Apparently the user can become unable to logout due to browser cache completely ignoring the logout function by serving a cached page instead of sending the `$_GET['logout']` parameter to the server. When I was testing this in a localhost environment it wasn't happening, but after uploading this externally and testing it became apparent that it didn't work properly.

I can see that the both `fm_show_header_login()` and `fm_show_header()` have:
```php
header("Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0");
header("Pragma: no-cache");
```

And in theory this should work fine given its initialization in:
```php
// --- TINYFILEMANAGER MAIN ---
fm_show_header(); // HEADER
```

Unfortunately I still get the same issue after 1st or 2nd consecutive login/logout attempt where it just refreshes the page and the request for `?logout=1` is completely ignored and instead it pulls the cached version. I can clearly see this is the issue in both Firefox and Chrome:

![firefox_F1yQ3ST38a](https://user-images.githubusercontent.com/2269603/228951336-8370afea-7ed5-41e3-8d75-f0102bba5ab3.png)

![chrome_7x9F2zbyf7](https://user-images.githubusercontent.com/2269603/228951374-5379d1ca-e5be-44b4-bb33-8cc6f23fce2e.png)

The few tests I have made would work only **if** `Cache-Control` is declared above the logout condition, for example:
```php
header("Content-Type: text/html; charset=utf-8");
header("Expires: Sat, 26 Jul 1997 05:00:00 GMT");
header("Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0");
header("Pragma: no-cache");

// logout
if (isset($_GET['logout'])) {
    unset($_SESSION[FM_SESSION_ID]['logged']);
    unset( $_SESSION['token']); 
    fm_redirect(FM_SELF_URL);
}
```

**Comment by ner00** [comment]
Disable page caching by changing existing function call: https://github.com/prasathmani/tinyfilemanager/blob/bf024c7c841be7600e41cf8e0564786ffad1d7a3/tinyfilemanager.php#L225
should be:
```php
    session_cache_limiter('nocache');
```

**Comment by prasathmani** [comment]
@ner00 , Thanks for the detailed information, if possible please create a PR.

**Comment by ner00** [comment]
@prasathmani https://github.com/prasathmani/tinyfilemanager/pull/1004
