### ISSUE TITLE
Navigating to wrong page after login

### ISSUE THREAD

**Issue by tonycstech** [prasathmani/tinyfilemanager#1008]
Here are my settings
```
// Root path for file manager
// use absolute path of directory i.e: '/var/www/folder' or $_SERVER['DOCUMENT_ROOT'].'/folder'
$root_path = $_SERVER['DOCUMENT_ROOT'].'/img';

// Root url for links in file manager.Relative to $http_host. Variants: '', 'path/to/subfolder'
// Will not working if $root_path will be outside of server document root
$root_url = '/img';

// Server hostname. Can set manually if wrong
// $_SERVER['HTTP_HOST'].'/folder'
$http_host = $_SERVER['HTTP_HOST'];
```
Once logged in, page "www.mywebsite.com/img" opens and error 403

php file is in the website root.
all files are inside img folder so i need to be able to use this browser to browse img folder.

**Comment by tonycstech** [comment]
To solve this issue, i had to make the following change:
fm_redirect('browser_new.php?p=');
otherwise after login, it opens www.mywebsite.com/img instead of opening file browser after successful login.

**Comment by ner00** [comment]
Change this line
https://github.com/prasathmani/tinyfilemanager/blob/6a6eb8abecef523aafda0e9aa71f94f231128222/tinyfilemanager.php#L325
to:
```php
fm_redirect(FM_SELF_URL);
```
