### ISSUE TITLE
Chinese version! and some bug.

### ISSUE THREAD

**Issue by haer0248** [prasathmani/tinyfilemanager#101]
https://github.com/haer0248/tinyfilemanager

BUG:

**CAN'T** change language
**CAN'T** change error reporting and hidden file.
can you fix it? 
I love it!

Notice: Windows and Linux same.

**Comment by prasathmani** [comment]
@haer0248 try this demo code - https://codeshare.io/2KnMMK

**Comment by haer0248** [comment]
@prasathmani 
Language - OK
Setting - Failed

**Comment by haer0248** [comment]
When I edit the file containing the website code, I will see the XSS cross-site attack screen (Chrome).

**Comment by prasathmani** [comment]
Demo code will work for languages only other settings not supported. For XSS, I need to check, https://stackoverflow.com/a/43288333

**Comment by haer0248** [comment]
Okay, waiting for your answer! Thanks :)

**Comment by haer0248** [comment]
@prasathmani 
new bug (?)
I can't upload or create **Chinese** document name.

**Comment by prasathmani** [comment]
I've tried to create new file/folder/upload with Chinese names, it's working. Feel free to reopen if your issue is not solved
