### ISSUE TITLE
Add date prefix to uploaded files

### ISSUE THREAD

**Issue by dotcomUNDERGROUND** [prasathmani/tinyfilemanager#1012]
I wish to auto add a date prefix to uploaded file names.

Like "DSC_1234.jpg" becomes "2023-04-08 DSC_1234.jpg"

How can I modify the code to achieve this?

**Comment by prasathmani** [comment]
https://github.com/prasathmani/tinyfilemanager/blob/6a6eb8abecef523aafda0e9aa71f94f231128222/tinyfilemanager.php#L938

```php
// format the date as required
$tmp_name = new DateTime().$f['file']['tmp_name'];

**Comment by dotcomUNDERGROUND** [comment]
Thanks!

I tried this:
```
$tmp_name = $f['file']['tmp_name'];
$date = date("Y-m-d H.i.s");
$tmp_name = "{$date} {$tmp_name}";
```
But it's not working

**Comment by ner00** [comment]
Apparently it doesn't work because it uses `$fullPath` instead to rename the temporary filename, change this:

https://github.com/prasathmani/tinyfilemanager/blob/6a6eb8abecef523aafda0e9aa71f94f231128222/tinyfilemanager.php#L1000
to:
```php
rename("{$fullPath}.part", dirname($fullPath).$ds.date("Y-m-d H.i.s")." $filename");
```

**Comment by dotcomUNDERGROUND** [comment]
Worked! 

Thank you!
