### ISSUE TITLE
Incorrect file url for specified $directories_users array

### ISSUE THREAD

**Issue by tonycstech** [prasathmani/tinyfilemanager#1013]
`$directories_users = array(
    'sah' => 'img/SAH',
    'sjmc' => 'img/SJMC'
);`
When user is logged in, user is taken to specified directory as expected.
All files are listed as expected.
File location is showing correct but the URL to file is wrong.
its double adding parts of the path.

Other changes made to the script are:
$root_path = $_SERVER['DOCUMENT_ROOT'].'/img';
$root_url = '/img';

![0](https://user-images.githubusercontent.com/61446662/230695659-9e614e6f-1a7d-4ab2-87f1-91b29469f997.jpg)

.This issue does not effect admin account, only array users.

**Comment by tonycstech** [comment]
File location:
P:/WWW/img/SAH/ENT/Dr. Pai Thyroid Extras.JPG
URL
http://localhost/SAH/ENT/Dr.%20Pai%20Thyroid%20Extras.JPG
Missing "img"

that is why i added 
$root_url = '/img';
to fix that. But if i do, array users start to encounter double "img" in the file URL while admin does not.

**Comment by prasathmani** [comment]
#724,

**Comment by tonycstech** [comment]
The cause for my problem was:
I had admin defined in the 
$auth_users = array(
but i gave no directory for admin below
$directories_users = array(

That made the URL's weird depending on what user is logged in and adding parts of missing URL to $root_url = '/img'; was causing the issue.
With $root_url = ''; being blank and admin properly given a directory, it worked.
