### ISSUE TITLE
highlight.js problem on my website

### ISSUE THREAD

**Issue by xololunatic** [prasathmani/tinyfilemanager#1019]
Hi! I am New to this. But I love it, currently, I am having a problem with highlight.js. I don't know why when I Use tfm on my local environment it shows correctly and all codes are shown using highlight.js but when I upload the tfm on my website the highlight.js does not work. I don't know if I have to do something or if there is any requirement for this or maybe it's my hosting problem. But I would love to get help on this. Plz, tell me what do you think is the problem.

**Comment by prasathmani** [comment]
@xololunatic , did you get any console error.

**Comment by xololunatic** [comment]
> @xololunatic , did you get any console error.

at first I was on localhost so I didn't check now that I checked this one: 

Get https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/styles/ir-blacK.min.css net::ERR_ABORTED 404

**Comment by xololunatic** [comment]
Also can you please help me with this too: 
When I put tfm in u subfolder  '/x/u '  
and edit this code like this

$root_path = $_SERVER['DOCUMENT_ROOT'].'/x/u';
$root_url = 'x/u';   or $root_url = '../x/u';

it works fine but when i login it take me here example.com/x/u/x/u/index.php    it repeats /x/u i tried to modify $root_url 
it worked but created another problem now the files are not opening even not downloading they showing different urls? 
Tell me what to do please?

**Comment by ner00** [comment]
This issue seems obsolete, especially considering the redundancy with from https://github.com/prasathmani/tinyfilemanager/issues/1021

I'd advise to close one of these issues.
