### ISSUE TITLE
Rating system

### ISSUE THREAD

**Issue by TuKo1982** [prasathmani/tinyfilemanager#1020]
Hi,

TinyFileManager is really a great tool, many thanks for it.

Would it be possible to add a simple rating system for each file (i.e. stars from 1 to 5) ?

This would be very handy for my use

**Comment by ner00** [comment]
This request should be ignored and closed. Requester doesn't even account for the dependencies required to implement such functionality. A rating system would require a database to keep track of ratings, this falls way out of the scope of this project; and even if it were to be considered, there are many functionalities that would take precedent over this if DBMS-assisted functionality was ever implemented.

Close issue as it's not realistic for the project as it stands.
