### ISSUE TITLE
Some Bugs in New 2.5.3

### ISSUE THREAD

**Issue by xololunatic** [prasathmani/tinyfilemanager#1021]
1. First one is about Upload from URL. Not working totally clicked a lot of times. It is not showing the URL input box at ll

![brave_0VmaDNwglS](https://user-images.githubusercontent.com/97784387/231948864-2a72fc92-de3b-4f1f-86b0-9ad83ebfb424.gif)

2. 2nd one is about Advanced Editor (which worked fine in 2.5.0 and 2.4.7 ) but now it's not working maybe because of an offline shift or something. I checked the console it currently shows this type of error GET "https://example.com/x/u/assets/js/theme-monokai.js" 404

![brave_W9tdvRnAVc](https://user-images.githubusercontent.com/97784387/231949441-14f93367-0fa5-462a-a365-5b5b35771dbb.gif)

3. 3rd one is about highlight.js which I already put in another issue. That time I was using 2.5.0 but now also in 2.5.3 it's not working at all but it's weird that it was working on localhost. So this issue could only be Mine maybe but please suggest something to fix that

![lQ9SlHAvlH](https://user-images.githubusercontent.com/97784387/231949791-c8e1858c-4308-4c0c-a441-21c18be13e7b.png)

4. 4th one is the MAJOR ISSUE. In 2.5.3 when logging in it should take us to the tfm.php file or (modified index.php) but when login is complete it's taking us to the website main URL. For example, if I have tfm in www.example.com/tfm/index.php (index.php is tfm) then after logging in it redirects to www.example.com and then I have to press back on the browser then it takes me to www.example.com/tfm/index.php

5th one was an issue with subfolder and download links but I think it's fixed in 2.5.4 I tried it SO its good to go.

I HOPE THESE GET FIXED SOON. IF I MADE ANY MISTAKE POSTING THIS/ THEN I APOLOGIZE AND I AM NEW TO THIS TFM. SO CUT ME SOME SLACK.

**Comment by mrihtar** [comment]
About the 4th issue: the solution would be to change redirection in lines 323 and 327 from
`fm_redirect(FM_ROOT_URL);`
to
`fm_redirect(FM_SELF_URL);`

Also, there's another issue in the latest offline version - supplied tinyfilemanager-2.5.3.zip, which can be downloaded from the Releases section, includes file `assests/js/datatables.min.js`, but the code references `assests/js/dataTables.min.js` (with a capital T).

**Comment by xololunatic** [comment]
Thanks for the reply. Literally everyone ghosted issues that I posted. Hope they will look into the matter. I think these are simple issues which can be solved easily instead of adding new features.

**Comment by ner00** [comment]
I think all these issues have been solved by now, no?
Personally, I never experienced 1, 2, or 3 - are you using the master branch version of the offline branch?

4. is definitely fixed: https://github.com/prasathmani/tinyfilemanager/pull/1031

**Comment by xololunatic** [comment]
@ner00 You are right they have been fixed but personally the 3rd one is still not working for me and i don't know why... I think everyone else's are working fine. I don't know what is the problem of highlight.js on my website (i think its becoz i have not implemented node.js for that ) so maybe that's Why i really don't know...

**Comment by ner00** [comment]
For me that issue only happens if somehow the resource `highlight.min.js` fails to load.

**Comment by xololunatic** [comment]
@ner00 My advance editor works fine for all file types i have php, html and all others.. I only have problem with highlight.js .... Not only html but every type it doesn't apply highlight.js to any of my files.... I don't get it why.. i am using online version (I too thought that this could be a problem resource so i checked online one) what is interesting is if I use same tinyfilesmanager.php file on localhost (xampp) the highlight.js works.for every file I have but when I put the same tinyfilesmanager.php file.to my website... The highlights.js does not work at all or any kind of file. It is like its isn't present in the code.. I don't know.if anyone can explain that... I am so confused that's why i am blaming my servers for that... Because I don't Know where the problem is..

**Comment by ner00** [comment]
Close this or change the tile to be more specific.
