### ISSUE TITLE
Cannot upload .png file

### ISSUE THREAD

**Issue by TheXisco** [prasathmani/tinyfilemanager#103]
I have problems uploading pictures whose extension is .png. On the other hand, I have not problems with the rest of extensions.

**Comment by prasathmani** [comment]
mostly problem with the file size, check with small size PNG files. 
change the maximum upload file size for PHP  - upload_max_filesize, post_max_size

**Comment by prasathmani** [comment]
Feel free to reopen if your issue is not solved
