### ISSUE TITLE
I have a question about url and direct link

### ISSUE THREAD

**Issue by hamood1200** [prasathmani/tinyfilemanager#1045]
Im new to this script  and i have instlled it but when i run the code using my host for example
www.example.com
the website works but it directs me into 
www.example.com/index.php?p=

and it looks not clear to be honest, i tried to fix it but i couldn't 

thanks a lot

**Comment by prasathmani** [comment]
tinyfilemanager will redirect `?p=` every time you navigate, it is an expected behaviour

**Comment by hamood1200** [comment]
but in the demo version , the url was so clean there was no ?p=
also i tried to use .htacess and it didnt work 
so do you have another plans?

**Comment by prasathmani** [comment]
I'm using iframe in the demo.
