### ISSUE TITLE
site ground blacklisting tinyfilemanager as malware

### ISSUE THREAD

**Issue by geolaw** [prasathmani/tinyfilemanager#1050]
I had a copy of tinyfilemanager under my wordpress website to manage some downloads for my wife's book club - I recently moved my website to siteground and immediately after uploading the directory containing tinyfilemanager, they flagged my site for hosting malicious code. :( 
bye bye tinyfilemanager

![9D35405A-110F-4749-B29E-F1AD583293E8](https://github.com/prasathmani/tinyfilemanager/assets/1840954/b7d3c2c3-282d-4ca6-89cd-ceced5e06eff)

**Comment by 3IceCube** [comment]
[https://github.com/prasathmani/tinyfilemanager/issues/995#issuecomment-1481521008](url)

remove line 6 of the .php file of tinyfilemanager. Then save it and upload.

the line contains- H3K | Tiny File Manager Vx.x.x

**Comment by 3IceCube** [comment]
> [https://github.com/prasathmani/tinyfilemanager/issues/995#issuecomment-1481521008](url)
> 
> remove line 6 of the .php file of tinyfilemanager. Then save it and upload.
> 
> the line contains- H3K | Tiny File Manager Vx.x.x

Check #995

**Comment by ner00** [comment]
Read https://github.com/prasathmani/tinyfilemanager/issues/999#issuecomment-1565560510 and the close this issue as it is not an issue that originates from TFM simply because it cannot control how systems perceive it.
