### ISSUE TITLE
Setup thumbail and preview, as the folder path is outside of the web folder.

### ISSUE THREAD

**Issue by pisceskaze** [prasathmani/tinyfilemanager#1052]
I have finally successfully install and setting it up, but not with thumbnail and preview, since my file folder are outside my web folder, I can't seems to find a way.

Know that the TFM.php are in my subdomain's folder, whiles the files to be explore are in another folder outside of the web.

Is there a way for this?

**Comment by prasathmani** [comment]
tfm will work only under web directory.

**Comment by Alvin-He** [comment]
I don't really know about cPanel, but that's how I did it with apache. 

You probably also need to allow that directory(the one outside of the web folders) to be able to be accessed in your web server's configs
