### ISSUE TITLE
$root_path / $root_url for Beginners

### ISSUE THREAD

**Issue by MGPhil** [prasathmani/tinyfilemanager#1055]
Hello, I checked all issues and tested different combinations but cannot get the open and link button to show the right path...
Everything else works like it should...great tool by the way!

I put tinyfilemanger.php inside a subfolder in my main http directory "webpage" called "filebrowser".
The $_SERVER['DOCUMENT_ROOT'] echos as "/data/web/e00000/html/webpage"
Inside webpage is the folder "filebrowser" with the folders "assets" and "Files" and the tinyfilemanger.php
Inside the folder "Files" are all the files to be shared and uploaded.

User and Admin were set to "/data/web/e00000/html/webpage/filebrowser/Files" under $directories_users.
That works like intended only that folder is visible and uploads go right there.

But when I now click on preview or the link to file button the link looks like:
https://www.webpage.com/filebrowser/data/web/e00000/html/webpage/filebrowser/Files/file.pdf

How can I remove "data/web/e00000/html/webpage/filebrowser/" from the link so that the link looks like:
"https://www.webpage.com/filebrowser/Files/file.pdf"

Thanks a lot

**Comment by MGPhil** [comment]
Can nobody help? Still missing a solution, thanks.

**Comment by jolz** [comment]
Not shure about your setup. You should have something like 
```php
# absolute path in local file system
$root_path = $_SERVER['DOCUMENT_ROOT']  . "/filebrowser/Files";

# relative path in Browser URL 
$root_url = "/";
```

Hope this helps.

**Comment by MGPhil** [comment]
Unfortunately not, still "data/web/e00000/html/webpage/filebrowser/" is in the link to each file...

**Comment by MGPhil** [comment]
Ok, now I tried a different $directories_users + $root_path combination and got it to work! Thanks for the help!
