### ISSUE TITLE
Feature Request -- 2FA Implement TOTP Login/Authentication

### ISSUE THREAD

**Issue by m267541** [prasathmani/tinyfilemanager#106]
Hi, I found tinyfilemanager very simple to use, and very fast.
Thanks.

but one feature maybe can make it more better.
is it possible, implement TOTP Login/Authentication?

**Comment by johnwmail** [comment]
Hi, I found this "https://github.com/PHPGangsta/GoogleAuthenticator" very simple to use,
I edit the code to support TOTP Login/Authentication (and fetch user info from mysql).
and it just work.
Thanks.

I do not know, how to paste the code here, so I attached it.
[index.php.txt](https://github.com/prasathmani/tinyfilemanager/files/2683566/index.php.txt)
