### ISSUE TITLE
How to disable authentication for users

### ISSUE THREAD

**Issue by Gilbertdelyon** [prasathmani/tinyfilemanager#1060]
In `config.php` we can set  `$use_auth = false;`  or  `$use_auth = true; `.
When  set to "false" everybody has full rights. 

but our need would be a little bit finer grained, as follows:
- without authentication everybody can only read, 
- only admin needs athentication
Please, is there a way to set `config.php` in this way?

**Comment by Gilbertdelyon** [comment]
@prasathmani 
Thank you for prompt answer.

> set $use_auth = false; and $global_readonly = true;

It doesn't work as expected:
- The good point: without authentication everybody can only read,
- The bad point:   admin cannot log and consequently he can only read, while I would like him to get all the rights

**Comment by prasathmani** [comment]
for admin use duplicate tfm with auth enabled.  #825

**Comment by Gilbertdelyon** [comment]
Thank you,
This is what I did in the meantime. It works, but I thought there would be a simpler way.
