### ISSUE TITLE
Download ONLY the first file

### ISSUE THREAD

**Issue by Gilbertdelyon** [prasathmani/tinyfilemanager#1062]
**Steps to reproduce:**
Open TinyFileManager.
Open a folder
Click the download button of a first file . The file is downloaded. It works!
Click the download button of a another file. The first file is downloaded again. 👎 
Click the download button of a another file. The first file is downloaded again. 👎 
and again as long as you do not refresh the page

**Comment by Gilbertdelyon** [comment]
Sorry, this issue was with an old version
I just downloaded master version and... IT WORKS!

**Comment by Monoverde888** [comment]
then close the issue
