### ISSUE TITLE
BAILOUT malware detected

### ISSUE THREAD

**Issue by znbn** [prasathmani/tinyfilemanager#1067]
"BAILOUT malware detected": I have this message if I create a new empty file with CPanel file manager, edit it and paste the code of tinyfilemanager into it.

If I upload the tinyfilemanager.php on the server, it is even not created at all.

I think it is a False Positive case, but how could I solve the issue?

Does anyone has a suggestion?

Thanks

P.S.
I'm on a web hosting server... I can't stop any running service.

**Comment by znbn** [comment]
UNBELIVABLE !!!!

I just had to remove line number 6 from the source file and the code is accepted! (

The line is:
 * H3K | Tiny File Manager V2.5.3

It should be a devil's fingerprint

I replaced it with 

* H3K - Tiny File Manager v2.5.3

If anyone experienced the same issue, let us know.

Bye

**Comment by prasathmani** [comment]
#273 , #985

**Comment by mhaiskar** [comment]
Considering this issue is or will be faced by others, @prasathmani is it worth it to make this change official and bring out an update?
Thanks.
