### ISSUE TITLE
Use chunking from dropzone

### ISSUE THREAD

**Issue by kikoun** [prasathmani/tinyfilemanager#107]
Why do not use dropzone.js chunking ability to rule out timeout, sizes issues or http server settings like post_max_size ?

https://www.dropzonejs.com/#config-chunking

**Comment by cahek-555** [comment]
Solidarity, you can split large files into chunk. There is a need for this mode.

**Comment by AndreFabris** [comment]
+1. You can actually easily enable it by addding chunking: enable, the real issue is adding the code to merge the chunks into one file

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
