### ISSUE TITLE
Settings - Theme and Hide Perms/Owner columns can not be toggled

### ISSUE THREAD

**Issue by SeDi343** [prasathmani/tinyfilemanager#1071]
![image](https://github.com/prasathmani/tinyfilemanager/assets/3628936/27bf7fe4-9de1-4068-89d8-f6f5a6bcba85)

I am unable to change Theme to dark and toggle on Hide Perms/Owner columns. When pressing Save it switches back to light Theme and toggled off Hide Perms/Owner columns.

**Comment by prasathmani** [comment]
are you using external configuration and check have write permission as well.

**Comment by SeDi343** [comment]
my config.php has permissions 666 and my index.php has 664.
I can only configure it throgh the Default Configuration $CONFIG string in index.php but not through the UI

**Comment by SeDi343** [comment]
Okay, changing permissions of index.php to 666 made it work but I have to change settings and save them once after another and have to configure it twice. meaning change theme to dark - save - change theme to dark - save
