### ISSUE TITLE
file encryption

### ISSUE THREAD

**Issue by djsaikrishna** [prasathmani/tinyfilemanager#1089]
need feature

when i upload any video or zip 
file extension should be hide in hosting file manager 

ex :-  i just uploaded sampe.mp4 video in tinyfilemanager  so now in hosting file manager that filename should be like fsde547nhhd6sxvffdxccvb like this without extension 

if is it possible please implement in tiny filemanager 

Thank you.

**Comment by prasathmani** [comment]
@djsaikrishna , current version doesn't have this option. but you can change the code for upload logic here https://github.com/prasathmani/tinyfilemanager/blob/43063e474684816fdb21915d139998c8483a8d5b/tinyfilemanager.php#L916
