### ISSUE TITLE
Reguest: Disable path to linked directories

### ISSUE THREAD

**Issue by lianergoist** [prasathmani/tinyfilemanager#1106]
I want to give the users access to a shared folder, so I have created a link (called 'Fælles') to that folder - but tinyfilemanager show the path to that folder. I don't want that. Is it possible to disaple it (I don't mind editing the script)? Or, maybe it should be an option in config to turn the path on and off?

![billede](https://github.com/prasathmani/tinyfilemanager/assets/6023573/4ac5d7c9-2f71-4cc6-ab47-542f72cabcf7)

**Comment by prasathmani** [comment]
<img width="1242" alt="image" src="https://github.com/prasathmani/tinyfilemanager/assets/11345598/7883b813-70d6-4c10-9d34-329f1ff06145">

**Comment by lianergoist** [comment]
> <img alt="image" width="1242" src="https://user-images.githubusercontent.com/11345598/282480965-7883b813-70d6-4c10-9d34-329f1ff06145.png">

Thank you for your reply.  I think you misunderstand. I don't want to exclude the folder. I want to show the folder "Fælles", but I don't want the  " → /var/www/html/garage/filer" part.
