### ISSUE TITLE
Video upload splitting in parts

### ISSUE THREAD

**Issue by NinoNikoles** [prasathmani/tinyfilemanager#1109]
If I try to upload a mp4 the video gets splitt into a video file and a part file. I'm getting no error. 
$max_upload_size_bytes = 10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
(For test case :D )
The video is 10mb large so it should work.
And yes mp4 upload is enabled

*Smaller Video with 7MB worked. But above 10MB no more.
PHP.ini is also setup up correctly for larger upload

**Comment by prasathmani** [comment]
disable chunk upload and try

```php
chunking: false,
forceChunking: false,
```

<img width="527" alt="image" src="https://github.com/prasathmani/tinyfilemanager/assets/11345598/26a60f2a-621c-43d1-aab0-19d3854970db">

**Comment by milankragujevic** [comment]
@prasathmani Disabling chunking does let the file be uploaded, but the file name is wrong, it's the name of it's folder not the actual file name. please fix.
