### ISSUE TITLE
problem with $exclude_items

### ISSUE THREAD

**Issue by 99zs** [prasathmani/tinyfilemanager#1129]
Not working with f.ex.:
```
'*_t.jpg'
'*-t.jpg'
'*_thumb.jpg'
'*-thumb.jpg'
'*t.jpg'
```
maybe a better solution would be to search the full file name for the occurrence of a given phrase?

**Comment by prasathmani** [comment]
Wildcard searches are not supported.

**Comment by 99zs** [comment]
Is it really problem to supported it? Because it would significantly increase the possibility of using this option. But this option is lame. It&#39;s a bit like art for art&#39;s sake.  Brgs. 
     
      
       
        Dnia 02 stycznia 2024 04:24 Prasath Mani ***@***.***&gt; napisał(a):
       
    
       
         
 Wildcard searches are not supported.
