### ISSUE TITLE
uploaded image's copy path is not correct

### ISSUE THREAD

**Issue by jessicastorm1986** [prasathmani/tinyfilemanager#113]
Hii,

Link to check - http://sapphireprofits.com/mrc-imgs/tinyfilemanager.php

> Please use admin credentials

Added specific directory path -

`$directories_users = array(
    'admin' => '/home3/sapphire/public_html/mrc-imgs/',
    'user' => '/home3/sapphire/public_html/mrc-imgs/'
    );`

When trying to copy the uploaded image or open it, its trying from -  **http://sapphireprofits.com/sunset.jpg**

Another issue is, it is not excluding the file tinyfilemanager.php

i tried like this

`// Array of files and folders excluded from listing
$GLOBALS['exclude_items'] = array(
    '/home3/sapphire/public_html/mrc-imgs/tinyfilemanger.php',
    'tinyfilemanger.php
    );`

Please help

**Comment by prasathmani** [comment]
@jessicastorm1986 , open images [http://sapphireprofits.com/mrc-imgs/sunset.jpg](http://sapphireprofits.com/mrc-imgs/sunset.jpg) and to hide `tinyfilemanager.php` , add in `exclude_items` with same name. i can see name is different in your file.

**Comment by jessicastorm1986** [comment]
its tinyfilemanager.php everywhere, where is the name different can you please guide

**Comment by jessicastorm1986** [comment]
in actions there should be an option of copy direct link

**Comment by prasathmani** [comment]
> in actions there should be an option of copy direct link

I'll try in feature releases
