### ISSUE TITLE
Overwrite during upload

### ISSUE THREAD

**Issue by markknol** [prasathmani/tinyfilemanager#1133]
First of all; what a great project. I was looking for exactly this, just a one pager doing everything you want on a server. I am hoping to use this instead of ftp for a few usages.

Question; is it possible to overwrite a file? Now if I upload a file called index.php it converts that to  index_240107200913.php. 
Maybe I'm missing something but couldnt find an option for this. Would maybe be nice if it was the opposite; the old file get renamed to its datetime, and new file will be called like how you uploaded it. Then you have some kind of version control.

**Comment by prasathmani** [comment]
@markknol  remove the `if` condition to avoid file name convert
https://github.com/prasathmani/tinyfilemanager/blob/8e87afae5b744c3e23490000bf0d398d6d4a749c/tinyfilemanager.php#L1016C17-L1016C17

```php
if ($chunkIndex == $chunkTotal - 1) {
                    if (file_exists ($fullPath)) {
                        $ext_1 = $ext ? '.'.$ext : '';
                        $fullPathTarget = $path . '/' . basename($fullPathInput, $ext_1) .'_'. date('ymdHis'). $ext_1;
                    } else {
                        $fullPathTarget = $fullPath;
                    }
                    rename("{$fullPath}.part", $fullPathTarget);
                }
 ```
 
 you can also check out the recent changes in file name conversation logic PR. 
 https://github.com/prasathmani/tinyfilemanager/commit/00541fc469fe2ddf3fc519c4074490c54380d983

**Comment by SuperUser-exe** [comment]
please can you reply the code after remove if condition because i tried not working , so please share the code i will replace it, til now overwrite not working
