### ISSUE TITLE
Google has blocked my website for a phishing content

### ISSUE THREAD

**Issue by znaczki654** [prasathmani/tinyfilemanager#114]
I found that my site was warned by google that it's deceptive website in which users can have stolen some user's credential. And futher more, it wasn't only the part with the file you've sent, but the whole website was flagged.

Also before the warning, google chrome has its own warning when I was visiting this site as it may be phishing, but other web browsers doesn't and it was only on site reserved for a tiny file manager file called ftp.php .

Now the site is flagged and even on firefox it shows a red banner, because firefox uses google's safe browsing API.

I hope it's been fixed by now but for security reasons I'll send you the code.
The version of Tiny File Manager is 2.1.

Hope the newest version doesn't have that security leak.

Regards, Jan.

Code:
https://pastebin.com/u6ssseeG

**Comment by scorcher9** [comment]
@znaczki654 Were you using the default password which is "admin", or did you change it?

**Comment by simon511000** [comment]
I'm sure this problem has nothing to do with tinyfilemanager, is your site in HTTPS, and if so, could you regenerate the certificate?

Also, if your site is in HTTPS, can you just test with HTTP? Do you still have the problem?

Good luck ;)

**Comment by znaczki654** [comment]
I've updated the version and since 04th January they haven't blocked my website so it might be right now.
