### ISSUE TITLE
Upload from URL overwrites existing file while normal upload renames file

### ISSUE THREAD

**Issue by RavanH** [prasathmani/tinyfilemanager#1143]
Hi, 

When doing a normal Upload file and a file with the same name already exists, then the new file will get a unique name suffix to prevent the old file from being overwritten. But when going through Upload from URL, this does not happen. The original file will get overwritten without any warning.

This might need a bit more thought...

1. Make the behavior **coherent** between the two upload methods
2. Maybe add a config option to allow switching between **rename** and **replace**?

**Comment by prasathmani** [comment]
check this out #1133
