### ISSUE TITLE
How does your demo host on gh-pages

### ISSUE THREAD

**Issue by unclehowell** [prasathmani/tinyfilemanager#1145]
I thought gh-pages doesn't support server-side script like php. 
So I wondered how you have your demo running. Interesting.

**Comment by prasathmani** [comment]
@unclehowell  I'm using [alwaysdata.com](https://www.alwaysdata.com/en/) free hosting service to host. it is included as an iframe in the demo page.

**Comment by unclehowell** [comment]
That's cool. Also, I have another question. I remember this php file I used for managing my Latex/ RST docs. And I remember it also featured a build button, so I could compile my text into PDF's. What happened to that? Was than an older version of your solution or another project.
