### ISSUE TITLE
Unable to open DOCX or PDF 

### ISSUE THREAD

**Issue by iz1kbp** [prasathmani/tinyfilemanager#1148]
Sorry in advance for my poor english.
I use filemaneger to store my personal file in my webspace.
When I press view button to view a docx or pdf file, it give me error 404 , file not found
note: my Tiny manager is under a directory htaccs protected....may be this is the problem?
If i try to open your files from your demo, all work's fine
thank's for the support
Mario

**Comment by prasathmani** [comment]
docx or pdf preview will work when the file publicly accessible

**Comment by iz1kbp** [comment]
Ok if I've understand well,without htacces restriction...all will be fine..right?

**Comment by prasathmani** [comment]
yes
