### ISSUE TITLE
Remote access to an external server

### ISSUE THREAD

**Issue by iinfotecnica** [prasathmani/tinyfilemanager#1150]
Hello, could you ask me a question?
I would like to know if it would be possible to use the system for remote access.
Example managing another server remotely.

Example meusite.com accessing directory on siteexterno.com

Doubt!

I tried to make some adjustments with the SSH connection, but without success.

Would it be possible to connect the remote server via ssh in php and point to the directory $root_path ='aqui';

If anyone can help

**Comment by prasathmani** [comment]
The SSH support is not available in the current TFM version.
