### ISSUE TITLE
Saving settings doesn't save

### ISSUE THREAD

**Issue by znaczki654** [prasathmani/tinyfilemanager#116]
Hi, when you click on the user name (admin for example) then settings and you change hidden files or error reporting to "on" and click "save" nothing happens.
Version 2.3

**Comment by prasathmani** [comment]
`tinyfilemanager.php` need write permission to save settings. check your file permission

**Comment by znaczki654** [comment]
> 
> 
> `tinyfilemanager.php` need write permission to save settings. check your file permission

I've changed the permissions to 777, even though it doesn't work. I've tried on XAMPP as well as webhost site, in the previous version hidden files worked but there was no option to change it.

**Comment by prasathmani** [comment]
After saving check  the line no. 3 is getting updated. or you can also configure manually here
![image](https://user-images.githubusercontent.com/11345598/50973779-b660ca00-150f-11e9-802b-a513956631ab.png)

**Comment by znaczki654** [comment]
It doesn't change automatically, I actually figured it out that this statement helps as well. But options doesn't work for me either...
![obraz](https://user-images.githubusercontent.com/27486533/50974141-d29e4000-14ea-11e9-9599-182c87c730cb.png)

**Comment by znaczki654** [comment]
Your suggestion works, but it sill doesn't save the changes in config variable. Could you change it in the further update? Also can you tell me if it's only me who's getting that kind of issue?

**Comment by znaczki654** [comment]
I've checked this on tow computers, I've also disabled adblock and antivirus if that's the thing causing issue, but still it doesn't work for me. I've checked this on chrome and firefox as well.

**Comment by znaczki654** [comment]
I don't know what to do...

**Comment by prasathmani** [comment]
did you able to change the language ?

**Comment by loulou2852** [comment]
I've got the same problem with my host too. I just download the repo today

**Comment by znaczki654** [comment]
I don't know how to add the language, it simply doesn't save changes. Save button does nothing.

**Comment by prasathmani** [comment]
check with the developer console, you're getting any error after saving? I've tried in my local not able to find. mostly problem with file permission.

**Comment by znaczki654** [comment]
![error](https://user-images.githubusercontent.com/27486533/51275459-55833700-19d2-11e9-9629-a8344f838721.PNG)
There is one issue.

**Comment by znaczki654** [comment]
But it shows up only on chrome, while in firefox doesn't but also it doesn't save on both one.

**Comment by prasathmani** [comment]
@znaczki654  try now, I've fixed `ArgumentCountError`.

**Comment by znaczki654** [comment]
Now it works, thank you :). The issue is closed.
