### ISSUE TITLE
script itself deletion

### ISSUE THREAD

**Issue by tom-vb** [prasathmani/tinyfilemanager#1160]
The script deletes itself as an index.php empty file if its has write permissions

**Comment by prasathmani** [comment]
duplicate https://github.com/prasathmani/tinyfilemanager/issues/995 https://github.com/prasathmani/tinyfilemanager/issues/273

**Comment by tom-vb** [comment]
Thank's, I see now  it's duplicated but I have reviewed #995 and #273 and not been able to find a solution. There is a solution for this issue?
