### ISSUE TITLE
Ownership and permission for root folder

### ISSUE THREAD

**Issue by thomaslvz** [prasathmani/tinyfilemanager#1169]
Hi all,
I have read a lot of issues here and it is not clear to me, so I make a new one

My root path is set to :
`$root_path = $_SERVER['DOCUMENT_ROOT'].'files';`

and i want to know what ownership and permission settings should be granted for my folder `files`. It is currently set to 

`drw-rw----    tinyfilemanager www-data`

But this doesnt work, and I dont want to set it to `777` (even though this makes it work) to keep things clean.

**Comment by hestiacn** [comment]
Just in the root directory of your web page. There is no point in setting this up. Please refer to: chmod 644 /home/admin/web/Example.com/public_html

**Comment by thomaslvz** [comment]
Thanks for answering.
What you say does not seem right to me. 
My web page is within `/var/www/tinyfilemanager`, my root directory is set to `/var/www/tinyfilemanager/files`.
If I do `chmod -R 644 /var/www/tinyfilemanager/files` my files are not visible from my web browser.
I did `chmod -R 755 /var/www/tinyfilemanager/files` , this seems to work now

**Comment by hestiacn** [comment]
In fact, /tinyfilemanager can be set to lindex.php and it can become the default access file by directly opening the domain name.
