### ISSUE TITLE
cannot preview files

### ISSUE THREAD

**Issue by mrxehmad** [prasathmani/tinyfilemanager#1175]
# Cannot preview files
I just installed this file browser to /var/www/html but in Root path for file manager
`$root_path = '/DATA/Guest';`

 /DATA/Guest is where my files are stored 

files are not preview nor direct link work only download button work
Please let me know how do i resolve this issue

![image](https://github.com/prasathmani/tinyfilemanager/assets/118040902/1a16d040-2450-4e8d-9e2f-16be30b8b28f)

**Comment by prasathmani** [comment]
try this,
```php
$root_path = $_SERVER['DOCUMENT_ROOT'].'/DATA/Guest';
$root_url = 'DATA/Guest';
```

**Comment by mrxehmad** [comment]
Thanks Man
