### ISSUE TITLE
Please help 

### ISSUE THREAD

**Issue by dawidostroda** [prasathmani/tinyfilemanager#118]
Hello . please help me . 

Im try add tinyfile manager to me website but i have problem . I dont now how add this code :

define('FM_EMBED', true);
define('FM_SELF_URL', $_SERVER['PHP_SELF']);
require 'path/tinyfilemanager.php';

tinyfilemanager.php its : 
https://mewebsite/oc-admin/index.php?page=plugins&action=renderplugin&file=menager/admin/config.php

but i see only : 

Tiny File Manager
Error: Cannot load configuration

**Comment by prasathmani** [comment]
this kind of error occurs when missing `$CONFIG` in line no 3. check whether `$CONFIG` is there ?

**Comment by dawidostroda** [comment]
i have this : 


<?php
//Default Configuration
$CONFIG = '{"lang":"en","error_reporting":false,"show_hidden":false}';

/**
 * H3K | Tiny File Manager V2.3
 * CCP Programmers | ccpprogrammers@gmail.com
 * https://tinyfilemanager.github.io
 */

Im try add to other script . i need something like that : 

![tiny-file-manager-embed](https://user-images.githubusercontent.com/46688553/51195227-f7305880-18ec-11e9-9766-3ed9b03f0b65.png)

**Comment by dawidostroda** [comment]
$CONFIG = '{"lang":"en","error_reporting":false,"show_hidden":false}';

**Comment by prasathmani** [comment]
ok, first try with a simple PHP file, then try to integrate with your application.
```
<? php
define('FM_EMBED', true); 
define('FM_SELF_URL', $_SERVER['PHP_SELF']);
require 'path/tinyfilemanager.php';
?>
```
first try with above code alone in single file, if it's working then try with your application. some time `config` will break due to url rewrite.

**Comment by dawidostroda** [comment]
![prsc](https://user-images.githubusercontent.com/46688553/51197578-41680880-18f2-11e9-97f4-0dbf7019b838.jpg)

**Comment by dawidostroda** [comment]
still it's this error :( damm .....

**Comment by dawidostroda** [comment]
im added to me config.php please look 
[config.zip](https://github.com/prasathmani/tinyfilemanager/files/2760755/config.zip)

**Comment by prasathmani** [comment]
try with this
[config.zip](https://github.com/prasathmani/tinyfilemanager/files/2760814/config.zip)

**Comment by dawidostroda** [comment]
no work back to start page (dashbord)

**Comment by dawidostroda** [comment]
back to this : http://localhost/oc-admin/index.php?p= automatic

**Comment by dawidostroda** [comment]
route to me file config.php

http://localhost/oc-admin/index.php?page=plugins&action=renderplugin&file=menager/admin/config.php

**Comment by prasathmani** [comment]
[config.zip](https://github.com/prasathmani/tinyfilemanager/files/2760914/config.zip)

**Comment by dawidostroda** [comment]
no way :) woorking yeee only some css its demege 
![css error](https://user-images.githubusercontent.com/46688553/51201982-d3c1d980-18fd-11e9-9d62-494d85388635.jpg)

**Comment by dawidostroda** [comment]
Thank You very mutch . :)

**Comment by prasathmani** [comment]
Note: All feature will not work, I've added your query param directly in file manager, and replaced only in few place to make it work. 
So you have to replace all `'?p='` to `$query.'&=p'`  then it will work perfectly
![image](https://user-images.githubusercontent.com/11345598/51202164-1eeee300-1924-11e9-9b88-0d3e65db35dc.png)

**Comment by dawidostroda** [comment]
its done thanks :)
