### ISSUE TITLE
"Open" error if "root_path" is on different location

### ISSUE THREAD

**Issue by logread** [prasathmani/tinyfilemanager#1181]
if _`tinyfilemanager.php`_ is on **_`/www`_** and root_path set to _**`/not_www`**_ , when you open a file which the absolute path is _`/not_www/file.txt`_ it will be opened in _`https://domain.tld/file.txt`_ which basically load a file from _`/www/file.txt`_, therefore throws a "not found/404" error.

**Comment by prasathmani** [comment]
if `$root_path` is changed then `$root_url` need to be adjusted accordingly

**Comment by logread** [comment]
isn't `$root_url` need to be in subdir of `$root_path` ? would you mind give me example of `$root_url` value in this case ?

**Comment by logread** [comment]
curently i set it like this (in nginx)
```
server {
	...
	root /not_www;
	...
	location / {
		try_files $uri /index.php;
	}
	location =/index.php {
		...
		root /www;
		fastcgi_param SCRIPT_FILENAME /www/$fastcgi_script_name;
		...
	}
}

```
looks like the upload functionality is broken, i'm still investigating
