### ISSUE TITLE
User's subfolder problem

### ISSUE THREAD

**Issue by panverger** [prasathmani/tinyfilemanager#120]
When you set specific directory for user direct link is not formed correct
I added a new line under 143 and now is ok
Check it yourself
// clean $root_url
$root_url = fm_clean_path($root_url);

New line
**$root_url = isset($directories_users[$_SESSION[FM_SESSION_ID]['logged']]) ? $root_url.'fm/'.$directories_users[$_SESSION[FM_SESSION_ID]['logged']] : $root_url**;

**Comment by panverger** [comment]
fm is the installation folder in new line

**Comment by panverger** [comment]
final solution - adding these lines all are ok
if (isset($_SESSION[FM_SESSION_ID]['logged'])) {
$wd = dirname($_SERVER['PHP_SELF']);
$wd = ltrim($wd, '/');
$root_url = !empty($directories_users[$_SESSION[FM_SESSION_ID]['logged']]) ? $root_url. $wd. '/'.$directories_users[$_SESSION[FM_SESSION_ID]['logged']] : $root_url; 
}

**Comment by prasathmani** [comment]
@panverger added your solution. It will work for normal flow(using `DOCUMENT_ROOT`), 
Problem still exist on flowing cases,
-  Using different `$root_path` 
    >`$root_path = $_SERVER['DOCUMENT_ROOT'].'my-folder';`
- If users directories configured outside the tinyfilemanager.php folder
```
$directories_users = array(
     'demo' => '../demo-folder'
);
```

**Comment by panverger** [comment]
Thank's a lot. It's a very useful code. I'll be using this file while teaching my class. Every student has his own folder where he can save his exercises.

**Comment by simon511000** [comment]
Hey @panverger ! I also recommend [agora](https://www.agora-project.net/index.php?curTrad=english), my technology teacher uses it

**Comment by prasathmani** [comment]
Closing the ticket as the primary problem solved and with known issues.
