### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by RS-Design** [prasathmani/tinyfilemanager#1203]
Running php 7.2. I have tested in osx Safari and Chrome on two different Mac's, I get the same problem on both devices/browsers. When I link to TFM I get a blank screen, body tags contain nothing. If I make any change to tinyfilemanager.php, eg; update the exclude_items array, or change the root path and root url, reload the page I can then log in, once logged in I can undo whatever changes I made, refresh the page and everything works. I have tested with a completely unaltered version of tinyfilemanager.php and a version with auth_users,  root_path and root_url changes, both version experience the same problem. I'm stumped?

**Comment by prasathmani** [comment]
did you check PHP error log ?
