### ISSUE TITLE
Customize Login Page Logo

### ISSUE THREAD

**Issue by jharbin** [prasathmani/tinyfilemanager#1207]
In the GUI config, it would be nice to be able to upload and select a Login page logo.  It's displaying the default "H3K" logo and I'm not sure where to change that.

**Comment by prasathmani** [comment]
change [here](https://github.com/prasathmani/tinyfilemanager/blob/1bcc2401195fc33b1f3773d68e57e19889c1a104/tinyfilemanager.php#L356)
