### ISSUE TITLE
upload get error

### ISSUE THREAD

**Issue by carlsue** [prasathmani/tinyfilemanager#121]
![tim 20190123191457](https://user-images.githubusercontent.com/17507066/51663756-a4445880-1ff2-11e9-804f-cd4d76ad6427.png)

file is small ,but get error

**Comment by prasathmani** [comment]
You need to increase the PHP max file/post size, 
try this https://stackoverflow.com/questions/3718571/request-entity-too-large-php

**Comment by prasathmani** [comment]
Feel free to reopen if your issue is not solved
