### ISSUE TITLE
Can't rename a file

### ISSUE THREAD

**Issue by Owned67** [prasathmani/tinyfilemanager#1215]
hello, i can create, delete everything but cannot rename a file... 

error:
Error while renaming from myfile.json to Testmyfile.json
edit, add other try:
Error while renaming from myfile.json to Test.json

on config.php, ive added (ive try with .json but its same):
`// Allowed file extensions for create and rename files
// e.g. 'txt,html,css,js'
$allowed_file_extensions = 'json';

// Allowed file extensions for upload files
// e.g. 'gif,png,jpg,html,txt'
$allowed_upload_extensions = 'json';`

Ive looked on developper console but no error...

using php 7.4

> fileinfo, iconv, zip and mbstring are enabled

if someone have a suggestion...

thanks

**Comment by Owned67** [comment]
Solved... need to set on tinyfilemanager.php and config.php, idk why using a config.php so? maybe im not update? ^^

**Comment by zorrobiwan** [comment]
Leave main file so you can update it with new releases. Use config.php to overwrite config from main file.
