### ISSUE TITLE
Embed into Wordpress.

### ISSUE THREAD

**Issue by ThomasMattOnline** [prasathmani/tinyfilemanager#124]
Hello, I have a basic PHP Wordpress template file and I am trying to embed using the code:

<?php
define('FM_EMBED', true);
define('FM_SELF_URL', $_SERVER['PHP_SELF']);
require 'tinyfilemanager/tinyfilemanager.php';
?>

My file is set at: portal/tinyfilemanager.php

So I have set it to there like this:

<?php
define('FM_EMBED', true);
define('FM_SELF_URL', $_SERVER['PHP_SELF']);
require 'portal/tinyfilemanager.php';
?>

However nothing happens?

I have looked into Auth users set that to true or false but still nothing! If anyone has any advice that would be extremely helpful! Thank you!

**Comment by prasathmani** [comment]
Embedding file manager in another script.

```
define('FM_EMBED', true);
define('FM_SELF_URL', $_SERVER['PHP_SELF']);
require 'path/tinyfilemanager.php';
```
[check document](https://tinyfilemanager.github.io/docs/#line5)

**Comment by ThomasMattOnline** [comment]
> Embedding file manager in another script.
> 
> ```
> define('FM_EMBED', true);
> define('FM_SELF_URL', $_SERVER['PHP_SELF']);
> require 'path/tinyfilemanager.php';
> ```
> [check document](https://tinyfilemanager.github.io/docs/#line5)

Yeah that doesn't work in wordpress..

**Comment by prasathmani** [comment]
@ThomasMattOnline , Tinyfilemanager doesn't work with WordPress templates, because WordPress and tinyfilemanager are using same query param `?p=` and tinyfilemanager has redirection on render based on file path so wordpress will be through `headers already sent` error. better try tinyfilemanager as separate file.
