### ISSUE TITLE
Simplified Chinese translation

### ISSUE THREAD

**Issue by baoang** [prasathmani/tinyfilemanager#125]
I've found this thread [here](https://github.com/prasathmani/tinyfilemanager/issues/101) raised by @[haer0248](/haer0248) , but from [his repo](https://github.com/haer0248/tinyfilemanager), I believe this is a translation for Traditional Chinese. 

Based on his contribution, I now propose another version, the Simplified Chinese version which has some slightly different variations.

Also, I want to suggest, maybe necessary, modifications for the language code. For Traditional Chinese, it may be better to set `zh-TW` for `正体中文`, and set `zh-CN` for `简体中文`.

The following code block is my translation. I did not read all the translated part because I didn't find all the corresponding places of these few terms from the software/UI (for example, *help*, *enable*). Hopefully these translated terms and words are all appropriate. For the App name, I keep it as it is because the original name, *Tiny File Manager* could be a widely accepted term/brand across the world.

```
{
      "name": "简体中文",
      "code": "zh-CN",
      "translation": {
        "AppName": "Tiny File Manager",
        "AppTitle": "文件及目录管理器",
        "Login": "登录",
        "Username": "账号",
        "Password": "密码",
        "Logout": "退出",
        "Move": "移动",
        "Copy": "拷贝",
        "Save": "保存",
        "SelectAll": "全选",
        "UnSelectAll": "取消全选",
        "File": "文件",
        "Back": "取消上传",
        "Size": "文档大小",
        "Perms": "权限",
        "Modified": "修改时间",
        "Owner": "拥有者",
        "Search": "查找",
        "NewItem": "创建新文件/文件夹",
        "Folder": "文件夹",
        "Delete": "删除",
        "CopyTo": "复制到",
        "DirectLink": "直链",
        "UploadingFiles": "上传",
        "ChangePermissions": "修改权限",
        "Copying": "复制中",
        "CreateNewItem": "创建新文件",
        "Name": "文件名",
        "AdvancedEditor": "高级编辑器",
        "RememberMe": "记住登录信息",
        "Actions": "可执行操作",
        "Upload": "上传",
        "Cancel": "取消",
        "InvertSelection": "反向选择",
        "DestinationFolder": "目标文件夹",
        "ItemType": "文件类型",
        "ItemName": "创建名称",
        "CreateNow": "创建",
        "Download": "下載",
        "UnZip": "解压缩",
        "UnZipToFolder": "解压至目标文件夹",
        "Edit": "编辑",
        "NormalEditor": "编辑器",
        "BackUp": "备份",
        "SourceFolder": "源文件夹",
        "Files": "文件",
        "Change": "修改",
        "Settings": "配置",
        "Language": "语言",
        "Open": "开启",
        "Group": "用户组",
        "Other": "其它用户",
        "Read": "读取权限",
        "Write": "写入权限",
        "Execute": "执行权限",
        "Rename": "重命名",
        "enable": "启用",
        "disable": "禁用"
      }
    }
```

**Comment by prasathmani** [comment]
@baoang, create a pull request.

**Comment by baoang** [comment]
Thank you, @prasathmani . Glad to contribute. I'll try it. I am not a skilled Github user.
