### ISSUE TITLE
Negative filesize on ARMv7 for files over 2GB

### ISSUE THREAD

**Issue by psycholyzern** [prasathmani/tinyfilemanager#127]
I have a couple of files over 2GB in size and they are displayed with negative size.
After reading some sources, turned out filesize() doesn't work well with 32-bit system for files bigger than 2GB.

I found some functions to replace filesize() that will work, but I am not sure if it is a good idea for me to edit the code by myself. Maybe you know the best method to use.

Thanks.

**Comment by prasathmani** [comment]
[Fixed](https://github.com/prasathmani/tinyfilemanager/commit/da31717cff67424c4a85c60e18ea663ebfe77081)

**Comment by psycholyzern** [comment]
Hi. Lookimg into the commit, you just added support for Windows and Linux will still be using `filesize`.

```
function fm_get_size($file)
{
    $return = filesize($file);
    if(substr(PHP_OS, 0, 3) == "WIN") {
        exec('for %I in ("'.$file.'") do @echo %~zI', $output);
        $return = $output[0];
    }
    return $return;
}
```
The code clearly would just be checking for a Windows and use specific method, but then if Linux, it would still be using filesize().

I have tried searching a solution by myself and found this solution works: https://stackoverflow.com/a/5502328

**Comment by prasathmani** [comment]
@psycholyzern your suggestion is added now. check now.

**Comment by psycholyzern** [comment]
Thanks :)
