### ISSUE TITLE
About installing via Composer

### ISSUE THREAD

**Issue by mozgbrasil** [prasathmani/tinyfilemanager#128]
Hello good afternoon

About installing via Composer

If possible make use of Composer

**Comment by prasathmani** [comment]
it is not possible now.

**Comment by AdrienPoupa** [comment]
I think the author should really support composer, as it is the best way to version dependencies. However, we can get around it.

This is how I did it:

composer.json

```json
    "require": {
        "prasathmani/tinyfilemanager": "2.4.3"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "prasathmani/tinyfilemanager",
                "version": "2.4.3",
                "source": {
                    "url": "https://github.com/prasathmani/tinyfilemanager.git",
                    "type": "git",
                    "reference":"tags/2.4.3"
                }
            }
        }
    ],
```

This will retrieve the files from the tag 2.4.3. To update in the future, change the tag by the latest version.

Create a PHP file where you want TinyFileManager to be loaded:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

require __DIR__ . '/vendor/prasathmani/tinyfilemanager/tinyfilemanager.php';
```

Copy the config.php file from the repo next to the newly created file and update your settings from there.
