### ISSUE TITLE
how change directory

### ISSUE THREAD

**Issue by afsatechnical** [prasathmani/tinyfilemanager#129]
i want to use another folder not root directory

**Comment by simon511000** [comment]
You can use [KodExplorer](https://github.com/kalcaddle/KodExplorer) as an alternative

**Comment by prasathmani** [comment]
change the path config, 
```
$root_path = $_SERVER['DOCUMENT_ROOT']."my-folder/hello-world";

$root_url = 'my-folder/hello-world';
```

**Comment by andrewlytvyn** [comment]
Can i use C:/somedirectory? Not seever root directory

**Comment by prasathmani** [comment]
yes, you can use, it will work, but some feature will not work if folder is outside web root.
