### ISSUE TITLE
How to make a different directory for a specific user?

### ISSUE THREAD

**Issue by znaczki654** [prasathmani/tinyfilemanager#130]
![obraz](https://user-images.githubusercontent.com/27486533/53117345-fbced900-354a-11e9-83b9-e42b30f9111b.png)
This doesn't help, it says that it couldn't find the directory. Even letting it be empty or writing "root" doesn't change your position into root.

**Comment by anasmoiz** [comment]
The directory path you have set seems to be incorrect  it should be the absolute path for the files in the server like this 

```
$directories_users = array(
'admin' => '/var/www/html/public_html/',
'user' => '/var/www/html/public_html/wp-content/themes/twentynineteen/'
);
```
