### ISSUE TITLE
RegEx error | function template

### ISSUE THREAD

**Issue by TigersWay** [prasathmani/tinyfilemanager#134]
With the same old webhosters as the previous issue, I get:
`Parse error: syntax error, unexpected '^', expecting ']' in ......tinyfilemanager.php on line 3137`

After checking the culprit is in `re=/<%([^%>]+)?%>/g`. the % sign is trouble!
I changed it to `re=/<\%([^\%>]+)?\%>/g` and it "seems" to be working... An old javascript trick?

I'm not an regexp expert so not exactly sure about the test(s) I should do to confirm.

**Comment by prasathmani** [comment]
Thank you for your information, We're not supporting older versions of IE.

**Comment by TigersWay** [comment]
The trouble is that it was not any IE!  Tested with Firefox an chrome, latest version!

**Comment by prasathmani** [comment]
Oh, anyway, we're using ES6, so older version it will break.

**Comment by TigersWay** [comment]
ES6 on the server - which is old I have to admit - or on the client?

**Comment by prasathmani** [comment]
Client side

**Comment by TigersWay** [comment]
Yes,  and as i wrote earlier i tested with latest firefox and Chrome.

**Comment by prasathmani** [comment]
Added your suggestion
