### ISSUE TITLE
Issue with Folder Direct Link

### ISSUE THREAD

**Issue by DC8888** [prasathmani/tinyfilemanager#136]
When clicking on the **Direct Link** icon of the audio folder for instance https://tinyfilemanager.eu-gb.mybluemix.net/Demo/Audio/ returns a 404 page instead of listing the contents like here https://tinyfilemanager.eu-gb.mybluemix.net/Demo/index.php?p=Audio (accessed by clicking on the **Folder** link)

I like the former url as it is cleaner, and makes it easier to share.

Any ideas how to get the above to work with the clean url?

**Comment by prasathmani** [comment]
For direct link behavior is based on server configuration, tinyfilemanager does not have the control of direct url.
