### ISSUE TITLE
IE11 aborts upload after 30s

### ISSUE THREAD

**Issue by crispyduck00** [prasathmani/tinyfilemanager#137]
IE11 aborts the ajax file upload always after 30s.

Trying to analyze this I found out that IE also does not like following syntax:
```
946                     xhr.ontimeout = (() => { 
947                         alert('Error: Server Timeout'); 
948                     }); 
```

Researching for the upload issue with IE11 I came across a post which mentioned that it helps to add a empty function for in progress. So I changed the code as followed, which does no more throw a syntax error and also solves the IE file upload:

```
946                     }).on("progress", function () {
947                     }).on("timeout", function () {
948                        alert('Error: Server Timeout');
```

As I am no developer, I have no idea if I am doing it correct, but this seems to fix the Problems with IE and does also not lead to problems with other browsers.

regards,
crispyduck

**Comment by prasathmani** [comment]
Fixed

**Comment by crispyduck00** [comment]
Perfect Thanks!
