### ISSUE TITLE
prevent overwriting if uploaded file already exists

### ISSUE THREAD

**Issue by crispyduck00** [prasathmani/tinyfilemanager#138]
When a file is uploaded which name already exists, the existing file is overwritten without any warning.

To prevent overwriting existing files a (n) can be added to the filename of the newly uplodad file. Where n is a ongoing number starting with 0.

So for example if "file.zip" exists already in the upload path, rename the newly uploaded "file.zip" to "file (0).zip". If again the same filename is uploaded, rename it to "file (1).zip and so on.

This could be easylie archifed by adding following code bevore the "move_upload_file()" function:

```
     if(file_exists ($fullPath)) {
          $newPath = preg_replace('/\\.[^.\\s]{3,4}$/', '', $fullPath) . ' (0).' . $ext;    	
          $n = 1;
          while(file_exists ($newPath)) {
                $newPath = preg_replace('/\\.[^.\\s]{3,4}$/', '', $fullPath) . ' (' . $n . ').' . $ext;
                $n++;
          }
          $fullPath = $newPath;
    }
```

regards,
crispyduck

**Comment by prasathmani** [comment]
@crispyduck00 , added your suggestion. check with latest.

**Comment by crispyduck00** [comment]
@prasathmani , great solution simply adding the date! 
Maybe $datetime_format without dot and spaces can be used for it.
What happens if the filename length exceeds the filesystem limit?  

Maybe there should be a configurable filename limit for uploads:
[](https://stackoverflow.com/questions/49524701/dropzone-js-check-filename-length-with-accept)

Thanks!

**Comment by hedwiggggg** [comment]
It would be nice, if this feature is configurable; So we can turn it off and it actually overwrites the files.
