### ISSUE TITLE
Not Working on Laravel

### ISSUE THREAD

**Issue by mdrathik** [prasathmani/tinyfilemanager#139]
I tried so much in **laravel** but **Error: Cannot load configuration** but same code working in row php. Please can anyone help me

**Comment by prasathmani** [comment]
Remove or disable the config and then try.
![image](https://user-images.githubusercontent.com/11345598/54256595-8a4edd00-4582-11e9-8ef5-47b5dfdded78.png)

**Comment by mdrathik** [comment]
Got error, i think its redirect to another url after login
![image](https://user-images.githubusercontent.com/15226624/54259156-fd5e5080-458e-11e9-90e9-56bcac8c3a25.png)

**Comment by prasathmani** [comment]
Tinyfilemanager has self redirection based on folder/file selected, also after login. better try as iframe
