### ISSUE TITLE
Duplicate file with "copy" not working

### ISSUE THREAD

**Issue by VincentVandalon** [prasathmani/tinyfilemanager#142]
It is currently not possible to duplicate a file: it is possible to copy a file to a new directory but an error is thrown if the file is copied to the same directory. There is no option for copying into the same directory with a new/modified file name.

By the way, thank you very much for creating this nice and convenient tool!

**Comment by prasathmani** [comment]
Copy to same path is not allowed, because you're already there, if you want to create a backup of the file, use backup option in the edit.

**Comment by VincentVandalon** [comment]
I implemented some code to also support duplicating a file (quite inline with the current approach of copying a file). See also pull request "Added duplicate functionality" #143

**Comment by prasathmani** [comment]
@VincentVandalon thank you for your contribution, let me check.

**Comment by johnwmail** [comment]
Hi, why need to new duplicate button, instead of merge to copy?
Thanks.

**Comment by VincentVandalon** [comment]
Merging with copy requires a more extensive rewrite of the code (the current GUI isn't very suitable for a combined copy/duplicate). It would even be nicer, but I did not have the time to do it that way.

**Comment by johnwmail** [comment]
Hi, I mean like this.

--- tinyfilemanager.php.orig	Thu Mar 21 15:15:27 2019
+++ tinyfilemanager.php	Thu Mar 21 15:18:42 2019
@@ -496,9 +496,16 @@
             }
         }
     } else {
-        fm_set_msg('Paths must be not equal', 'alert');
+        $msg_from = trim(FM_PATH . '/' . basename($from), '/');
+        $fn_parts = pathinfo($from);
+        $ext = $fn_parts['extension'] ? '.' . $fn_parts['extension'] : '';
+        $fn_duplicate = $fn_parts['dirname'] . '/' . $fn_parts['filename'] . '_' . date('ymdHis') . $ext;
+        if (fm_rcopy($from, $fn_duplicate, False)) {
+            fm_set_msg(sprintf('Copyied from <b>%s</b> to <b>%s</b>', fm_enc($copy), fm_enc($fn_duplicate)));
+        } else {
+            fm_set_msg(sprintf('Error while copying from <b>%s</b> to <b>%s</b>', fm_enc($copy), fm_enc($fn_duplicate)), 'error');
+        }
     }
-    fm_redirect(FM_SELF_URL . '?p=' . urlencode(FM_PATH));
 }
 
 // Mass copy files/ folders

**Comment by VincentVandalon** [comment]
Now I understand what you mean, that might work. I will play around and update the pull request asap

**Comment by VincentVandalon** [comment]
I have updated the pull request to now include the merged functionality.
