### ISSUE TITLE
Setting FM_ROOT_PATH breaks image/video previews

### ISSUE THREAD

**Issue by alessandrofrancesconi** [prasathmani/tinyfilemanager#144]
If you set FM_ROOT_PATH to a (valid) location, every image or video preview in the File Manager gives "404 - Not Found":

![immagine](https://user-images.githubusercontent.com/1595223/54640283-b0e3ab00-4a8f-11e9-948f-d8d9e058d56c.png)

Also the "Open" link returns 404.
Instead, "Download" link works without problems.

**Comment by prasathmani** [comment]
Based on `$root_path`  change and need to change the `$root_url` accordingly .
i.e:
```
$root_path = '/var/www/html/temp-folder';
$root_url = 'temp-folder'
```

**Comment by alessandrofrancesconi** [comment]
@prasathmani , so a fix is needed or it is something I have to do in my local installation?

**Comment by prasathmani** [comment]
@alessandrofrancesconi  you need to configure in your local installation
