### ISSUE TITLE
Provide "previous" and "next" to navigate between previews

### ISSUE THREAD

**Issue by alessandrofrancesconi** [prasathmani/tinyfilemanager#145]
Imagine a folder containing media files. It would be extremely convenient if you provide "previous" and "next" buttons so I can go back and forth while in the "preview" window. 
A sort of slideshow like Windows Photo Viewer does:

![immagine](https://user-images.githubusercontent.com/1595223/54643215-aa0c6680-4a96-11e9-9d7d-f89b6dd06b70.png)

**Comment by prasathmani** [comment]
Added Quick Preview option to view all kind of files with prev/next.
