### ISSUE TITLE
Downloading 128Mb zip file stops at 52Mb

### ISSUE THREAD

**Issue by mindfragment** [prasathmani/tinyfilemanager#149]
TFM v2.3.3 
Created a zip through TFM, tried downloading it but it always stopped halfway (52Mb), firefox said "download complete", couldn't open the zip (error). Tried through filezilla the zip downloaded and was error free.
PS: just tried again it with the same 128Mb zip, it stopped at 98Mb
and with a 533Mb zip and also stopped at 98Mb

**Comment by mindfragment** [comment]
just tried again it stopped at 98Mb

**Comment by prasathmani** [comment]
PHP has limits on how long a script can run, and how much memory it can use. It's possible that the script is timing out before it has completed, or is using up too much memory by reading in the large file.

Try tweaking the `max_execution_time` and `memory_limit` variables in php.ini. If you don't have access to php.ini, try the `set_time_limit` and/or `ini_set` functions.

**Comment by mindfragment** [comment]
Thanks prasathmani. Unfortunately I can't change these parameters.

**Comment by alecos71** [comment]
```
@set_time_limit(0);
  @ini_set('max_execution_time', 0);
```
two lines written at top of script should solve the issue...

**Comment by mindfragment** [comment]
Thanks prasathmani. You mean at the top of the .php file ?
Even if my internet provider (on shared linux) says it is set at 60 and cannot be changed unless I move to a cpanel account ?

**Comment by VaelVictus** [comment]
> Even if my internet provider (on shared linux) says it is set at 60 and cannot be changed unless I move to a cpanel account ?
Then no, they are likely in control of what you can do. You may find it more affordable to just run your own unmanaged server!
