### ISSUE TITLE
Correct permission to upload and overwrite php files

### ISSUE THREAD

**Issue by kabeza** [prasathmani/tinyfilemanager#153]
Hi

Which would be the correct permission and folder ownership so the user can upload and overwrite php files? The user actually logins to TinyFilemanager and can upload/overwrite css, js, html, etc. file types, but cannot delete/overwrite php files.

Folder where TinyFilemanager is located has 777 permission now. I know it is very dangerous and would like to correct this without affecting user uploading/overwriting folder/files. 
Also, my linux user is added to www-data group but am having that problem with php files

Thanks a lot and congrats for this lifesaving tool

**Comment by prasathmani** [comment]
https://serverfault.com/questions/962790/php-script-and-correct-permissions-for-user-to-change-everything
