### ISSUE TITLE
Error in the console

### ISSUE THREAD

**Issue by AndreFabris** [prasathmani/tinyfilemanager#161]
Hi I got the following reported in the console:
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data tinyfilemanager.php:501:71
fm_get_config http://209.97.131.216/myadmin/resources/views/myAdmin/tinyfilemanager.php?p=site/wp-content/uploads:501
    <anonymous> http://209.97.131.216/myadmin/resources/views/myAdmin/tinyfilemanager.php?p=site/wp-content/uploads:583
jQuery 2
j
k
```
Also this
```
jQuery.Deferred exception: JSON.parse: unexpected character at line 1 column 1 of the JSON data fm_get_config@http://209.97.131.216/myadmin/resources/views/myAdmin/tinyfilemanager.php?p=site%2Fwp-content%2Fuploads&view=2019.ZIP:385:71
@http://209.97.131.216/myadmin/resources/views/myAdmin/tinyfilemanager.php?p=site%2Fwp-content%2Fuploads&view=2019.ZIP:467:9
j@https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:29999
g/</k<@https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:30313
```
Any ideas?

**Comment by prasathmani** [comment]
I think you will get this kind of error on uploading through URL. try normal upload.

**Comment by AndreFabris** [comment]
I am getting this error as soon as I open the app. Line which throws it:
`function fm_get_config(){ if(!!window.name){ window.config = JSON.parse(window.name); } else { $.getJSON(window.curi).done(function(c) { if(!!c) { window.name = JSON.stringify(c), window.config = c; } }); }}`
App is running in the iframe btw

**Comment by prasathmani** [comment]
on first time it load config from `https://tinyfilemanager.github.io/config.json`, check the config is loading or not.

**Comment by prasathmani** [comment]
check with latest release, hope it working with latest
