### ISSUE TITLE
Fixed Errors in German Translation

### ISSUE THREAD

**Issue by marcorensch** [prasathmani/tinyfilemanager#163]
I've updated the German Language Translation (there where some errors):
{
      "name": "Deutsch",
      "code": "de",
      "translation": {
        "AppName": "Tiny File Manager",
        "AppTitle": "Datei Manager",
        "Login": "Einloggen",
        "Username": "Benutzername",
        "Password": "Passwort",
        "Logout": "Ausloggen",
        "Move": "Verschieben",
        "Copy": "Kopieren",
        "Save": "Speichern",
        "SelectAll": "Alles auswählen",
        "UnSelectAll": "Alles abwählen",
        "File": "Datei",
        "Back": "Zurück",
        "Size": "Größe",
        "Perms": "Berechtigungen",
        "Modified": "Geändert",
        "Owner": "Eigentümer",
        "Search": "Suchen",
        "NewItem": "Neues Element",
        "Folder": "Ordner",
        "Delete": "Löschen",
        "Rename": "Umbenennen",
        "CopyTo": "Kopieren nach",
        "DirectLink": "Direktlink",
        "UploadingFiles": "Datei hochladen",
        "ChangePermissions": "Berechtigungen ändern",
        "Copying": "Kopieren",
        "CreateNewItem": "Neue Datei erstellen",
        "Name": "Name",
        "AdvancedEditor": "Erweiterter Editor",
        "RememberMe": "Eingeloggt bleiben",
        "Actions": "Aktionen",
        "Upload": "Hochladen",
        "Cancel": "Abbrechen",
        "InvertSelection": "Auswahl umkehren",
        "DestinationFolder": "Zielordner",
        "ItemType": "Dateityp",
        "ItemName": "Dateiname",
        "CreateNow": "Jetzt erstellen",
        "Download": "Download",
        "Open": "Öffnen",
        "UnZip": "Entpacken",
        "UnZipToFolder": "Entpacken im Ordner",
        "Edit": "Bearbeiten",
        "NormalEditor": "Standard Editor",
        "BackUp": "Backup",
        "SourceFolder": "Quellordner",
        "Files": "Dateien",
        "Change": "Ändern",
        "Settings": "Einstellungen",
        "Language": "Sprache"
      }
    },

kind regards

**Comment by prasathmani** [comment]
Added
