### ISSUE TITLE
Problem with Direct Link

### ISSUE THREAD

**Issue by Whisper40** [prasathmani/tinyfilemanager#165]
Hi, the direct link is not working on my side with an user connected with his home directory.
User => /home/User/files
When User click on direct link, he has a link like that : 
/filemanager/home/User/files/file.mkv with a 404 Not Found Nginx error.

Do you have an idea on what's the reason of that ?
Thanks !

---

I use your last master push ( i can delete,zip.....)

**Comment by prasathmani** [comment]
@Whisper40 , try with absolute path, i.e `/var/www/filemanager/home/user/file/`

**Comment by Whisper40** [comment]
Thanks for this response, i will take a look later, do you allow special request (paid) in private for an embedding add ? If yes, give me your email.
(in order to use my css into yours without problem.. )

**Comment by prasathmani** [comment]
reach out ccpprogrammers[at]gmail.com

**Comment by Whisper40** [comment]
I asked prasathmani to develop his filemanager in my interface in order to make the filemanager even more beautiful.
I also asked if it was possible to create a function that allows documents to be shared without a password.

We defined everything in our first emails, I provided him with my pages (navbar+css) and he then started working on them, he then showed me the results at each step, proposed video demonstrations, and he didn't hesitate to ask questions to make sure we were talking about the same thing.

In the end, the work was more complicated because I didn't use the filemanager in the web server but in the /home/.
This has created many syntax problems with urls, in short, many complex problems to solve.
He then decided to go through teamviewer to see what the problems were.

In the end, this developer is very serious, and completes the development task completely until his work is functional on the client side.
Regarding deadlines, I had asked that the work be completed at D+7, the first results arrived at D+1 and the work was fully completed at D+3

I can only recommend his work!

**Comment by iarifbd** [comment]
`<?php 
// Determine the base URL, checking if the connection is secure (HTTPS) or not (HTTP)
$base_url = ((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == "on") ? "https" : "http");
$base_url .= "://". @$_SERVER['HTTP_HOST'];  // Append the server's host (domain) to the base URL
$base_url .= str_replace(basename($_SERVER['SCRIPT_NAME']), "", $_SERVER['SCRIPT_NAME']);  // Append the script path without the filename

// Set the base path for the user's directory (for example, a server's root path)
$base_path = 'https://base_url/';

// Get the full path of the logged-in user (from session and directories array)
$full_path = $directories_users[$_SESSION[FM_SESSION_ID]['logged']];

// Calculate the relative path by removing the base path from the full path
$relative_path = substr($full_path, strlen($base_path));
?>

<a title="<?php echo lng('DirectLink') ?>" 
   href="<?php echo  $base_url."/".$relative_path."/".$f; ?>" 
   target="_blank" 
   onclick="copyAndOpen(event, this)">
    <i class="fa fa-link"></i> 
</a>

<script>
// JavaScript function to copy the URL to clipboard and open it in a new tab
function copyAndOpen(event, element) {
    // Prevent the default action of the link (navigating to the URL)
    event.preventDefault();

    // Get the URL from the href attribute of the clicked link
    const url = element.href;

    // Copy the URL to clipboard using the Clipboard API
    navigator.clipboard.writeText(url).then(function() {
        console.log('URL copied to clipboard');  // Log success message to the console
    }).catch(function(err) {
        console.error('Failed to copy: ', err);  // Log error if copying failed
    });

    // Open the URL in a new browser tab
    window.open(url, '_blank');
}
</script>
`
