### ISSUE TITLE
Add Microsoft Office online view option

### ISSUE THREAD

**Issue by cc5771027** [prasathmani/tinyfilemanager#169]
[Here](https://products.office.com/en/office-online/view-office-documents-online) can creat online view url
```
https://view.officeapps.live.com/op/view.aspx?src=<file>
```

**Comment by yehudaei** [comment]
What's wrong with Google?

**Comment by cc5771027** [comment]
> What's wrong with Google?

Microsoft Office has better compatibility
and
I live in China

**Comment by prasathmani** [comment]
I'll add both google and Microsoft office in config, so that user can select.
I'll try to add this feature in next release

**Comment by prasathmani** [comment]
@cc5771027 , Microsoft office viewer added.

**Comment by cc5771027** [comment]
> @cc5771027 , Microsoft office viewer added.

thk
