### ISSUE TITLE
IP whitelisting and/or blacklisting

### ISSUE THREAD

**Issue by Kevin-at-Navigram** [prasathmani/tinyfilemanager#171]
Simple idea really, how about support for basic IP whitelisting and/or blacklisting?

My proposal would be simple:

- User gets to define a whitelist
- User gets to define a blacklist
- User gets to define an OFF/AND/OR ruleset
-- OFF => Don't check connection IP, defaults to OFF
-- AND => Connection must be on the whitelist, and not on the blacklist
-- OR => Connection must be on the whitelist, or not on the blacklist

We internally use TFM, and I'll likely be able to get some time to develop this and to put it back upstream. So that's why I'm asking, care to have this functionality added?

**Comment by prasathmani** [comment]
@Kevin-at-Navigram, really great input, I'll add this in feature release
