### ISSUE TITLE
PHP Warning:  count()

### ISSUE THREAD

**Issue by Kevin-at-Navigram** [prasathmani/tinyfilemanager#173]
**Platform**
Ubuntu 18.04 LTS
PHP: 7

**message**
> PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /.../tinyfilemanager.php on line 629

**Comment by prasathmani** [comment]
@Kevin-at-Navigram, When did you getting this warning

**Comment by Kevin-at-Navigram** [comment]
I was using the preview functionality to look at a text file.
MIME-type: text/plain
Charset: utf-8

**Comment by prasathmani** [comment]
quick fix done, check now @Kevin-at-Navigram

**Comment by Kevin-at-Navigram** [comment]
Confirmed. Warning gone. 

Next question, does this break some functionality?

**Comment by prasathmani** [comment]
No, definitely not.
