### ISSUE TITLE
Document type detection

### ISSUE THREAD

**Issue by nk932714** [prasathmani/tinyfilemanager#183]
It would be awesome if file manager automatically recognize the document type.
![image](https://user-images.githubusercontent.com/29853208/58627832-cb3ece00-82f5-11e9-994d-bf2b0c5930a5.png)

Example :- if we are editing ```php``` file then document type should automatically pick php template. But it is picking only JavaScript. we have to manually change this to php. 

However is there any way to set default language to php from javaScript. because I'm working only on Php files. So every time after i click save i have to choose php template. its annoying.

**Comment by prasathmani** [comment]
![image](https://user-images.githubusercontent.com/11345598/58630796-19f06600-82fe-11e9-9dea-16349a07959d.png)
e.g.  `editor.getSession().setMode( {path:"ace/mode/php", inline:true} );`
note :  dropdown selection will not change

**Comment by nk932714** [comment]
Thanks buddy for your quick reply. It helps. 
But the problem is that now I'm unable to switch to JavaScript. Anyways i don't need JavaScript. 
eg: I'm editing ```http://xxxx.xxx/tinyfilemanager.php?p=&edit=tinyfilemanager.php```  here editing **edit=tinyfilemanager.php** then it should choose mode automatically. i.e php in this case. and if i'm editing  ```http://xxxx.xxx/tinyfilemanager.php?p=&edit=translation.json``` then it should choose mode to Json. 

I believe a simple this code would be ok for this
```
<?php if (isset($_GET['edit'])) { $filename_= $_GET["edit"]; $ext_ = pathinfo($filename_, PATHINFO_EXTENSION);	}     else { $ext_= "javascript";      } ?>

editor.getSession().setMode( {path:"ace/mode/<?php echo $ext_; ?>", inline:true} ); ```

**Comment by prasathmani** [comment]
In next release I will add this feature

**Comment by nk932714** [comment]
Thanks @prasathmani

**Comment by prasathmani** [comment]
@nk932714 , your suggestion added.

**Comment by nk932714** [comment]
Thanks a  lot @prasathmani
