### ISSUE TITLE
view file is insecure

### ISSUE THREAD

**Issue by satyr-software** [prasathmani/tinyfilemanager#187]
File exclusion mask is applied on listing files, but not on views:
Short test:
 * View path (let's say index.php)
 * Open file (opens fine)
 * Add to GLOBALS['exclude_items'];
 * Reload : (File still displayed)
 * Back: View path (file dissapears)

Expected result:
 * Reload should show "FIle Not Found" (excluded)

Fix:
 if ($file == '' || !is_file($path . '/' . $file) **|| in_array($file, $GLOBALS['exclude_items'])**) {

Just before:
 fm_set_msg('File not found', 'error');

**Comment by prasathmani** [comment]
@satyr-software added your suggestion.
