### ISSUE TITLE
Add shorten URL on share

### ISSUE THREAD

**Issue by khangninh** [prasathmani/tinyfilemanager#189]
Can you add feature shorten URL on share
It is so helpfull

**Comment by ryancco** [comment]
Using a third-party service, or some kind of temporary data store within the filesystem to keep track of short URLs? I guess this is  a two part question - what would the author of this issue like to see, ideally, and ultimately what will the author of the project allow?

/cc @prasathmani @khangninh

**Comment by prasathmani** [comment]
Thank you suggesting, as of now not possible to add this feature, This application developed to help for managing files in the server.
