### ISSUE TITLE
preview button behaviour

### ISSUE THREAD

**Issue by nk932714** [prasathmani/tinyfilemanager#190]
its strange. When i click on preview first time it displays the code in color format. But when i click close and click to preview button again it shows the code in Black color only.

( when clicked on preview first time)

![image](https://user-images.githubusercontent.com/29853208/60421857-4ef71d80-9c08-11e9-80b8-3d1934f132bb.png)

( When opening the preview 2nd time )

 
![image](https://user-images.githubusercontent.com/29853208/60421881-5a4a4900-9c08-11e9-910f-a188b50f1f8b.png)

**Comment by EV-soft** [comment]
Try to change this line:

> if(online_viewer && online_viewer !== 'false' && in_array($ext, fm_get_onlineViewer_exts())){

To:

> if($online_viewer && $online_viewer !== 'false' && in_array($ext, fm_get_onlineViewer_exts())){

(missing: $ before: online_viewer )

**Comment by nk932714** [comment]
Thanks for your reply @EV-soft  but still if I'm closing a preview more then 3-4 times  its not working
