### ISSUE TITLE
Cannot edit aspx File

### ISSUE THREAD

**Issue by clclgithub** [prasathmani/tinyfilemanager#200]
Install on Windows 2016/ IIS 1.0, when I try edit aspx file, it only show Download, Open and Back option button. It's cannot show Edit or Advance Editor option.

It can edit web.config file without any problem.

Any hints to fix it?

**Comment by prasathmani** [comment]
fixed, try with latest.

**Comment by clclgithub** [comment]
Confirm issue fixed. Thanks!
