### ISSUE TITLE
Backup File return false

### ISSUE THREAD

**Issue by clclgithub** [prasathmani/tinyfilemanager#201]
On Edit File screen, click the Backup button, system only return "false" on screen.

File Manger:  2.3.8
OS: Windows 2016/ IIS 10
PHP Version 7.3.7

**Comment by EV-soft** [comment]
Browser ?
In Firevox 68.0.1 (64-bit) is javascript blocked, and also return "false"
In Chrome it works!

**Comment by clclgithub** [comment]
OS: Windows 10
Testing Browser:
Firefox 68.0.1 (64bit), testing by create new profile, always return "false"
Chrome 76.0.3809.87 (Official Build) (64-bit), success backup.

**Comment by si458** [comment]
Hi,
this still happens a year later
Mac Firefox 76.0.1 just shows 'return' on white screen
Mac Chrome 81 works as expected

**Comment by prasathmani** [comment]
fixed
