### ISSUE TITLE
DEMO not working

### ISSUE THREAD

**Issue by EV-soft** [prasathmani/tinyfilemanager#203]
When clicking the link:
https://tinyfilemanager.github.io/demo/
it shows:
404 Not Found: Requested route ('tinyfilemanager.eu-gb.mybluemix.net') does not exist.

**Comment by prasathmani** [comment]
server restarted

**Comment by ivangretsky** [comment]
Please, do your magic once again, @prasathmani. The demo is broken.

**Comment by prasathmani** [comment]
@ivangretsky thanks again
