### ISSUE TITLE
File Upload: The resource you are looking for has been removed

### ISSUE THREAD

**Issue by clclgithub** [prasathmani/tinyfilemanager#204]
Try to upload PDF file size 30M, system return following error:

The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

fm.php updated following setting:

define('MAX_UPLOAD_SIZE', '51200');
$allowed_extensions = 'aspx,html,pdf,gif,png,jpg'; 

PHP ini update following setting:

upload_max_filesize = 50M
post_max_size = 50M

File Manger: 2.3.8
Cloud: Azure WebApp
OS: Windows 2016/ IIS 10
PHP Version 7.3.7

Any hints?

**Comment by regmibijay** [comment]
What is your `maxAllowedContentLength` in `web.config` ? Default limit for IIS used to be 30MB, so I think that is where your issue is?

**Comment by clclgithub** [comment]
By updating the web.config (see below), I can now upload file around 50MB now.  

However, I cannot upload more than 50MB, even I increase the size limit to 200M after change both PHP setting, web.config file. 

System does show upload success, but the file cannot found on the upload folder.  Any method to debug?

<configuration>
   <system.webServer>
      <security>
         <requestFiltering>
            <requestLimits maxAllowedContentLength="<valueInBytes>"/>
         </requestFiltering>
      </security>
   </system.webServer>
</configuration>

**Comment by regmibijay** [comment]
> I cannot upload more than 50MB, even I increase the size limit to 200M after change both PHP setting, web.config file.

Are you uploading files that have extensions you have specified?
Please make sure you have proper permissions/ space to store the file. I can not reproduce same error. Would you be kind enough to provide error log, with some error codes etc.? This is most probably not an issue of FM.

**Comment by clclgithub** [comment]
You are correct, Seems file extension issue:

I upload 100MB pdf, system show upload success but cannot find the file afterward.
I rename the pdf to jpg extension.
System show upload success and find the jpg file on the server. 

No PHP or system error logged.

** I can success upload 40MB pdf extension file.

**Comment by regmibijay** [comment]
If you dont have any logs, its hard to tell.

Maybe check MIME-Types under app/site pool in your IIS? I am sorry  I am out of ideas at this point.
