### ISSUE TITLE
Bug Hide Perms/Owner columns

### ISSUE THREAD

**Issue by weado** [prasathmani/tinyfilemanager#205]
`Debian Buster
PHP 7`

When I put on true the "Hide Perms/Owner columns" button, the colums don't hide.

Thank you this file manager, it's very nice to work with it.

**Comment by weado** [comment]
Works fine when you put 'true' in the first line of php file. My www-data user is owner of all file in the folder.

**Comment by prasathmani** [comment]
@weado  check your file write permission, tinyfilemanager required write permission to update the settings

**Comment by EV-soft** [comment]
Another possible cause:
```
  function save()
    {
        global $root_path;  // default: $root_path = $_SERVER['DOCUMENT_ROOT'];
        $fm_file = $root_path.$_SERVER["PHP_SELF"];
        $var_name = '$CONFIG';
        ....
```
If user has edited $root_path so it is not $_SERVER['DOCUMENT_ROOT']  sawing will fail
A better solution:
```
  function save()
    {
        $fm_file = __FILE__;   // Independent of user set root_path
        $var_name = '$CONFIG';
        ....
```

**Comment by prasathmani** [comment]
hope it works for you
