### ISSUE TITLE
add translation support for a few more words

### ISSUE THREAD

**Issue by Roni-Neto** [prasathmani/tinyfilemanager#210]
lng(' ')
support translation to these words below

> Folder is empty

> successful save!

> File Saved Successfully

> Paths must be not equal

> Delete selected files and folders?

> Create archive?

> Change Permission

**Comment by Roni-Neto** [comment]
> Delete selected files and folders?

**Comment by Roni-Neto** [comment]
> `Folder <b>%s</b> deleted`

> `File <b>%s</b> deleted`

> `Folder <b>%s</b> not deleted`

> `File <b>%s</b> not deleted`

**Comment by EV-soft** [comment]
See my comments and my ZIP file in # 211
