### ISSUE TITLE
 when saving an edit show a warning ( alert )

### ISSUE THREAD

**Issue by Roni-Neto** [prasathmani/tinyfilemanager#213]
put warning to know if the file was saved, because in the last update after saving is staying on the same page

**Comment by nk932714** [comment]
instead of alert. Snackbar will be a good option 
[https://www.w3schools.com/howto/howto_js_snackbar.asp](https://www.w3schools.com/howto/howto_js_snackbar.asp)

**Comment by prasathmani** [comment]
Added toast message
