### ISSUE TITLE
Suggestions for the next version

### ISSUE THREAD

**Issue by EV-soft** [prasathmani/tinyfilemanager#219]
In this file: [TFM-v2.3.8-ev.zip](https://github.com/prasathmani/tinyfilemanager/files/3582379/TFM-v2.3.8-ev.zip), I have made the following improvements:
```
    Upgraded icons: font-awesome/4.7.0 to font-awesome/5.9.0
    Set color on file-icons in a new individual way
    Added column 'Ext' so you can sort on file-extension
    Corrected count folders: fm_get_directorysize()
    Moved link to parent folder to <thead> so it stays at top when sorting table
    Added several translate: lng('x...')
    Added fm_set_msg() to the language translate system like lng()
    Generate/update support file TFM_2Google.txt for easy first time translate
    Renamed: translation.json to .FM_translation.json (hidden supportfile)
    Added warning: "This page needs JavaScript..."
    CSS for column output tblcol,fsize (align, width)
    Separated buttons [fileSelecting] and [fileHandling] with text: "With selected:"
    Show fileTime and more, for files in ZIP/TAR-archives
    View current filename in editor after bread-crumb
    Set Color on actions buttons
    Added left-Panel with folder structure (only visibly when expertMode= true)
    New button - toggle expert mode: Show/hide 3 columns, 
                 Color on actions buttons on/off, and show folder structure 
```

**Comment by EV-soft** [comment]
To upgrade bootstrap to newest do
```
SEARCH:  maxcdn.bootstrapcdn.com/bootstrap/4.0.0
REPLACE: stackpath.bootstrapcdn.com/bootstrap/4.3.1
```

**Comment by osoibol** [comment]
Hi, is it possible to add a user-based exclude list of files?
i/e if I am admin I can still see "index.php" or "filemanager.php" but if i log in as "guest" or "user2" I can choose to hide those files from them?

**Comment by osoibol** [comment]
another cool option could be to allow multiple folders for different users, so we can have a shared folder between different users for example, or if different users need to have access to a particular folder it could be possible to add permission to that particular folder.

**Comment by EV-soft** [comment]
In the last 10 days, I have added further enhancements, that you can see on this [link](https://www.sky-box.dk/tinyFM/TFM-v2.3.8c.php) and you can download source files gathered in the ZIP file: TFM-v2.3.8c.zip

**Comment by prasathmani** [comment]
Thank you suggesting, will consider  in upcoming releases
