### ISSUE TITLE
how to ask user to create password when he visit the file manger for the first time

### ISSUE THREAD

**Issue by codesiddhant** [prasathmani/tinyfilemanager#225]
I wanted to know , how to add a password creation function to this file manager.

**Comment by prasathmani** [comment]
Password creation option is already available in file manager under "Help" > " Generate new password hash"

**Comment by codesiddhant** [comment]
actually I wanted to add a signup form before login page appears,
is it possible for now ?

**Comment by prasathmani** [comment]
No
