### ISSUE TITLE
can it work with Mysql user/password authorization? 

### ISSUE THREAD

**Issue by zhaoyangted** [prasathmani/tinyfilemanager#226]
Can user auth work with Mysql database, and how can I configure user directories respectively then?

**Comment by prasathmani** [comment]
File manager not supported login using database. You have to customise.

**Comment by zhaoyangted** [comment]
Thx! can embedded mode work with Bootstrap 3.3.7?

**Comment by prasathmani** [comment]
yes, https://tinyfilemanager.github.io/docs/#line5
