### ISSUE TITLE
Search functionality does not work for me

### ISSUE THREAD

**Issue by ambipur76** [prasathmani/tinyfilemanager#227]
I have seen that on the demo site works great, but unfortunately in my case nothing happens after beginning to write an existing filename. Does this functionality have a special package dependency or some extra configuration is needed?

**Comment by prasathmani** [comment]
No configuration required, search is developed using datatable js. Check your console , is there any JS issue?

**Comment by prasathmani** [comment]
hope it will work with latest version, but feel free to re-open a closed issue if needed.
