### ISSUE TITLE
how to disable the "You are logged in" text bar?

### ISSUE THREAD

**Issue by ambipur76** [prasathmani/tinyfilemanager#228]
Is it possible somehow to disable the text bar, which displays a text after successfull logon "You are logged in"? Thank's in advance!

**Comment by prasathmani** [comment]
remove line no: 248
`fm_set_msg('You are logged in');`

**Comment by ambipur76** [comment]
There are many rows in the code like fm_set_msg('Write something'). I would like to completely disable this message bar, not only disabling the 'You are logged in' message to be displayed in the message bar.
Is it possible to hide the message bar?

**Comment by prasathmani** [comment]
Comment the following line, you will not get any message
```
function fm_set_msg($msg, $status = 'ok')
{
   // $_SESSION[FM_SESSION_ID]['message'] = $msg;
   // $_SESSION[FM_SESSION_ID]['status']` = $status;
}
```

**Comment by ambipur76** [comment]
Yes, that has solved my question. Maybe it would be worth a configuration variable at the beginning of the code to enable / disable this bar. Function could than check this variable and act accordingly.
