### ISSUE TITLE
how to add context menu to the tinyfilebrowser

### ISSUE THREAD

**Issue by codesiddhant** [prasathmani/tinyfilemanager#230]
how one can add a custom context menu and disable and action buttons 
I also want gird view for the files and folder just like a cute file browser.
but its quite difficult to understand how tiny file browser renders the file list view to the browser.

I also wanted to play or open any video/document on the same page under a box using an iframe
from the context menu of the file.
![rjjj](https://user-images.githubusercontent.com/54833015/65595566-b415a180-dfb2-11e9-8828-84c91c02e3bf.png)

**Comment by prasathmani** [comment]
File manager not supporting context menu. You can  customize.

**Comment by EV-soft** [comment]
I'm trying to do what you suggest, but can only make it work on one post. Maybe you can fix my problem?
You can see my version here:
https://www.sky-box.dk/tinyFM/Context%20Menu/TFM-v2.3.8d.php?p=Context%20Menu
Try right-click on the row with file .FM_background.png (the first unsorted file)
You can view and edit all the required files in the folder "Context Menu"
