### ISSUE TITLE
please clarify in README.md that we need to get json plugin installed

### ISSUE THREAD

**Issue by CaiMiao** [prasathmani/tinyfilemanager#231]
My [repo which I installed php from](https://repo.ius.io) does not defaultly ship with json plugin, I must manually install it to make it works.
So if you can clarify not only json plugin but all plugins we must have, then newcomers would have less asspain.

**Comment by prasathmani** [comment]
I'm not getting what your asking

**Comment by CaiMiao** [comment]
Precompiled PHP binaries from https://repo.ius.io/ does not have the PHP JSON plugin shipped with (minimal installation), and in line 355 we called a function `json_decode()` which is from [JSON plugin](https://www.php.net/manual/en/book.json.php).
If we don't have the plugin installed, your php won't run.
