### ISSUE TITLE
File on uploading is not getting uploaded

### ISSUE THREAD

**Issue by ersaurabh101** [prasathmani/tinyfilemanager#233]
I am able directly login in my docs folder as i set the root path as -

`$root_path = $_SERVER['DOCUMENT_ROOT'].'/es'.'/docs';`

but when i am uploading file in folder named '44' [ image,txt ] it shows the uploading loader and the tick icon but the file is not uploaded. 

>Please note i am able to create a new folder but uploading is not working. Please find the attached screenshots
![2019-09-28_13h11_26](https://user-images.githubusercontent.com/50316624/65813330-87030200-e1f1-11e9-90eb-2b0c133d3b9d.png)
![2019-09-28_13h13_30](https://user-images.githubusercontent.com/50316624/65813346-d1847e80-e1f1-11e9-80c8-3a364631d119.png)

**Comment by prasathmani** [comment]
update the root path,
`
$root_url = 'es/docs';
`

**Comment by ersaurabh101** [comment]
> update the root path,
> `$root_url = 'es/docs';`
> and check if you have write permissions to upload the file

Done as guided, still files are not getting uploaded.
`$root_url = 'es/docs';`
0755 permission to folders and this php script

**Comment by prasathmani** [comment]
file is not uploading due to file tmp_name is empty, change the `upload_max_filesize` and check.

https://stackoverflow.com/questions/30358737/php-file-upload-error-tmp-name-is-empty

**Comment by quasarnew** [comment]
I have the same issue!
I checked the directory and the permissions (755) but still, it is not working.

**Comment by prasathmani** [comment]
change the `upload_max_filesize` in `php.ini`

**Comment by infernostudiosmtl** [comment]
see #314 for my solution - hope it helps
