### ISSUE TITLE
Please make upgrade easier

### ISSUE THREAD

**Issue by maertin** [prasathmani/tinyfilemanager#235]
When i update my file manager I have to copy the users. It would be easyer if users where in extern file(json) like the translation file

**Comment by TheFax** [comment]
Very similar to mine: #199

**Comment by csaggo** [comment]
all config should be outside the code so +1 from me

**Comment by prasathmani** [comment]
external configuration file available in latest version

**Comment by csaggo** [comment]
yeah just saw that :-) thanks alot, great improvement!
