### ISSUE TITLE
Preview not working using Xampp embedded in wordpress

### ISSUE THREAD

**Issue by OldHondaGeek** [prasathmani/tinyfilemanager#237]
Hi Great script works great I just need to figure out the file preview. I have set Google as default viewer however clicking on the preview button only shows "No preview available"

What am I doing incorrectly. I am logged into my gmail account.

Ps.
I also tried the microsoft setting same issue.

Thanks for writing a great script.

**Comment by prasathmani** [comment]
are you trying in localhost, docs preview is not supported in localhost.

**Comment by OldHondaGeek** [comment]
Hi yes that must be it.
I have been developing an internet site on xammp. Ill put it on a server.
Thankyou again for a great script.
