### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by KrisMerckx** [prasathmani/tinyfilemanager#24]
Hello

I would like to use tinyfilemanager, but I experience two main problems. I tried to use it on multiple domains but it's terribly slow. It took more than a minute before the filemanager was loaded. Besides, I changed $root_path but it doesn't seem to work. It still loaded $_SERVER['DOCUMENT_ROOT']

**Comment by prasathmani** [comment]
disable the file tree view feature and check.
` $show_tree_view=false`

#29

**Comment by plonknimbuzz** [comment]
thanks prasath
