### ISSUE TITLE
Questions - dark mode / disable everything / see only folders

### ISSUE THREAD

**Issue by DAngeloFrancesco** [prasathmani/tinyfilemanager#247]
Hello guys..
you created here something almost perfect but i want to ask some questions
1. Dark mode is ? if yes how
2. Disable everything - if you see the photo on this view page like in photo http://prntscr.com/pm17pg i colored the marked i only use.. is a way to disable everything else on this view mode? i dont want to edit/download/upload/clone/copy etc just for see and and delete folders. short story i want to delete the rest butons.
3. see only folders - im on a section with tinyfilemanager and i want a custom url or something like this where to see only folders
4. time of files - is any custom url to see only files oldest 40 minutes for example?

**Comment by DAngeloFrancesco** [comment]
hi i try to help to this tinyfilemanger how i can so i subcribe here https://patreon.com/ccpprogrammers maybe when you have a little time maybe can you guide me to fix some of my requests. thanks

**Comment by prasathmani** [comment]
I'm looking into it, I'll give you update on this weekend

**Comment by DAngeloFrancesco** [comment]
ok sir ty.
dark mode is optional if dont exist dont matter you dont need to create
but maybe you can help me with this
some custom url or a custom script i want on the section where i see files i want to see only folders + to see only folder 40 minutes older for example and to have only 2 buttons: select all and delete . (is something like a way to hiden buttons? what i like and what i dont like? )
btw good job of this tinyfilemanager. continue !

**Comment by EV-soft** [comment]
You can try this -
Create a CSS-rule:
```
.userstyle {
     display: none /* Used to hide user selected objects */
}
```  
Add class '_**userstyle**_'  to li-elements with buttons below file-table, as shown here:
```
<div class="row">
    <?php if (!FM_READONLY): ?>
    <div class="col-xs-12 col-sm-9">
        <ul class="list-inline footer-action">
            <li class="list-inline-item"> <a href="#/select-all" class="bt...
            <li class="list-inline-item userstyle"><a href="#/unselect-all...
            <li class="list-inline-item userstyle"><a href="#/invert-all" ...
            <small><?php echo lng('With selected'); // EV-soft ?>: </small...
            <li class="list-inline-item "><input type="submit" class="hidd...
                <a href="javascript:document.getElementById('a-delete').cl...
            <li class="list-inline-item userstyle"><input type="submit" cl...
                <a href="javascript:document.getElementById('a-zip').click...
            <li class="list-inline-item userstyle"><input type="submit" cl...
                <a href="javascript:document.getElementById('a-tar').click...
            <li class="list-inline-item userstyle"><input type="submit" cl...
                <a href="javascript:document.getElementById('a-copy').clic...
        </ul>
    </div>
    <div class="col-3 d-none d-sm-block"><a href="https://tinyfilemanager....
    <?php else: ?>
        <div class="col-12"><a href="https://tinyfilemanager.github.io" ta...
    <?php endif; ?>
</div>
```
And to hide buttons to the right in folder-rows:
```
  <td class="inline-actions" <?php if...
  <?php if (!FM_READONLY): ?>
          <a title="<?php echo lng('Delete...
          <a class="userstyle" title=...
          <a class="userstyle" title=...
  <?php endif; ?>
      <a class="userstyle" title="<?p...
  </td>
```
Hide rows with files:
`<tr class="userstyle" ...`

If you want to cancel the effect, simply comment on the rule:
```
.userstyle {
 /*    display: none /* Used to hide user selected objects */
}
```
time of files:
How about sort by filetime, by clicking on "Modified" above the time-column?

**Comment by prasathmani** [comment]
Attached customized filemanger,
 - Removed all actions as you mentioned
 - Now able to see files/folder older than 40 mins using following query string adding to URL.
   - View all folder and files modified 40 minutes before `https://example.com/tinyfilemanager.php?p=Workspace&m=40&file=true&folder=true` 
   - View only file - `https://example.com/tinyfilemanager.php?p=Workspace&m=40&file=true` 
   - View only folder - `https://example.com/tinyfilemanager.php?p=Workspace&m=40&file=true` 

add this query paramat the end of url - **&m=x&file=true&folder=true**
you can change minutes to any number it will work.

download [tinyfilemanager.zip](https://github.com/prasathmani/tinyfilemanager/files/3771703/tinyfilemanager.zip)

**Comment by DAngeloFrancesco** [comment]
> Attached customized filemanger,
> 
> * Removed all actions as you mentioned
> * Now able to see files/folder older than 40 mins using following query string adding to URL.
>   
>   * View all folder and files modified 40 minutes before `https://example.com/tinyfilemanager.php?p=Workspace&m=40&file=true&folder=true`
>   * View only file - `https://example.com/tinyfilemanager.php?p=Workspace&m=40&file=true`
>   * View only folder - `https://example.com/tinyfilemanager.php?p=Workspace&m=40&file=true`
> 
> add this query paramat the end of url - **&m=x&file=true&folder=true**
> you can change minutes to any number it will work.
> 
> download [tinyfilemanager.zip](https://github.com/prasathmani/tinyfilemanager/files/3771703/tinyfilemanager.zip)

ty for helping me sir . im glad you take some time for helping me.
i see the update and i like it but some minor edit to complete this please
http://prntscr.com/po3hr3 - delete everything or just hide them please
http://prntscr.com/po3ih1 - delete everything or just hide them please

about the time 40 minutes is working but the opposite i mean i use your link to see only folder and m=40 to see folder 40 minutes ok? is working but not in the good way i mean i create a new folder to see if is working and your custom url show me all folder make from minutes 1 to 40 minutes but i want the opposite to show me only folders older that 40minutes
in rest is good i like how you hides all the butons (PS i ask this hide because maybe i will give acces to someone random and this filemanager have to power to destroy everything :D ) dont worry i like it just hide some..

**Comment by prasathmani** [comment]
@DAngeloFrancesco, updated [tinyfilemanager-v1.1.zip](https://github.com/prasathmani/tinyfilemanager/files/3773001/tinyfilemanager-v1.1.zip)
