### ISSUE TITLE
Bug in load Ace editor javascript and text mode files

### ISSUE THREAD

**Issue by ja-bahmani** [prasathmani/tinyfilemanager#248]
hi
fix ace editor to load "mode-javascript.js" and "mode-text.js" files:

find this line:
			$ext = pathinfo($_GET["edit"], PATHINFO_EXTENSION);

and replace to this:
			$ext = pathinfo($_GET["edit"], PATHINFO_EXTENSION);
			if($ext == "js") $ext = "javascript";
			if($ext == "txt") $ext = "text";

tnx a lot
jbahmani@outlook.com
https://wa.me/989174565564

**Comment by EV-soft** [comment]
My suggestion
Replace to: 
```
	$ext = strtolower(pathinfo($_GET["edit"], PATHINFO_EXTENSION)); #202
	switch ($ext) {
		case 'js':  $ext = 'javascript'; break;
		case 'txt': $ext = 'text'; break;
		case 'htm': $ext = 'html'; break;
		// And others...
		default:    $ext = 'text';
	}
```
