### ISSUE TITLE
Limit file uploads to certain file extensions

### ISSUE THREAD

**Issue by gunemalli** [prasathmani/tinyfilemanager#25]
Hi There,

Love this script. Helped a lot with a few customers. I'd like to request a new feature if it's possible.

My requirement is that I only want a certain file extension to be able to be uploaded for security. Further to this, is it possible to lock down the file rename, not to be able to change the extension?

Regards
Asanka

**Comment by prasathmani** [comment]
`
$total = count($_FILES['upload']['name']);
$allowed =  array('gif','png' ,'jpg');
	
    for ($i = 0; $i < $total; $i++) {
		$filename = $_FILES['upload']['name'][$i];
        $tmp_name = $_FILES['upload']['tmp_name'][$i];
		$ext = pathinfo($filename, PATHINFO_EXTENSION);
        if (empty($_FILES['upload']['error'][$i]) && !empty($tmp_name) && $tmp_name != 'none' && in_array($ext,$allowed)) {
            if (move_uploaded_file($tmp_name, $path . '/' . $_FILES['upload']['name'][$i])) {
                $uploads++;
            } else {
                $errors++;
            }
        }
    }`

replace the code from line no 445. you can add allowed list of extension in $allowed.
