### ISSUE TITLE
Bug in exclude_items

### ISSUE THREAD

**Issue by ja-bahmani** [prasathmani/tinyfilemanager#250]
set $GLOBALS['exclude_items'] to sampleFolder:
$GLOBALS['exclude_items'] = array('sampleFolder');

then open this url:
https://example.com/index.php?p=sampleFolder

this url show all items in folder :(

*fix : replace lines 1002-1006 to :
```
        if (@is_file($new_path) && !in_array($file, $GLOBALS['exclude_items']) && !in_array(explode("/",FM_PATH)[0], $GLOBALS['exclude_items'])) {
            $files[] = $file;
        } elseif (@is_dir($new_path) && $file != '.' && $file != '..' && !in_array($file, $GLOBALS['exclude_items']) && !in_array(explode("/",FM_PATH)[0], $GLOBALS['exclude_items'])) {
            $folders[] = $file;
        }
```

**Comment by ja-bahmani** [comment]
:(
this link show file content :(
http://example.com/fileManager/index.php?p=sampleFolder&view=index.php

**Comment by EV-soft** [comment]
Are you using user_config.php #242 ?
If yes - remenber $GLOBALS['exclude_items'] maybe is set in both!
Comment out
// $GLOBALS['exclude_items'] = array();
in user_config.php

**Comment by ja-bahmani** [comment]
:(
this link edit file content :( when sampleFolder define in $GLOBALS['exclude_items']
http://example.com/fileManager/index.php?p=sampleFolder&edit=index.php

*fix : replace line 1548 to :
```
 if ($file == '' || !is_file($path . '/' . $file) || in_array(explode("/",FM_PATH)[0], $GLOBALS['exclude_items'])) {
```

**Comment by ja-bahmani** [comment]
> Are you using user_config.php #242 ?
> If yes - remenber $GLOBALS['exclude_items'] maybe is set in both!
> Comment out
> // $GLOBALS['exclude_items'] = array();
> in user_config.php

what is user_config.php ?

**Comment by EV-soft** [comment]
user_config.php:
https://github.com/prasathmani/tinyfilemanager/pull/242

**Comment by prasathmani** [comment]
exclude folder issue is fixed
