### ISSUE TITLE
Notice Error.

### ISSUE THREAD

**Issue by jopiortiz** [prasathmani/tinyfilemanager#252]
I've been receiving the following error notice while using PHP 7.1.x
```Notice: A non well formed numeric value encountered in /path/to/file/tinyfilemanager.php on line 2248```

**Comment by prasathmani** [comment]
@daubac402 PR #245 is creating error notice, possible help this out

**Comment by prasathmani** [comment]
reverted to old code.

**Comment by EV-soft** [comment]
The reason for the error is that the parameter value $size= "Folder" is not a number!
Add a line:
```
function fm_get_filesize($size) // Rename: fm_nice_filesize ?
{
    if (!is_numeric($size)) return $size; // string: 'Folder'
    $units = array('&nbsp;B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB');
    $power = $size > 0 ? floor(log($size, 1024)) : 0;
    return sprintf('%s %s', round($size / pow(1024, $power), 2), $units[$power]);
}
```

**Comment by daubac402** [comment]
@prasathmani 
Sorry, I'm in a little bit busy.
I've applyed @EV-soft's above comment fix to my feature branch.
Please recheck and apply if possible. Thank you!
