### ISSUE TITLE
Error while deleting items

### ISSUE THREAD

**Issue by cinetube** [prasathmani/tinyfilemanager#253]
Error while deleting items

<img width="960" alt="1563" src="https://user-images.githubusercontent.com/23441775/68657935-c0ec5580-055e-11ea-83c3-da0b333eb81c.png">

I can't delete any file using Tiny File Manager. How to resolve this issue?

**Comment by prasathmani** [comment]
need file write permission to delete the files, check you have the correct permission

**Comment by cinetube** [comment]
> 
> 
> need file write permission to delete the files, check you have the correct permission

how to assign correct permission?

**Comment by prasathmani** [comment]
try with 755 or 777
