### ISSUE TITLE
How to show the hidden. Documents of

### ISSUE THREAD

**Issue by Xuzan9396** [prasathmani/tinyfilemanager#254]

**Comment by Xuzan9396** [comment]
For example： .gitignore ，  .htaccess ， How to show？
![image](https://user-images.githubusercontent.com/24741439/69006337-ad7b2900-0968-11ea-93d3-ac2ffd4d06c8.png)
![image](https://user-images.githubusercontent.com/24741439/69006346-cbe12480-0968-11ea-94ad-e3a46e81284f.png)

**Comment by Xuzan9396** [comment]
![image](https://user-images.githubusercontent.com/24741439/69006360-15317400-0969-11ea-82dc-a531a1a60638.png)

**Comment by prasathmani** [comment]
enable `Show Hidden Files` in settings
