### ISSUE TITLE
Icons Not Showing

### ISSUE THREAD

**Issue by inellcorpin** [prasathmani/tinyfilemanager#256]
Why are icons not showing?

![image](https://user-images.githubusercontent.com/58069801/69413931-b2672080-0d4c-11ea-818d-b17d2f9ea0c1.png)

I've downloaded all CSS and JS since my site will be running local only and no internet.

**Comment by prasathmani** [comment]
I'm using font awesome icons, so download font awesome and try it

**Comment by inellcorpin** [comment]
Hi Prasathmani, do you have the download? And where do I store them once I have them?

**Comment by EV-soft** [comment]
Download link: 
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
Find this line in tinyfilemanager pdf:
`<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">`
and edit to the place where you save the CSS

Be aware that other things will not work without Internet access (File Viewer / Editor?)

**Comment by inellcorpin** [comment]
I already downloaded that css and have that in place but still not working.

![image](https://user-images.githubusercontent.com/58069801/69419550-a6349080-0d57-11ea-99f5-61bc7fc031b2.png)

**Comment by EV-soft** [comment]
It also need a font:
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2?v=4.7.0

**Comment by inellcorpin** [comment]
Tried right now and still not working. Is this just copy and paste on the css folder?

**Comment by EV-soft** [comment]
Download and save "fontawesome-webfont.woff2" in: Try the same folder as tinyfilemanager.php

**Comment by EV-soft** [comment]
Create a foler:" /webfonts" and place it here.
Read more: https://stackoverflow.com/questions/49550011/font-awesome-icons-in-offline
Read more: https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself

**Comment by EV-soft** [comment]
Sorry... /webfonts is for the newest fontawesome version 5.0
v4.7 from 2017 uses a folder: "/fonts"
url('..**/fonts**/fontawesome-webfont.woff?v=4.7.0') format('woff')

**Comment by inellcorpin** [comment]
I downloaded the latest version of webfonts. However, there are still icons not showing:
![image](https://user-images.githubusercontent.com/58069801/69487042-76d46f80-0e8e-11ea-9084-47b5d82b7750.png)

**Comment by Roni-Neto** [comment]
https://neto.cf/download/78937498rue/fonts%20css%20js.zip

**Comment by inellcorpin** [comment]
> 
> 
> https://neto.cf/download/78937498rue/fonts%20css%20js.zip

I can't open the link...
![image](https://user-images.githubusercontent.com/58069801/69487452-2b718f80-0e95-11ea-8d5a-6a5bb4bd30a9.png)

**Comment by Roni-Neto** [comment]
[fonts css js.zip](https://github.com/prasathmani/tinyfilemanager/files/3883095/fonts.css.js.zip)

**Comment by Roni-Neto** [comment]
?

**Comment by inellcorpin** [comment]
Downloaded the files. It still doesn't show the icons... :(

**Comment by inellcorpin** [comment]
> 
> 
> Downloaded the files. It still doesn't show the icons... :(

Now it's showing after clearing the cache. :)
Thanks to all!
