### ISSUE TITLE
No message / status / information when saving edited file

### ISSUE THREAD

**Issue by joglomedia** [prasathmani/tinyfilemanager#257]
It seems there is no message / status / information when saving edited file
so confusing whether my edit has been successfully saved or not

**Comment by prasathmani** [comment]
duplicate #213

**Comment by EV-soft** [comment]
There are a message
`LINE 398: fm_set_msg('successful save!', 'alert');`
Maybe it is a bug ?

**Comment by prasathmani** [comment]
Added toast message
