### ISSUE TITLE
download large file issues

### ISSUE THREAD

**Issue by kewlfft** [prasathmani/tinyfilemanager#259]
`readfile()` on large files can create issues even if in theory the documentation says it can handle any size. I personally had issues for files over 4GB. This is made worse if several users download the file at the same time. It seems the simplest way to handle this is to output the file in “chunks”.
I have implemented the solution proposed [here](https://www.media-division.com/the-right-way-to-handle-file-downloads-in-php/) and it worked for me. 
To see whether replacing:
~~~
        readfile($path . '/' . $dl);
~~~
with:
~~~
        set_time_limit(0);
        $file = @fopen($path . '/' . $dl,"rb");
        while(!feof($file))
        {
            print(@fread($file, 1024*8));
            ob_flush();
            flush();
        }
~~~
was something we could implement.

**Comment by EV-soft** [comment]
Missing:
`@fclose($file);`

**Comment by kewlfft** [comment]
@EV-soft good point, thanks
