### ISSUE TITLE
Open document files?

### ISSUE THREAD

**Issue by EV-soft** [prasathmani/tinyfilemanager#262]
Is it possible to add a viewer / editor to open document files (LibreOffice)?

**Comment by prasathmani** [comment]
Document viewer is already available in application, but editor feature is not available. 
`Google/Microsoft doc viewer helps you preview PDF/DOC/XLS/PPT/etc. 25 MB can be previewed with the Google Drive viewer`

**Comment by EV-soft** [comment]
It does not work.
When I try to open .odt and .ods files, it is suggested to download the files.

**Comment by prasathmani** [comment]
Added `.odt` and `.ods` extension support, use microsoft doc viewer.
change following configuration
`$GLOBALS['online_viewer'] = 'microsoft';` on line number ``105``

**Comment by EV-soft** [comment]
Still not working !
**Microsoft**: _An error occurred - We're sorry, but for some reason we can't open this for you._
**Google**: _Whoops! - There was a problem displaying this image._
(My testfile was created with LibreOffice Version: 6.1.5.2)

**Comment by prasathmani** [comment]
working for me, check [here ](http://cloud03.ga/work/tfm/tinyfilemanager.php?p=)

**Comment by EV-soft** [comment]
Working on your server, not mine...
Looks like it is a problem with file upload to google/microsoft server. Here's the dump from Firefox: Web developer Network
![billede](https://user-images.githubusercontent.com/21997911/70372363-1f96bc00-18de-11ea-97da-7f3bdc600d65.png)
It is probably not a problem with file manager.

**Comment by prasathmani** [comment]
are you trying from localhost? Google/Microsoft both will not work on localhost

**Comment by EV-soft** [comment]
No. Look here:
tfm.ev-soft.online/tinyfilemanager.php
Now #microsoft" is working (cashed?)
"google" is still bad

**Comment by prasathmani** [comment]
Google drive viewer is not supported the format

**Comment by EV-soft** [comment]
OK thanks.
