### ISSUE TITLE
Make search available to read-only user

### ISSUE THREAD

**Issue by tjharman** [prasathmani/tinyfilemanager#265]
Hi,

Great little file manager.
At the moment I'm manually hacking the if (!FM_READONLY): to be AFTER the search addon section (moving it to line 2959) so that even read-only users can search.

I can't see how allowing access to search is a security issue, it makes working with the file manager much easier.  I don't know if this could be a toggle, or probably it's just easier to say "search is always available"

Thanks!

**Comment by prasathmani** [comment]
available in latest version
