### ISSUE TITLE
Use of undefined constant warning in php7.3

### ISSUE THREAD

**Issue by amurad** [prasathmani/tinyfilemanager#266]
I am running in debian with nginx 16.1 and php7.3. I am getting following warning when trying to open image or pdf file:

> **Warning**: Use of undefined constant online_viewer - assumed 'online_viewer' (this will throw an Error in a future version of PHP) in /**srv/www/index.php** on line **1387**

**Comment by alan67160** [comment]
I'm using Ubuntu Server 19.10 at Raspberry Pi 4B(4GB Ram/128GB SD card) with Nginx 1.16.1 and php7.3-fpm, but I can't see any error.

**Comment by yumyo** [comment]
I see all the warnings on PHP 5.5.9 when setting error_reporting to true. I assume the same should happen for PHP 7.3 as the correct way to set arrays as constant values is to serialize and unserialize the array. https://stackoverflow.com/a/19444381
So changing line 359 to:
`defined('FM_EXCLUDE_ITEMS') || define('FM_EXCLUDE_ITEMS', serialize($exclude_items));`

and line 2298 to:
`    if(!in_array($file, unserialize(FM_EXCLUDE_ITEMS)) && !in_array("*.$ext", unserialize(FM_EXCLUDE_ITEMS))) {`

Solve all fo the notices and warnings at once.

**Comment by yumyo** [comment]
Actually, In PHP 7, array values are also accepted, so you can either use the fix above r upgrade PHP
