### ISSUE TITLE
Turkish language support

### ISSUE THREAD

**Issue by ufukguler** [prasathmani/tinyfilemanager#268]
`{
  "appName": "Tiny File Manager",
  "version": "2.3.8",
  "language": [
    {
      "name": "Türkçe",
      "code": "tr",
      "translation": {
        "Tiny File Manager": "Tiny Dosya Yöneticisi",
        "File Manager": "Dosya Yöneticisi",
        "Sign in": "Giriş Yap",
        "Username": "Kullanıcı adı",
        "Password": "Parola",
        "Sign Out": "Çıkış Yap",
        "Move": "Taşı",
        "Copy": "Kopyala",
        "Save": "Kaydet",
        "Select all": "Hepsini Seç",
        "Unselect all": "Hepsini Bırak",
        "File": "Dosya",
        "Back": "Geri",
        "Size": "Boyut",
        "Perms": "İzinler",
        "Modified": "Son Düzenleme",
        "Owner": "Sahibi",
        "Search": "Arama",
        "New Item": "Yeni Dosya",
        "Folder": "Klasör",
        "Delete": "Sil",
        "Rename": "Yeniden Adlandır",
        "Copy to": "Şuraya Kopyala",
        "Direct link": "Erişim Linki",
        "Upload Files": "Dosyaları Yükle",
        "Change Permissions": "İzinleri Değiştir",
        "Copying": "Kopyalanıyor",
        "Create New Item": "Yeni Dosya Oluştur",
        "Name": "Ad",
        "Advanced Editor": "Gelişmiş Düzenleyici",
        "Remember Me": "Beni Hatırla",
        "Actions": "Hareketler",
        "Upload": "Yükle",
        "Cancel": "İptal Et",
        "Invert Selection": "Seçimi Geri Al",
        "Destination Folder": "Hedef klasör",
        "Item Type": "Dosya Türü",
        "Item Name": "Dosya Adı",
        "Create Now": "Oluştur",
        "Download": "İndir",
        "Open": "Aç",
        "UnZip": "Arşivden çıkart",
        "UnZip to folder": "Klasöre Çıkart",
        "Edit": "Düzenle",
        "Normal Editor": "Normal Düzenleyici",
        "Back Up": "Yedekle",
        "Source Folder": "Kaynak Klasör",
        "Files": "Dosyalar",
        "Change": "Değişim",
        "Settings": "Ayarlar",
        "Language": "Dil",
        "Memory used": "Kullanılan Bellek",
        "Partition size": "Disk Boyutu",
        "Error Reporting": "Hata Raporlama",
        "Show Hidden Files": "Gizli Dosyaları Göster",
        "Full size": "Toplam Boyut",
        "Help": "Yardım",
        "Free of": "Boş Olan",
        "Preview": "Görüntüle",
        "Help Documents": "Yardım Dökümanları",
        "Report Issue": "Sorun Bildir",
        "Generate": "Oluştur",
        "Full Size": "Toplam Boyut",
        "free of": "Boş olan",
        "Calculate folder size": "Klasör Boyutlarını Hesapla",
        "Check Latest Version": "Güncel Sürümü Kontrol Et",
        "Generate new password hash": "Parola Hash Üret",
        "Hide Perms/Owner columns": "Yetki / Sahip Sütununu Gizle"
      }
    }
  ]
}`

**Comment by prasathmani** [comment]
@ufukguler kindly create a pull request.
