### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by jorgemorgado** [prasathmani/tinyfilemanager#270]
What is the best way to contact the application developer(s) privately? I would like to report a security issue which can expose the compromised target and doing a pull request (with the risk of disclosure) might not be the best way. Also, there is no "Security" label on this project and there should be one.
Shall I contact the CCP Programmers email address (the one on the PHP header)? Will this reach the correct people?

**Comment by prasathmani** [comment]
yes, reach out ccpprogrammers[at]gmail.com

**Comment by jorgemorgado** [comment]
Thanks for the quick reply. You should find the report's link on your email:
https://docs.google.com/document/d/1etO4NYnSJe...
