### ISSUE TITLE
Suggestion for online media play

### ISSUE THREAD

**Issue by huya1121** [prasathmani/tinyfilemanager#272]
Hi, I mount googledrvie files to folder,but it seems can't play online videos....
Would you like to add online play function?

**Comment by EV-soft** [comment]
Files with these extensions should appear as video:
('webm', 'mp4', 'm4v', 'ogm', 'ogv', 'mov', 'mkv')

**Comment by huya1121** [comment]
> Files with these extensions should appear as video:
> ('webm', 'mp4', 'm4v', 'ogm', 'ogv', 'mov', 'mkv')

I know that，but cant play...

**Comment by andrewfrazer03** [comment]
Might be because the files cant be accessed, make sure the video files are accessible, e.g. have a look in the developer tools for any 404's or ERR_NAME_NOT_RESOLVED. if there is make sure the document root is set correctly.

**Comment by prasathmani** [comment]
Thank you suggesting, as of now not possible to add this feature, This application developed to help for managing files in the server.
