### ISSUE TITLE
i can upload a file with extension .cfg and .conf? im using it for uplad my backups

### ISSUE THREAD

**Issue by days3991** [prasathmani/tinyfilemanager#277]

**Comment by prasathmani** [comment]
I'm not getting your question?
You can upload any kind of file using tinyfilemanager.

**Comment by days3991** [comment]
when i tried to upload my backup file with extension ".cfg" or ".conf"
ex. "bakup.cfg"  to an folder in my root path "var/www/html/folder1"
it wont be in my folder and its not uploaded

**Comment by prasathmani** [comment]
#233 
 - Check folder permission
 - is it working if upload different formats other than `.cfg` and `.conf`

**Comment by days3991** [comment]
sorry for late answer, it's now working an  i already limited to only this types of file extension.
it's a great software and for my situation in work it's great to have it i look forward to new releases.
