### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by NiravGondalia** [prasathmani/tinyfilemanager#280]
by using the default username and password it show "Login failed. Invalid username or password"

**Comment by prasathmani** [comment]
Please try again,
username : admin
Password : admin@123

php version should be `PHP 5.5.0`  or higher version

**Comment by NiravGondalia** [comment]
> Please try again,
> username : admin
> Password : admin@123
> 
> php version should be `PHP 5.5.0` or higher version

Thank you @prasathmani .... I like your project tinyfilemanager and i want to talk to you about this project so how can i contact you???

**Comment by prasathmani** [comment]
ccpprogrammers[at]gmail.com
