### ISSUE TITLE
Thumbnail view for folders containing images

### ISSUE THREAD

**Issue by Steeefan** [prasathmani/tinyfilemanager#283]
It would be great to be able to activate a thumbnail view when browsing folders containing multiple images. This would be helpful when looking for a specific image so you don't have to open every single file. Would this be possible?

**Comment by EV-soft** [comment]
It is possible. Look here: #244

**Comment by prasathmani** [comment]
thumbnail preview available in latest version
@Steeefan and @deivh

**Comment by Steeefan** [comment]
How can I activate it?

**Comment by prasathmani** [comment]
No configuration required, just downloaded latest version

**Comment by Steeefan** [comment]
Right, now I can see it. Thanks for the hint. It's not exactly what I meant but it'll make do. I'm also gonna go and add a hack for that myself.

Anyhow, great tool! Thanks for providing it.
