### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by YehudaEi** [prasathmani/tinyfilemanager#284]
I improved your file explorer and made improvements to it so it updates automatically through my server.
You can realize the server update on GitHub ...
Of course all user settings are saved ...

If you are interested in hearing more than that, talk to me

**Comment by prasathmani** [comment]
possible create PR, your help will be highly appreciated

**Comment by YehudaEi** [comment]
https://github.com/prasathmani/tinyfilemanager/pull/296
