### ISSUE TITLE
Cannot hide the specified file or folder？

### ISSUE THREAD

**Issue by msdnos** [prasathmani/tinyfilemanager#285]
$exclude_items = array(
'*.php',
'translation.json',
'tinyfilemanager.php',
);
Cannot hide the specified file or folder？

**Comment by prasathmani** [comment]
`$exclude_items`  is it not working?

**Comment by msdnos** [comment]
Yes, it's invalid.

**Comment by msdnos** [comment]
Yes, invalid. The specified file will not be hidden.

**Comment by dartokloning** [comment]
It's happen to me too, but I fix it with change PHP version, from 5.6 to 7.3.
