### ISSUE TITLE
Static files in LAN (unable to connect to Internet)

### ISSUE THREAD

**Issue by crazywhalecc** [prasathmani/tinyfilemanager#288]
Single file manager is good, but when I try using this in some specific network, schools, companies, etc.
I can't visit and get js and css files. It will be better if supporting local static files downloading.

**Comment by prasathmani** [comment]
possibly I'll try to add offline version in feature releases

**Comment by crazywhalecc** [comment]
How are you going to store these offline stylesheet and js file? In a single `.php` file or put into another directory?

**Comment by prasathmani** [comment]
I'll create offline version separably, It will have `assets` directory

**Comment by EV-soft** [comment]
You could try FineFileManager here: https://fine-fm.ev-soft.online/FFM/finefilemanager.php
It is running offline when: $localRun = true;
Folder: "/assets" = "/LocalLib"
Note: It is a demo - not all new features is working.

**Comment by gr01d** [comment]
Any update for this issue, I too have problems with internet connection. I want to make this offline only.

**Comment by prasathmani** [comment]
Thank you suggesting, as of now not possible to add this feature, This application developed to help for managing files in the server.
