### ISSUE TITLE
Can we hide tree view in the left side?

### ISSUE THREAD

**Issue by plonknimbuzz** [prasathmani/tinyfilemanager#29]
i like the new feature but tree view is no needed when we use it on big server and especially with slow connection.

Why? because the script is scan all directory recrusively. So i think we need an option to remove this in the configuration file or you can give us the old ones. because i forgot to fork your last project before this update

**Comment by prasathmani** [comment]
new feature has been added, so now can set `$show_tree_view=false`. tree view will be disabled.
