### ISSUE TITLE
Function Tree View Missing ?

### ISSUE THREAD

**Issue by CloudTechiea** [prasathmani/tinyfilemanager#290]
Hi,

I just read previous issue on
https://github.com/prasathmani/tinyfilemanager/issues/29

Why the function Tree View missing for a new update ?
I hope you can add back ..
TQ

**Comment by EV-soft** [comment]
You could try FineFileManager here: https://fine-fm.ev-soft.online/FFM/finefilemanager.php
If you toggle to Expert-mode on button up right,
you will have a diretory tree on left panel, with a "Search file in subfolders" button.
Note: It is a demo - not all new features is working.
