### ISSUE TITLE
Upload-Button at the bottom of every page?

### ISSUE THREAD

**Issue by devnull4242** [prasathmani/tinyfilemanager#291]
Is it possible to put a "Upload-Button" additional to the bottom? It is not nice to use the "Upload-Button" at the top on mobile devices.
Code:
`
                <li class="list-inline-item"> <a href="?p=<?php echo urlencode(FM_PATH) ?>&amp;upload" class="btn btn-small btn-outline-primary btn-2"><i class="fa fa-check-square"></i> <?php echo lng('Upload') ?> </a></li>`

Example:
![bottom](https://user-images.githubusercontent.com/58322182/72790083-2b8fd080-3c35-11ea-8617-87ef87ba35b3.png)

**Comment by prasathmani** [comment]
All actions in bottom toolbar are related to file selection, but `upload` is not relevant here

**Comment by devnull4242** [comment]
Thant you for your answer. But it is not really nice on mobile devices with navbar-collaps.

![Unbenannt](https://user-images.githubusercontent.com/58322182/72794193-e3c07780-3c3b-11ea-928c-983628336971.png)

**Comment by prasathmani** [comment]
Okay, then I'll improve the navbar design with feature release

**Comment by devnull4242** [comment]
Thank you very much. Tiny File Manager is a really nice software.
