### ISSUE TITLE
Point to drive

### ISSUE THREAD

**Issue by jackcrane** [prasathmani/tinyfilemanager#292]
Hallo!!

I want to run tinyfilemanager on a Raspberry Pi that is plugged into a massive external hard drive with terabytes of data on it. I have 2 questions - Is there a way to cycle through all of that data and index it so I can use it, and can I point it to the drive instead of the normal ```/var/www/html``` dir?

Thank you!

**Comment by prasathmani** [comment]
- Tinyfilemanager has no index concept
- Point to drive - Yes, you can point to drive. use full absolute path in `$root_path`. i.e `/usr/share/myfiles`, but media(image, video, audio) preview will not work if file is outside web root.
