### ISSUE TITLE
Can create and delete folders but not rename

### ISSUE THREAD

**Issue by yumyo** [prasathmani/tinyfilemanager#293]
The error is generic but given I can both create and delete (and open) it does not seem related to permissions, is it?

**Comment by yumyo** [comment]
error_reporting to true does not help.

**Comment by yumyo** [comment]
Also, can rename files but NOT folders

**Comment by prasathmani** [comment]
Even I'm not sure, mostly it related to permissions and environment related, try to change the folder permission

**Comment by yumyo** [comment]
I'd agree it surely must be tho it's quite strange. olders are on 777 at the moment but it's not helping. The only probably uncommon thing in my setup is that TinyFileManager (which is amazing by the way!) does jus live in a folder of a domain. 
So in my setup I have:

`// Root path for file manager
$root_path = $_SERVER['DOCUMENT_ROOT'].'/upload';
$root_url = '';`

With this setup I am able to perform any operation except renaming.
However, if I set `$root_url = ''/upload";`` as it seems suggested elsewhere, trying to open any file results in a 404. Thus I guess the two variables above are correct in my case?

**Comment by prasathmani** [comment]
correct configuration:
```php
$root_path = $_SERVER['DOCUMENT_ROOT'].'/upload';   
$root_url = 'upload';  
```
in 2.4.0 release, added some restriction to rename files, file name should not contain `'/?%*:|"<>'`.

**Comment by yumyo** [comment]
If is set $root_url, trying to open any item results in a 404, where the URL looks as follows:

https://https://[DOMAIN-HERE]/uploadupload/uploads/test/10/10.html

Instead of the correct/working:

https://[DOMAIN-HERE]/upload/uploads/test/10/10.html

**Comment by swarfer** [comment]
The problem is that folders generally do not have extensions so the check for allowed extensions fails.
I have added is_dir() to fm_rename() like this:
function fm_rename($old, $new)
{
    $isFileAllowed = fm_is_valid_ext($new) || is_dir($old);

    if(!$isFileAllowed) return false;

    return (!file_exists($new) && file_exists($old)) ? rename($old, $new) : null;
}

**Comment by soiqualang** [comment]
> The problem is that folders generally do not have extensions so the check for allowed extensions fails. I have added is_dir() to fm_rename() like this: function fm_rename($old, $new) { $isFileAllowed = fm_is_valid_ext($new) || is_dir($old);
> 
> ```
> if(!$isFileAllowed) return false;
> 
> return (!file_exists($new) && file_exists($old)) ? rename($old, $new) : null;
> ```
> 
> }

Thanks, this's work!
