### ISSUE TITLE
pdf preview gives error

### ISSUE THREAD

**Issue by ErikJanDeWilde** [prasathmani/tinyfilemanager#297]
All Office document previews work fine, but pdf documents give an error: file not found. Unlike with office documents, the path seems adjusted. I embedded the file in a wordpress environment, maybe that's the complication?

the headerinfo is:
_File "Toelichting-totaal-aantal-leerlingen-via-regioportret.pdf"
Full path: /sites/sterktechniekonderwijs-ondersteuners.nl/www//bestanden/regio/STO19002/Toelichting-totaal-aantal-leerlingen-via-regioportret.pdf
File size: 381.2 KB B
MIME-type: application/pdf_

path of the file is http://www.sterktechniekonderwijs-ondersteuners.nl/bestanden/regio/STO19002/Toelichting-totaal-aantal-leerlingen-via-regioportret.pdf

**Comment by prasathmani** [comment]
I'm not sure, why the URL is altered. check the configuration of `$root_path` and `$root_url` are configured correctly

**Comment by ErikJanDeWilde** [comment]
Thanks for responding, $root_path and $root_url are fine, I guess, since the preview works OK with Office documents. Perhaps the problem is that I used an iframe to embed your php? I couldn't get it to work correctly with the wordpress theme I used.

**Comment by prasathmani** [comment]
Okay, Did you tried to preview PDF files without embedding Tinyfilemanager.php

**Comment by ErikJanDeWilde** [comment]
yes; please look at https://www.sterktechniekonderwijs-ondersteuners.nl/wp-content/plugins/sto-d3/tinyfilemanager.php?p=STO19002
the docx-files work, the pdf doesn't.

**Comment by prasathmani** [comment]
PDF preview is not working with Microsoft office configuration and this issue is not relevant to tinyfilemanager. try with google drive configuration, I'd tested with google and it is working. 
```php
$online_viewer = 'google';
```

**Comment by ErikJanDeWilde** [comment]
I understand, its an external dpendency. But why then does it work correctly at https://tinyfilemanager.github.io/demo/?
BTW, thanks again for taking your time to respond; I really admire your Tiny File Manager!

**Comment by prasathmani** [comment]
Demo using google drive to show PDF files.
