### ISSUE TITLE
Thumbnail view for File

### ISSUE THREAD

**Issue by marcbth** [prasathmani/tinyfilemanager#300]
Hello,

...I might have a question for you. Maybe I'm too stupid.

tinyfilemanager is in the directory

/var/www/test/tiniyfilemanager

if I changed
$root_path = $_SERVER['DOCUMENT_ROOT'];

in
$root_path = 'home/usertest/files';

I will no longer see thumbnails or
the complete preview does not work anymore.

http://ip/home/usertest/files/folder.jpg as output

no file

i use nginx and php 7.3

Thanks for the effort

Cliff

**Comment by prasathmani** [comment]
media(image, video, audio) preview will not work if file is outside web root.

**Comment by marcbth** [comment]
thank you for the quick response.

is unfortunately a pity, wanted to include the tinyfilemanager in ompd (www.ompd.pl).
Unfortunately embedding does not work either. there are errors in url.

thanks again
