### ISSUE TITLE
replace files

### ISSUE THREAD

**Issue by seron** [prasathmani/tinyfilemanager#305]
My question seems to be related to the behavior described in issue #138. Basically, I'm asking for file replacement behavior.
------
When uploading files with the same name already present, the file is not replaced, but instead the uploaded filename is suffixed with the date and time.

For example, uploading `index.html`, it is renamed to `index_200214144111.html` if `index.html` is already present. I expect it to replace the file.

How can this behavior be changed so that same name files get replaced? I couldn't find anything in the Wiki about it.

**Comment by EV-soft** [comment]
Try change:
`$override_file_name = false;`
to 
`$override_file_name = true;`
at / near line 782

**Comment by seron** [comment]
that worked. thanks!

**Comment by it-toppp** [comment]
How can overwrite be activated when copying files or directories?
