### ISSUE TITLE
MD5 should not be used for passwords

### ISSUE THREAD

**Issue by nickvellios** [prasathmani/tinyfilemanager#31]
MD5 is not encryption and is about as secure as just storing passwords as plaintext.  Please use password_hash().

**Comment by Tha14** [comment]
I second this, using md5 was probably the worst idea...

**Comment by prasathmani** [comment]
MD5 has been removed. 7c9ecf5

**Comment by alecos71** [comment]
Now the user and pass are in clear text, without any hash checking... use instead password_verify and password_hash...
