### ISSUE TITLE
upload button not found

### ISSUE THREAD

**Issue by chinmoydeka** [prasathmani/tinyfilemanager#313]

**Comment by chinmoydeka** [comment]
upload button and settings button are not found please somebody fix the issue

**Comment by prasathmani** [comment]
Upload and settings buttons are available only for admin users, kindly login as admin and check. @chinmoydeka

**Comment by chinmoydeka** [comment]
How can i use this as admin

**Comment by chinmoydeka** [comment]
I got it ..thank you brother ...
