### ISSUE TITLE
File Upload Issue

### ISSUE THREAD

**Issue by dlodaman** [prasathmani/tinyfilemanager#314]
I've tried everything I can think of.  I am able to upload file sizes up to about 30MB.  The problem is I cannot upload anything above this amount.  In tinyfilemanager.php, my setting is: define('MAX_UPLOAD_SIZE', '8000');

My php.ini is set to:
upload_max_filesize = 100M
post_max_size = 101M

When trying to upload, I get the following message: The page was not displayed because the entity was too large.

What other settings do I need to check?  Running IIS 7, PHP version 7.1.7.  Thank you so much for your help.

**Comment by infernostudiosmtl** [comment]
Perhaps my experience can help. I was able to get around the issue within my shared host cpanel configuration.
I tried modifying php.ini - didn't work
I tried modifying .htaccess - didn't work
what did work was modifying the php settings themselves:
1. go to PHP selector
2. OPTIONS tab
3. modify configuration of variables. this allowed me to change the upload max size past 2mb despite the increase in all other areas as above.

Hope this can help someone :)


<img width="552" alt="Screen Shot 2020-10-22 at 9 15 32 PM" src="https://user-images.githubusercontent.com/31630679/96945482-e3475c80-14ab-11eb-87f5-7331c2db9664.png">
