### ISSUE TITLE
Using window.name for config causes problems

### ISSUE THREAD

**Issue by neutralvibes** [prasathmani/tinyfilemanager#315]
Great work first of all.

### Scenario
A tab containing tinyfilemanager is opened by another window, this window sets window.name for future reference.
### Problem
tinyfilemanager actually stores its config in window.name, checks if the name is set, then parses it as json. If the window name has been previously selected, this will of course fail.
### Idea
 Use another window[variable] with  a name that can be modified as a global and implement a try catch structure to handle it and alert developers or automatically use another.

~~~
# Top of file
define('WIN_VAR',"'_tfm'");

# Example usage
# Without try catch
###############
    function fm_get_config(){ if(!!window[<?=WIN_VAR;?>]){ window.config = JSON.parse(window[<?=WIN_VAR;?>]); } else fm_load_cfg()}
    function fm_load_cfg(){{ $.getJSON(window.curi).done(function(c) { if(!!c) { window[<?=WIN_VAR;?>] = JSON.stringify(c), window.config = c; } }); }}
~~~

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
