### ISSUE TITLE
Login dont work

### ISSUE THREAD

**Issue by fernandodeveloper** [prasathmani/tinyfilemanager#322]
After type the users credentiails, and tap in button login. The refresh the page and return the login. 

With no erros, no one message.

**Comment by fernandodeveloper** [comment]
I I type in the username and password (on the login screen) and click to login.

However, he returns to the login page. (Does not show any errors, nor does it open the file listing)

I have already tested with the user with valid and invalid data

**Comment by prasathmani** [comment]
php version should be `PHP 5.5.0` or higher version

**Comment by fernandodeveloper** [comment]
I'm using 

PHP Version 7.2.22
--

**Comment by prasathmani** [comment]
even I'm not sure, why do you getting this issue, try in different server

**Comment by AnthorNet** [comment]
Issue is also happening on the git demo ^^ Tested using Chrome

**Comment by Louuu** [comment]
Have you tried making your web server user the owner of the php sessions directory?
For example `chown nginx /var/lib/php/session/` ?

**Comment by fernandodeveloper** [comment]
> Have you tried making your web server user the owner of the php sessions directory?
> For example `chown nginx /var/lib/php/session/` ?

I'm using hosting provider. I can touch in this folder.

**Comment by alfem** [comment]
I am using php7 as well and I can not pass the login screen. I fill in the form, and then I am redirected to a blank page. Demo page works ok. 

I am no sure about the value I must put into the 'root_url' variable. Examples do not show a real 'url'.

I planned to use this for a school (covid-19 times), but no way.

**Comment by alfem** [comment]
Solved! 

nginx+php installation tutorials recommend to change cgi.fix_pathinfo=0 in php.ini

If I do it, $_SERVER['PHP_SELF']) is empty and abs path for site is wrong.

Changing that parameter to 1 and reloading php service make everything work fine.
