### ISSUE TITLE
Problem with $directories_users and preview

### ISSUE THREAD

**Issue by MaartenV87** [prasathmani/tinyfilemanager#325]
Hi there,

On my website i needed the use the following format to be able to let users access their own personal space.
$directories_users = array(
'user' => '/customers/f/4/f/sbshasselt.be/httpd.www/wiuk/demo/uploads/bowi/',
);

However when the user goes to their space they can't preview the items. The URL is broken.
It creates a location like http://sbshasselt.be/wiuk/customers/f/4/f/sbshasselt.be/httpd.www/wiuk/demo/uploads/bowi/Hasselt.png
and it shoulld be
http://sbshasselt.be/wiuk/demo/uploads/bowi/Hasselt.png

On the website it looks like 
![preview](https://user-images.githubusercontent.com/7249912/77052921-d589a000-69cd-11ea-88a9-ff196626281e.png)

Any idea on a fix?

The admin with no restrictions on folders does see the preview.

**Comment by prasathmani** [comment]
@MaartenV87 , try this
```php
$directories_users = array(
    'user' => $_SERVER['DOCUMENT_ROOT'].'/wiuk/demo/uploads/bowi'
);
```

**Comment by MaartenV87** [comment]
Thank you for your answer, but this didn't fixed the problem.
The files are downloadable so there the location is correct. It's only the preview that doesn't work.

**Comment by jin146** [comment]
Hi, same issue here after a fresh install, even with the admin account (this one doesn't looks like a real admin though, or I missed something). 
A user can preview the files until I set his personal directory.

**Comment by Xeon33** [comment]
Hello,
It looks like when a directory is set for a user, the root path folder of filemanager is added in the link.
I found if you remove "$wd.DIRECTORY_SEPARATOR." from this line:

$root_url =  $root_url.**$wd.DIRECTORY_SEPARATOR.**$directories_users[$_SESSION[FM_SESSION_ID]['logged']];

to looks like this:
$root_url =  $root_url.$directories_users[$_SESSION[FM_SESSION_ID]['logged']];

the tinymanager path it's not added anymore, and the link for preview is fine.

I don't know if doing this could produces some side effects.
Please wait confirmation from Prasathmani

**Comment by alaasharkawy60** [comment]
hello , I've the same problem 
it's working for download not for preview

https://github.com/prasathmani/tinyfilemanager/issues/325#issue-584281851
