### ISSUE TITLE
Bug in .tar archive extraction when destination(s) file(s) already exist (HTTP error 500)

### ISSUE THREAD

**Issue by Mich3le3D** [prasathmani/tinyfilemanager#332]
Step to riproduce this bug:
1. Select one or more file
2. Click Tar button for create .tar archive
3. Click on the .tar archive
4. Click UnZip button
5. HTTP ERROR 500 appear

This happen also by clicking UnZip to folder, if the files structure already exist.
This don't happen with .zip archive, only with .tar (in .zip file he just overwrite the file without ask confirmation).

---
Some system info:

```
$ uname -a
Linux Michele-ROCK64 4.4.185-1222-rockchip-ayufan-g35fc1f1eff95 #1 SMP Tue Jul 16 16:10:11 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```
```
$ apache2 -v
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2019-08-21T20:43:21
```
```
$ php -v
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
```

**Comment by prasathmani** [comment]
fixed
