### ISSUE TITLE
Change Licence to use it with BSD Licenced Projects

### ISSUE THREAD

**Issue by gOOvER** [prasathmani/tinyfilemanager#336]
It would be nice, iy u can change the Licence to a BSD Licence compatible Licence, so other Project can use ur Filemanager.

ispconfig3 can't use it, becasue of incompatible Licence

https://www.howtoforge.com/community/threads/a-file-manager-that-works.83895/

**Comment by prasathmani** [comment]
@gOOvER  added comment in that forum, possibly I'll update in a feature release if required

**Comment by gOOvER** [comment]
great news :)
