### ISSUE TITLE
Error while fetching archive info

### ISSUE THREAD

**Issue by abhimaliyeckal** [prasathmani/tinyfilemanager#340]
Looks like there is some problem when we try to view the zip files. Please look into it. It says **Error while fetching archive info**

![image](https://user-images.githubusercontent.com/6493531/78884960-660d4a80-7a79-11ea-9ecc-df6613ed2b8f.png)

**Comment by prasathmani** [comment]
you will get this kind of issue when `ZipArchive` Library is missing or disabled

**Comment by abhimaliyeckal** [comment]
Yes. I have installed phpzip library and the issue is solved.
