### ISSUE TITLE
Direct link after login

### ISSUE THREAD

**Issue by Alexofhiswalnut** [prasathmani/tinyfilemanager#341]
Hello,

Is it possible to share a gender link https: //xxxxx.xx/index.php?P=Miscellaneous&view=CC2531ZNP-Prod.hex

To give the connection identifiers and then that the user can arrive directly on the link instead of the simple index "/index.php?p="?

thank you.

**Comment by kiber-io** [comment]
Hi. I also asked this question and did it for myself personally.
Find this code in .php file:
`if(function_exists('password_verify')) {
            if (isset($auth_users[$_POST['fm_usr']]) && isset($_POST['fm_pwd']) && password_verify($_POST['fm_pwd'], $auth_users[$_POST['fm_usr']])) {
                $_SESSION[FM_SESSION_ID]['logged'] = $_POST['fm_usr'];
                fm_set_msg(lng('You are logged in'));
                fm_redirect(FM_SELF_URL . '?p=');
            } else {
                unset($_SESSION[FM_SESSION_ID]['logged']);
                fm_set_msg(lng('Login failed. Invalid username or password'), 'error');
                fm_redirect(FM_SELF_URL);
            }
        } else {
            fm_set_msg(lng('password_hash not supported, Upgrade PHP version'), 'error');;
        }`
And replace with it:
`if(function_exists('password_verify')) {
           $path_to_open = '?p=';
            if (isset($_GET['p'])) {
                $path_to_open .= $_GET['p'];
            }
            if (isset($auth_users[$_POST['fm_usr']]) && isset($_POST['fm_pwd']) && password_verify($_POST['fm_pwd'], $auth_users[$_POST['fm_usr']])) {
                $_SESSION[FM_SESSION_ID]['logged'] = $_POST['fm_usr'];
                fm_set_msg(lng('You are logged in'));
                fm_redirect(FM_SELF_URL . $path_to_open);
            } else {
                unset($_SESSION[FM_SESSION_ID]['logged']);
                fm_set_msg(lng('Login failed. Invalid username or password'), 'error');
                fm_redirect($path_to_open);
            }
        } else {
            fm_set_msg(lng('password_hash not supported, Upgrade PHP version'), 'error');;
        }
`

**Comment by Alexofhiswalnut** [comment]
hello, thanks for your code.  but it just allows direct access to the
folder and not a file directly.  If you have the solution.  have a good day.

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
