### ISSUE TITLE
favicon firefox

### ISSUE THREAD

**Issue by kwapster** [prasathmani/tinyfilemanager#342]
the base 64 encoded image still shows even when a favicon is set. very annoying.

**Comment by prasathmani** [comment]
did you try this configuration
```PHP
// Favicon path. This can be either a full url to an .PNG image, or a path based on the document root.
// full path, e.g http://example.com/favicon.png
// local path, e.g images/icons/favicon.png
$favicon_path = '?img=favicon';
```

https://stackoverflow.com/questions/37859753/refresh-favicon-in-bookmarks-firefox

**Comment by kwapster** [comment]
I was able to fix with solutions from the link you posted. Thank you.
