### ISSUE TITLE
Session, self login, Ip Blocking, etc.

### ISSUE THREAD

**Issue by barart** [prasathmani/tinyfilemanager#345]
This is not an issue, is a request to developer,

I like the way that tinyfilemanager handle the sessions with login and ip blocking, 

is there any way that you could make a simple php script that handle ony this so we can add our content on it? (remove the filemanager so we can add our stuff/scritps/code)

Thanks in advance

**Comment by GonistLelatel** [comment]
Hello, you can use a code from `src` folder.
Compiled filemanager is hard to refactoring.

see https://github.com/GonistLelatel/tinyfilemanager_dev/tree/master/src
