### ISSUE TITLE
Error operation in mount unit

### ISSUE THREAD

**Issue by meoluc** [prasathmani/tinyfilemanager#346]
Hi,
Thanks a lot for your job! I very very nice. I have a NAS and I mount on linux ubuntu in folder of tinyfilemanager. I read all folder, but the operation delete, rename, upload etc... The permission is 777 In the folder of tinyfiemanager works very good, but in the mount I can read only...
Can you help me?
Thanks a lot!

**Comment by prasathmani** [comment]
Are you sure that your external hard drive is mounted with the necessary permissions. try this,
https://stackoverflow.com/questions/40951340/php-mkdir-permission-denied-on-mounted-hard-drive
