### ISSUE TITLE
Preview

### ISSUE THREAD

**Issue by maxmontgmx** [prasathmani/tinyfilemanager#348]
Hi all,
I'm just starting using this great tool.
When I try to preview XML file : I see a blank popup. I 'd like to view document lie web page (with XSLT embedded)
When I try to preview HTML file : I see the html code instead of web page.

Can you help me , please? Thanks

**Comment by prasathmani** [comment]
Preview  - it is an source preview. to view actual web page, use direct link option

**Comment by maxmontgmx** [comment]
Thanks for your answer.
Why XML file preview is blank?

**Comment by prasathmani** [comment]
XML file format should work, in case if invalid format it will not work. try with simple xml file.
