### ISSUE TITLE
Should show limit number of files per directory

### ISSUE THREAD

**Issue by devstress** [prasathmani/tinyfilemanager#35]
When a directory holds up to 1 million files, it will cause the browser crashing. It should be nice if we have an option to show only fixed number of files and have a navigate bar to show other using paging.

**Comment by uudruid74** [comment]
Sounds like you need to organize better.  That configuration will cause performance issues on the server and all sorts of problems.

**Comment by prasathmani** [comment]
Thank you suggesting, as of now not possible to add this feature, This application developed to help for managing files in the server.
