### ISSUE TITLE
settings not updating

### ISSUE THREAD

**Issue by mitle** [prasathmani/tinyfilemanager#351]
when saving settings, the old configuration is shown again after pressing the button. Page refresh is needed to show the new settings.

**Comment by prasathmani** [comment]
is your server is running in WSL. plz provide more details about your OS, PHP Version

**Comment by Jonathan57500** [comment]
Hi,
Same issue here

OS:
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"

PHP:
PHP 7.4.6 (cli) (built: May 14 2020 10:02:31) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies

![2020-05-27_19h09_23](https://user-images.githubusercontent.com/20670942/83051054-beaa9e00-a04d-11ea-9e4f-282930ca3356.png)

Go to Settings, change language, click on save, page is reloading but without any change. Same with any option.

![2020-05-27_19h09_36](https://user-images.githubusercontent.com/20670942/83051074-c36f5200-a04d-11ea-8e63-fe7473cafd3f.png)

There is no error in Apache logs. Access logs :

```
X.X.X.X - - [27/May/2020:19:09:37 +0200] "POST /tinyfilemanager.php?p=&settings=1 HTTP/1.1" 200 2165 "https://files.domain.com/tinyfilemanager.php?p=&settings=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
X.X.X.X - - [27/May/2020:19:09:37 +0200] "GET /tinyfilemanager.php?p=&settings=1 HTTP/1.1" 200 12417 "https://files.domain.com/tinyfilemanager.php?p=&settings=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36"
```

**Comment by rems28** [comment]
Hi, I have the same problem. My OS is Debian 10 with php-7.3 provided by the distro. I can make effects to the setting I choose when I click only one setting to change and make the saving operation several times (+/- 3 times works for me)

**Comment by zwozwo** [comment]
I have the same problem, Saving new settings is not possible, when pressing the "Save-Button" it goes back to the old settings. S, for example" if a client wants to change the language, he will see the drop-down-menue, but when choosing another language, Saving doesnt work

**Comment by rene-hermenau** [comment]
@prasathmani May I recommend changing the color for the active button state to green?

It's absolutely not possible to see at a glance if the button is active or disabled which is not so good for usability;-)
Thanks to my friend @alaasalama for catching this.

**Comment by je2555** [comment]
As a note to anyone else who might stumble onto this issue, you can't change any settings in the web interface if you define the `$CONFIG` array in `config.php`

So if you set a default language or some of the other options you can no longer modify them without modifying `config.php`

These seem to be the defaults if you don't define the array:

```php
$CONFIG = '{"lang":"en","error_reporting":false,"show_hidden":true,"hide_Cols":false,"calc_folder":true}';
```

**Comment by someone42** [comment]
I have also encountered this issue, I am using Raspbian GNU/Linux 10 (buster) with php-7.3. After some experimentation, I believe that on some systems, Zend OPcache doesn't realise that tinyfilemanager.php has been modified and when the settings page is immediately reloaded after pressing the Save button, PHP will use the old cached version of tinyfilemanager.php with the old settings.

Here are some workarounds:
1. Disable Zend OPcache. This has a negative impact on performance.
2. Introduce a few seconds delay in reloading the settings page whenever the Save button is pressed. I can submit a PR for this if people are interested.
