### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by ramsamba** [prasathmani/tinyfilemanager#352]
1. is there a dark mode available
2. if not, how does one style the interface, i don't see any css files

thank you

**Comment by prasathmani** [comment]
1 - No
2 - Embedded css available in tinyfilemanager.php file, and we have used bootstrap.

**Comment by prasathmani** [comment]
duplicate #260

**Comment by ramsamba** [comment]
firstly, i forgot to commend you on this great job you've done in creating tiny file manager. just superb work!

theoretically, are there any issues with using CSS variables to replace the hardcoded colors in the code?

**Comment by prasathmani** [comment]
> theoretically, are there any issues with using CSS variables to replace the hardcoded colors in the code?

NO

**Comment by GameGlitz** [comment]
I'm actually laughing that this guy asked such a stupid question, CSS has recolourization built in, I don't know why it's hard for you to add a dark theme, and anyway, just add a bootstrap theme switcher and switch between the default theme and darkly if you wanna make your life even easier LMAO

**Comment by prasathmani** [comment]
dark theme available in latest version.

**Comment by Noahbest6** [comment]
How to enable dark mode

**Comment by prasathmani** [comment]
available under settings section
<img width="654" alt="image" src="https://user-images.githubusercontent.com/11345598/209773848-a27a93a7-d3b5-4d56-8c11-a9e2a992f299.png">
