### ISSUE TITLE
Download file causes timeout

### ISSUE THREAD

**Issue by D0tty** [prasathmani/tinyfilemanager#353]
Hi, it is all fine with small downloads but with larger files (when it takes more than some seconds) I am not able to navigate the file manager.

This behavior does not happen when I use the direct link, and I think that is because the direct link uses the web server (nginx in my case). The download button uses the php file in the url to generate the download link _(href="?p=PATH_TO_FILE")_ and then causing the connection to timeout when I want to do other things on the file manager.

I don't know if this could be fixed or if this is the supposed behavior.

Steps to reproduce:
- Fresh install with one user and no other change
- Launch one large (let's say 1Go) download with the "Download" button
- Try to navigate the file manager it will time out
- [proof] stop the download, you can now navigate the file manager
- [proof] does not time out with the "DirectLink" button

**Comment by prasathmani** [comment]
now download feature is improved with chunk download.
