### ISSUE TITLE
File upload issue

### ISSUE THREAD

**Issue by bluesky-ca** [prasathmani/tinyfilemanager#354]
When uploading a file larger than upload_max_filesize (php.ini) errors are not processed correctly - there is a missing else condition and $response has no value (from error_log ):
PHP Notice:  Undefined variable: response in /var/www/upload/index.php on line 849
Fixes:
1) add default value for $response 
or
2) add else to: if (empty($f['file']['error']) && !empty($tmp_name) && $tmp_name != 'none' && $isFileAllowed) { ... } else { <generate error> }

The above was easy to fix, the part I don't how to to deal with is the upload preview items need to be marked as error - in all cases the dropped files showed up in preview, but did not make to disk.  You may want to add error_log(...,0) in few places to improve error logging.
Thanks for the project - fits a niche between very simple and things like nextcloud.

**Comment by prasathmani** [comment]
@bluesky-ca, your suggestion has been added.
