### ISSUE TITLE
security breaches in tiny file manager

### ISSUE THREAD

**Issue by peefour** [prasathmani/tinyfilemanager#357]
hi,

are you aware of this?

https://www.quantumleap.it/tiny-file-manager-path-traversal-recursive-directory-listing-and-absolute-path-file-backup-copy/

see also other mentions:
https://www.google.com/search?newwindow=1&sxsrf=ALeKk0025t2B-Upsat5D1t8HcK2-iLWyTw%3A1582747077534&ei=xc1WXs2dIMSYkwWvyqGICQ&q=tiny%20file%20manager%20vulnerabilities

**Comment by si458** [comment]
i concur this issue
it is affected and the vulnerability does work and expose stuff it shouldnt do...
awaiting a fix

**Comment by prasathmani** [comment]
@peefour, issue has been fixed now, kindly close the open CVEID.

**Comment by peefour** [comment]
thank you! what is cveid?

[Peefy - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=ikp6a)	[ikp6a]

On May 18, 2020 at 8:09 GMT, Prasath Mani <notifications@github.com> wrote:

[@peefour](https://github.com/peefour), issue has been fixed now, kindly close the open CVEID.
