### ISSUE TITLE
Request: Get Direct Links for Selected Files

### ISSUE THREAD

**Issue by AlekLT** [prasathmani/tinyfilemanager#36]
Would it be possible to add a button in the footer/bottom section that displays a window containing direct links for all the selected files, separated by carriage returns? (Direct links meaning those specifically called 'direct links' in the individual file actions on the right of the file browser.)

As in:
```
#######################
#  Direct Links       #
#######################
#  http://one.jpg     #
#  http://two.jpg     #
#  http://three.jpg   #
#######################
```

This would be extremely useful!

**Comment by prasathmani** [comment]
Currently it's not part of scope.
