### ISSUE TITLE
Bug: about online play url error

### ISSUE THREAD

**Issue by huya1121** [prasathmani/tinyfilemanager#363]
When I setup "User Specific Directories"
the online play video/img/audio file URL is not correct.
for example:
domain   abc.com

User Specific Directories
'user' => '/var/www/abc.com/cloud'

play link should be  http://abc.com/cloud/123.mp4
but it shows:   http://abc.com/var/www/abc.com/cloud/123.mp4

**Comment by TheFax** [comment]
Why you not set only `'user' => '/cloud'` ?

**Comment by huya1121** [comment]
> Why you not set only `'user' => '/cloud'` ?

"Root path "/cloud/gdrive" not found!"
This setting  is not going to work.

**Comment by GonistLelatel** [comment]
bug fixed at forked version, please check

https://github.com/GonistLelatel/tinyfilemanager_dev
