### ISSUE TITLE
Permissions and Owner cols hidden whatever the setting is true or false

### ISSUE THREAD

**Issue by menaFadel** [prasathmani/tinyfilemanager#364]
first of all thank you so much for this great tool
I noticed that perms/owner cols don't show even if it's turned on whether from settings or in the php file directly, I also noticed that this problem doesn't happen on Linux, I'm using Windows but it's not the problem because I tested another php file manager script and it does show/edit file permissions/owner cols
what am I missing?
thanks in advance :)

**Comment by prasathmani** [comment]
@menaFadel File Permissions and Owner are not supported by windows, so this two columns are not applicable for windows, so by default it removed from table columns

**Comment by menaFadel** [comment]
@prasathmani please take a look at this:
https://github.com/misterunknown/ifm
this tool CAN show and edit file permissions on Windows, I already tested it, that means this feature can be implemented
Thanks!
