### ISSUE TITLE
if exist include config.php

### ISSUE THREAD

**Issue by alecos71** [prasathmani/tinyfilemanager#366]
Hello, there is a bug in filemanager...

```
// if User has the customized config file, try to use it to override the default config above
$config_file = 'config.php';
if (is_readable($config_file)) {
    @include($config_file);
}

```
should be...

```
// if User has the customized config file, try to use it to override the default config above
$config_file = './config.php';
if ((file_exists($config_file)) && (is_readable($config_file))) {
    @include($config_file);
}
```
Thanks.

**Comment by rinoshiyo** [comment]
whatever the **include_path** is set to, the following code will work correctly.

```php
$config_file = dirname(__FILE__) . '/config.php';
```

**Comment by alecos71** [comment]
Relative path in this case `./` is the best... it means current folder...

**Comment by rinoshiyo** [comment]
@alecos71 oooh, this was a new discovery for me, thank you 🙇

https://www.php.net/manual/en/ini.core.php#ini.include-path

> Using a . in the include path allows for relative includes as it means the current directory. However, it is more efficient to explicitly use include './file' than having PHP always check the current directory for every include.

**Comment by prasathmani** [comment]
included `./` before file name.

**Comment by Trifid** [comment]
Using $config_file = dirname(__DIR__) . '/config.php';
would be a better fix as “./“ is relative to the _current working directory_ not the folder where the current script is located.

**Comment by alecos71** [comment]
> Using $config_file = dirname(**DIR**) . '/config.php';
> would be a better fix as “./“ is relative to the _current working directory_ not the folder where the current script is located.

tinyfilemanager.php and config.php must be in the same location and "./" sounds good for this purpose. "./" is not a php trick, is a global mechanism that works in every programming language and in every markup language... php, javascript, Java, perl, c++, html, python, etc...

**Comment by Trifid** [comment]
I know that it’s universal for this folder. The problem that I pointed out is that in this case it’s relative to the current working directory which may not be the same as the tiny filemanger folder. If there is a config.php file in the current working directory it will be included instead of the correct file.

**Comment by alecos71** [comment]
> I know that it’s universal for this folder. The problem that I pointed out is that in this case it’s relative to the current working directory which may not be the same as the tiny filemanger folder. If there is a config.php file in the current working directory it will be included instead of the correct file.
> […](#)

if the folder is called for example "app" and tinyfilemanager.php is inside this folder and if in this folder there is also the config.php file, the latter will be loaded correctly.  Two config.php files cannot coexist in the same folder ... ./ means the current folder, therefore the one where tinyfilemanager.php is also located.  If tinyfilemanager.php is located in the "foo" folder and config.php is located in the "pluto" folder the config.php file will not be loaded because it is not located in the "foo" folder.  The question is trivial.

**Comment by Trifid** [comment]
Communication problem here.
Consider this:
webroot-|
     index.php
     config.php
     filemanager/
                 tinyfilemanager.php
                 config.php
All requests are routed through index.php as URLs are rewritten.
Filemanager is included - require(‘./filemanager/tinyfilemanager.php’);

The /current working directory/ is webroot as it is the first file executed.
The /script folder is webroot/filemanager/./
“./“ is relative to webroot/, not filemanager/ even if you use "./" for 
your include in tinyfilemanager the config file included is the one from 
webroot, not the one in filemanager.

**Comment by alecos71** [comment]
> 
> Communication problem here. Consider this: webroot-|     index.php     config.php     filemanager/                 tinyfilemanager.php                 config.php All requests are routed through index.php as URLs are rewritten. Filemanager is included - require(‘./filemanager/tinyfilemanager.php’); The /current working directory/ is webroot as it is the first file executed. The /script folder is webroot/filemanager/./ “./“ is relative to webroot/, not filemanager/ even if you use "./" for your include in tinyfilemanager the config file included is the one from webroot, not the one in filemanager.
> […](#)

1. `$config_file = dirname(DIR) . '/config.php';`

doesn't exist, you are referencing a undefined constant DIR.

2. `$config_file = dirname(__DIR__) . '/config.php';`

produces the same behavior described in your example. The is no way to avoid this, the only way consists in declaring a real and existing directory... example:

```
$config_dir = 'filemanager';  // Set the folder name where you have your config.php file
$config_file = $_SERVER['DOCUMENT_ROOT'] . "/$config_dir/config.php";
```

this assumes that tinyfilemanager `config.php` file is inside the folder `'filemanager'`... and this works fine...

you can customize the folder config_dir variable as you like... I cannot get it working in other ways.

Thanks.
