### ISSUE TITLE
sleep during download 

### ISSUE THREAD

**Issue by kewlfft** [prasathmani/tinyfilemanager#372]
Isn't the `sleep(1)` limiting the download speed to 1024*$chunkSize per second?

https://github.com/prasathmani/tinyfilemanager/blob/0a920029199d88a402a5375edba30559dba13d23/tinyfilemanager.php#L2969

**Comment by kewlfft** [comment]
The `sleep(1)` is still there limiting the download speed, if it is intentional what is the purpose?

**Comment by prasathmani** [comment]
removed b032327
