### ISSUE TITLE
Reuse of the Login system + question license

### ISSUE THREAD

**Issue by NonozgYtb** [prasathmani/tinyfilemanager#378]
I would like to be able to use the TinyFileManager (TFM) login system. But I'm having trouble finding the code.
I would also like to know if I can use it (all codes and graphic theme) without copyright and / or without mention of the authors.

So I would like to reuse the login system to do it all over the website. I can recover the "array" of user accounts with hashed passwords. The only problem here is finding the code for authentication, and the sessions (and cookies) to verify and keep the session active.

Thank you so much.
*PS: The responses of the community are also desired and willingly.*

**Comment by prasathmani** [comment]
You can feel free to use the code.
