### ISSUE TITLE
Improvement: Enclose each user into a different directories

### ISSUE THREAD

**Issue by jotacor** [prasathmani/tinyfilemanager#38]
Currently you can configure several users, but all of them access to the same directory.

A good improvement could be enclose each user into a different directory, because this user is in charge of uploading files only to this folder, or change files only in this folder.

**Comment by Whisper40** [comment]
Hello, i suggest the same thing, i have try to define user as variable in $root_path , but it doesn't arrive to read it.
(Really good code, the interface is good :) )

**Comment by prasathmani** [comment]
@jotacor, thanks for suggestion. added user based directory listing.

**Comment by Whisper40** [comment]
Oh good i will try it  👍👍

**Comment by Whisper40** [comment]
I tried it and it works like a charm ! :)
