### ISSUE TITLE
Uploading file not working

### ISSUE THREAD

**Issue by AgentSmith0** [prasathmani/tinyfilemanager#382]
Hello,

I tried uploading a file in tinyfilemanager on my raspberry pi but it is not working. I changed the max file size settings in php.ini and tried another uploading script. I also changed the root path but URL uploading is working.

Please help! Thanks...

**Comment by prasathmani** [comment]
https://github.com/prasathmani/tinyfilemanager/wiki/FAQ
also check you have write permission

**Comment by AgentSmith0** [comment]
The owner/group is pi and should work with that I tried already with another script.

**Comment by AgentSmith0** [comment]
My issue is now solved. The issue that I edited the code and made some error.
