### ISSUE TITLE
Unable to pass root_path and root_url from another php page

### ISSUE THREAD

**Issue by dasguptaritwik18** [prasathmani/tinyfilemanager#383]
I want to pass root_path and root_url from another php page as session variable or post method. I have to define root_path depending on various conditions on another php page. Based on the conditions, I define root_path and want to pass the root_path to tinyfilemanager so that only this path gets opened in tinyfilemanager on a button click. Please help me in passing the root_path as a parameter from another php page.

**Comment by prasathmani** [comment]
try to Embed the file manager instead of passing values  https://github.com/prasathmani/tinyfilemanager/wiki/Embedding.
Post method will not work because file manager will reload every folder/file navigation.

**Comment by dasguptaritwik18** [comment]
Adding
define(FM_ROOT_PATH,"my_custom_path")
define(FM_ROOT_URL ,"my_custom_url")
will it lead me to the directory I want as root directory?

**Comment by prasathmani** [comment]
yes, you can customize.

**Comment by dasguptaritwik18** [comment]
Thanks. Worked like a charm. Just another query, Is there any config settings that can make it readonly which I can pass through session?

**Comment by prasathmani** [comment]
```php
define('FM_READONLY', true);
```

**Comment by dasguptaritwik18** [comment]
Great!! Thanks to you. Helped a lot.
