### ISSUE TITLE
Provide option to extract zip and RAR file

### ISSUE THREAD

**Issue by Crack827** [prasathmani/tinyfilemanager#384]
Sir, there is no option to extract zip and rar file in it.
We request you to provide this option.

**Comment by prasathmani** [comment]
![image](https://user-images.githubusercontent.com/11345598/85490320-2cb39800-b5ef-11ea-9d28-1f6b9484b6f3.png)
Unzip/tar option is available already, check the screenshot. RAR option is not supported.
