### ISSUE TITLE
hiding full destination path

### ISSUE THREAD

**Issue by zwozwo** [prasathmani/tinyfilemanager#388]
Hello. If a user starts an upload, he will see the full destination path, like this in the attached picture
![Screenshot_filemanager](https://user-images.githubusercontent.com/41323271/86021908-f2e8f400-ba29-11ea-9af2-fda6b589273f.jpg)
Is it possible to hide this?

**Comment by prasathmani** [comment]
Remove `FM_ROOT_PATH` from the line no: 1175,
![image](https://user-images.githubusercontent.com/11345598/87888953-0c8bc300-ca4d-11ea-850e-72ae826d27ff.png)

**Comment by zwozwo** [comment]
That is cool, thank you! How can I give a donation to you? Paypal for example?

**Comment by prasathmani** [comment]
@zwozwo 
There is "Sponsor" button at the top, you can use that to donate.

**Comment by zwozwo** [comment]
Ah, didn't see until now! Thanks again!
