### ISSUE TITLE
we are not able to login to the admin panel

### ISSUE THREAD

**Issue by Crack827** [prasathmani/tinyfilemanager#389]
Sir, we are not able to login to the Tiny File Manager admin panel.
Not showing any error.
Our username and password are correct.
We also tried installing fresh script.
I request you to help us please.

**Comment by prasathmani** [comment]
Not sure. try with different server/browser.

**Comment by Crack827** [comment]
Sir, I just delete  this line {php_value session.save_path
"/var/cpanel/php/sessions/alt-php71}
in .htaccess file.
And now this is working properly.

It's a very awesome script for FM.
