### ISSUE TITLE
Need to upload through nginx reverse proxy, how to?

### ISSUE THREAD

**Issue by jayray-git** [prasathmani/tinyfilemanager#395]
Need to upload through nginx reverse proxy, how to?
location ^~ /storage/ {     
   client_max_body_size 2G;
   proxy_pass http://upstreamserver/storage/;
   proxy_read_timeout 1d;
 }
Gives error "server response with 0 code"

**Comment by prasathmani** [comment]
not sure, check with some server related forum site
