### ISSUE TITLE
Getting an error Call to undefined function json_decode()

### ISSUE THREAD

**Issue by RustinCassiem** [prasathmani/tinyfilemanager#398]
I added the file to my server
with -PHP 7.4
        -apache 2.4.29
Fatal error: Uncaught Error: Call to undefined function json_decode() in /data/www/html/site/tinyfilemanager.php:3216 Stack trace: #0 /data/www/html/site/tinyfilemanager.php(152): FM_Config->__construct() #1 {main} thrown in /data/www/html/site/tinyfilemanager.php on line 3216

**Comment by prasathmani** [comment]
try this https://stackoverflow.com/questions/18239405/php-fatal-error-call-to-undefined-function-json-decode
