### ISSUE TITLE
PHP Warnings

### ISSUE THREAD

**Issue by TigersWay** [prasathmani/tinyfilemanager#40]
I get:
-  `Warning: is_file(): open_basedir restriction in effect`...." at line 669,
-  and "`Warning: is_dir(): open_basedir restriction in effect`...." at line 671.
But nothing I can change on my shared hoster side.

A basic error_reporting(0) seems to be working, but probably not helping an embedded version.
Any better idea?

```
        if (is_file($new_path)) {
            $files[] = $file;
        } elseif (is_dir($new_path) && $file != '.' && $file != '..' && !in_array($file, $GLOBALS['exclude_folders'])) {
            $folders[] = $file;
        }
```

**Comment by TigersWay** [comment]
Nothing? Not even a comment? That's still a real bug.

**Comment by Igreky** [comment]
I also have this problem

**Comment by TigersWay** [comment]
@Igreky Anything specific/particular on your hosting or environment?

**Comment by TigersWay** [comment]
Just tried the master branch and love everything :-)

But still had to add the basic `error_reporting(0)` at the top of the file to make it usable.

**Comment by prasathmani** [comment]
@TigersWay  which version of PHP  your using. bcz i'm not getting any error and my error reporting is on.

**Comment by TigersWay** [comment]
it's working nearly everywhere, so I don't really think the fault is yours.

it gives me the 2 warning on a french webhoster called "Free.fr" running php 5.6.34

**Comment by prasathmani** [comment]
Okay. Thanks for update.
