### ISSUE TITLE
preview of pdf, word, audio and video

### ISSUE THREAD

**Issue by arnoldkamga** [prasathmani/tinyfilemanager#403]
pls the preview of pdf, word, audio and video does not work

**Comment by prasathmani** [comment]
are you trying in localhost, pdf/word preview is not supported in localhost. or in case if you change the `$root_path` then you need to adjust the `$root_url` accordingly

**Comment by ingluislamas** [comment]
Hello, first of all congratulations on this project, it is the best I have seen in a long time.

I have the same problem, I have by default:

$ root_path = $ _SERVER ['DOCUMENT_ROOT'];

And that way the previews work perfectly, but if some user assigned a route that starts from like:

  ROOT / testfolder / imagestest

I can see the files but you can't see the previews anymore, any clues?

Thanks in advance

**Comment by prasathmani** [comment]
if your modified the $root_path, then you have to configured $root_url correctly.
i.e:
```php
$root_path = $_SERVER['DOCUMENT_ROOT'].'/test';
```
then root url should be like bellow
```php
$root_url = 'test';
```

**Comment by ingluislamas** [comment]
For some reason still not working, this is my config file, hope you have a chance to take a look, regards.
<img width="701" alt="Captura de Pantalla 2020-08-19 a la(s) 23 43 33" src="https://user-images.githubusercontent.com/69946912/90717800-0e2bef00-e276-11ea-9740-614df17f6c07.png">

**Comment by prasathmani** [comment]
@ingluislamas ,
try this,
```php
$root_path = $_SERVER['DOCUMENT_ROOT'].'proyectos/testproj/Files';
$root_url = 'proyectos/testproj/Files';
$directories_users = array(); //no change required as path is same as root
```

**Comment by ingluislamas** [comment]
OK, what if I want different users to access different folders?

**Comment by baur** [comment]
@prasathmani 
in my case 
in some users doc preview works with:
$root_path = $_SERVER['DOCUMENT_ROOT'].'/fm/data';
$root_url = '';

in some users works with 
$root_path = $_SERVER['DOCUMENT_ROOT'].'/fm/data';
$root_url = '/fm/data';

?
