### ISSUE TITLE
save button doubles contents

### ISSUE THREAD

**Issue by abgammon** [prasathmani/tinyfilemanager#406]
Newest version, when i save document and then reopen, it has the same content twice in it. for example if i create a text document and use editor and add Test and then save, reopen file it has TestTest. I had a copy of 2.4.1 and ran it side by side and issue not there in 2.4.1.

**Comment by abgammon** [comment]
side note: occuring on test server and live server
test server: windows, apache2.4 php latest
live server: ubuntu apache2 php 5.6

**Comment by kerygmafabian** [comment]
I have the same issue here.

**Comment by DvashVistrame** [comment]
I also faced this
