### ISSUE TITLE
Need a bit of help

### ISSUE THREAD

**Issue by harvestcore** [prasathmani/tinyfilemanager#41]
I've been looking for good file managers for a while and I found yours and I've to say it works like a charm, but i need help with some things.

1. I can't create files or folders, how do I do that? I've tried to give myself permissions (in the server) but same issue. Also i've created new usernames.
2. How do I upload files? I can open files and it looks like files are uploading, but they don't.

Surely i'm doing something wrong. Hope you can help me, thanks :D

**Comment by MirkoPerrone** [comment]
I got the same problem on Debian Jessie x86 , I can upload just one file each time ,  than I can create a folder but I can not delete a full folder( maybe can be a recursive problem) .

**Comment by prasathmani** [comment]
check the file system permissions. reopen if still facing issues.
