### ISSUE TITLE
 ImunifyAV highlights tiny file manager with AV warning

### ISSUE THREAD

**Issue by temabu** [prasathmani/tinyfilemanager#411]
Probably a false positive but  ImunifyAV  on Plesk highlights index.php of file manager with this message:

Error: ImunifyAV has detected malware on the website. Clean it up manually or upgrade to ImunifyAV+ for automatic malware cleanup

ID | Type | Action | Signature ID | File
1 | SRV | Ignore | SMW-SA-05072-php.tool.filemanager-6 | /index.php

![image](https://user-images.githubusercontent.com/6004995/90162364-cc420b00-dd94-11ea-8ee0-affe9d31f968.png)

**Comment by EV-soft** [comment]
index.php is not part of File manager !

**Comment by temabu** [comment]
well, of course I renamed it.  But the file is the exact copy of tinyfilemanager.php...
Any answers?

**Comment by GonistLelatel** [comment]
use code

__index.php__
```php
<?php
require __DIR__ . '/../%your_path%/filemanager.php';
```
and add the ignore rule to antivirus

**Comment by skerbis** [comment]
Oh Oh ... 
![Uploading Bildschirmfoto 2020-11-26 um 17.05.18.png…]()
