### ISSUE TITLE
希望能够把CSS、JS 、等文件内置

### ISSUE THREAD

**Issue by ghost** [prasathmani/tinyfilemanager#413]
https://drive.google.com/file/d/1NvFqHjJySwcWR9ohKgjnx_YV6-Dl14TC/view?usp=sharing

Due to network conditions (loading css, js and other resources is very slow), it is often difficult to open the file manager.
It is difficult to access Google, etc.
I hope you can embed css files, most of which I have downloaded and applied to my own server. Hope it can help more people.

Note, I modified the translation.json file myself, please restore it. Other files are downloaded from the website without any modification

**Comment by GonistLelatel** [comment]
Resources are placed at "cdn" servers, why you prefer store its at the own server?

**Comment by DvashVistrame** [comment]
You can install this to solve this problem
https://www.localcdn.org/

**Comment by kimobo** [comment]
> Resources are placed at "cdn" servers, why you prefer store its at the own server?

Because in most cases I am a local area network, tinyfilemanager and connect to the Internet

**Comment by kimobo** [comment]
> 您可以安装它以部分解决此问题
> https://www.localcdn.org/

I hope it can be used normally when my server is a LAN.

**Comment by kimobo** [comment]
https://github.com/kimobo/my_php_File-manager.git  

This is something I customized for myself. You can refer to the exam.
This is the first time I use github to submit code.

**Comment by linechengchen** [comment]
Chinese players  read    CSS、JS   very slow

**Comment by linechengchen** [comment]
> > 您可以安装它以部分解决此问题
> > https://www.localcdn.org/
> 
> 我希望它可以在我的服务器是LAN时正常使用。很难访问您在中国提供的Google和CDN。加载js，css等文件通常需要一分钟以上的时间，
> 并且由于某些资源无法成功加载，tinyfilemanager也不完整。难以使用，丑陋
> 
> 希望使CSS像config.php。如果有（css，js ...），请使用本地，如果没有，请使用CDN

并不好用 ,不能编辑器很多js 还未整理完毕
