### ISSUE TITLE
Add Unrar option

### ISSUE THREAD

**Issue by error105** [prasathmani/tinyfilemanager#42]
There is any chance that u will add the Unrar option into your projects ?

**Comment by karavidas** [comment]
Trying to implement an unRar function I found out that a package should be installed to the server.

**Comment by dvjantry60** [comment]
en que servidor puedo instalar el tiny file manager
para subir archivos

**Comment by prasathmani** [comment]
Thank you suggesting, as of now not possible to add this feature, This application developed to help for managing files in the server.
