### ISSUE TITLE
Demo not logging in

### ISSUE THREAD

**Issue by nunoperalta** [prasathmani/tinyfilemanager#424]
https://tinyfilemanager.github.io/demo/

I put username and password, but it just brings me back the login page.

**Comment by svein83** [comment]
> https://tinyfilemanager.github.io/demo/
> 
> I put username and password, but it just brings me back the login page.

**I decided to try the demo too**

My experience was the exact same thing.


**I did a few tests**

- Login attempt with *invalid* credentials lead to:
  - Error exposing php variable names.
  - Very useful info for attackers.
- Attempt with correct credentials: 
  - Seems to only reload the login page.

**Comment by GonistLelatel** [comment]
please try tinyfinamanager on localhost or server

**Comment by svein83** [comment]
> please try tinyfinamanager on localhost or server

Why?

If users need to install their own instance then it's no longer a demo...

The most important reason for such a demo is to see what it's like without installing.

It is a great service to anyone looking for a specific solution. They can try the demo and decide if it would fit their needs before touching their server configuration at all. A great time saver IMHO.

**Comment by tankcb** [comment]
Is there an issue with the demo? Neither login is working for me...

**Comment by prasathmani** [comment]
try this one http://tinyfilemanager.eu-gb.mybluemix.net/Demo/

**Comment by svein83** [comment]
> try this one http://tinyfilemanager.eu-gb.mybluemix.net/Demo/

I just did.
Both logins take me into the file list like expected.
And the admin login has more options available like expected

**Comment by yik77** [comment]
provided demo does not work.

**Comment by tankcb** [comment]
> try this one http://tinyfilemanager.eu-gb.mybluemix.net/Demo/

This one worked for me!

**Comment by prasathmani** [comment]
Demo page is running in iframe, so having some issue in chrome, for the time being use Firefox, I'll fix this soon

**Comment by GonistLelatel** [comment]
> > please try tinyfinamanager on localhost or server
> 
> Why?
> The most important reason for such a demo is to see what it's like without installing.

Because file manager is an admin tool to manipulate with files. Your can't get access to not own server.

**Comment by svein83** [comment]
> > > please try tinyfinamanager on localhost or server
> > 
> > Why?
> > The most important reason for such a demo is to see what it's like without installing.
> 
> Because file manager is an admin tool to manipulate with files. You can't get access to not own server.

Well.. This issue is about **THE DEMO** that **SHOULD WORK** like intended instead of it's login system failing. So your comment is not very helpful to anyone.
