### ISSUE TITLE
is there any way I can sort by modified date folders?

### ISSUE THREAD

**Issue by Majklas** [prasathmani/tinyfilemanager#428]
Looking for a simple file manager to fetch log files. I need to make sorting possible either by creation/modification date or filename. Is this possible?

**Comment by prasathmani** [comment]
sorting will work for filename and date columns. but not possible to sort by modified date folders name

**Comment by EV-soft** [comment]
See #295
You can explore "FineFileManager" at: https://fine-fm.ev-soft.online
It will do it...
