### ISSUE TITLE
larger file uploads fail mysteriously

### ISSUE THREAD

**Issue by yik77** [prasathmani/tinyfilemanager#429]
This is very handy tool. When I upload a larger file, say over 2 MB, it fails. Tested both from a desktop and from an iPhone. (tested with 2 files, a large pdf and 4MB photo). I did modified my config.php file to increase size to 15MB, no effect.

**Comment by RiversideRocks** [comment]
Could it be something with your php.ini file?

**Comment by yik77** [comment]
yes, that was it. I needed to modify my php.ini , increase upload_max_filesize to 10M, and restart lighttpd.
