### ISSUE TITLE
Can't login when hosted on my server it reload page

### ISSUE THREAD

**Issue by kingsolomon17** [prasathmani/tinyfilemanager#430]
Have been trying to login for a while now but it keep reloading my page for me

Adding only = to the url

How can I fix this

**Comment by GonistLelatel** [comment]
https://github.com/GonistLelatel/tinyfilemanager_dev 

try this fork, if problem will not resolved, please write issue to fork repository

**Comment by maxmontgmx** [comment]
Hi,
I get the same issue on my machine.
The link is broken.
Thanks for your help
