### ISSUE TITLE
"Error while deleting files"

### ISSUE THREAD

**Issue by Raavtube** [prasathmani/tinyfilemanager#431]
I have seen issue #253 that is a copy of this saying that you need to change perms for the deletion to work. But where do I change that? If my root directory is `/var/www/` how do I get it so that I can delete, edit, and move other files?

**Comment by prasathmani** [comment]
You have to change the permission from hosting server.
https://www.hostgator.com/help/article/how-to-change-permissions-chmod-of-a-file

**Comment by GonistLelatel** [comment]
> I have seen issue #253 that is a copy of this saying that you need to change perms for the deletion to work. But where do I change that? If my root directory is `/var/www/` how do I get it so that I can delete, edit, and move other files?

you can install [tinyfilemanager_dev ](https://github.com/GonistLelatel/tinyfilemanager_dev) with **terro** terminal and call **chmod** from online terminal directly
