### ISSUE TITLE
Your demo site does not work 

### ISSUE THREAD

**Issue by pippo73** [prasathmani/tinyfilemanager#432]
Just for your info, your demo site is not working. It is not a good way to search new users 😉

**Comment by prasathmani** [comment]
Server is up now, demo site having some issue in chrome, check in different browsers.

**Comment by pippo73** [comment]
On my PC with vivaldi browser just does not login. with chrome on the phone it gives me the following error:
`Array ( [fm_usr] => User [fm_pwd] => 12345 ) ERROR - Array ( [fm_usr] => User [fm_pwd] => 12345 )
`
hope it helps you to fix your site/app :-)
