### ISSUE TITLE
Add .webp to preview like jpg / png / images

### ISSUE THREAD

**Issue by deidyomega** [prasathmani/tinyfilemanager#437]
Allow .webp to be previewed like other image formats

**Comment by deidyomega** [comment]
I was able to get mine working by just adding webp everywhere jpg was, and it worked.  If anyone wants this feature, just ask and I'll do a PR

**Comment by deidyomega** [comment]
Was this closed because it's a "wont fix" or did I do you not want feature requests?

**Comment by azudindaem** [comment]
its just simply add mimetype & append file list..

**Comment by deidyomega** [comment]
So the answer is, everyone that wants webp should just fork the project?

**Comment by safraja** [comment]
Preview for Webp should work by default in the latest version, it was added few months ago.
