### ISSUE TITLE
Changing Root Directory

### ISSUE THREAD

**Issue by macarooni-man** [prasathmani/tinyfilemanager#438]
I am unable to change the directory of the browser, is there any way to set it to a different location entirely?

**Comment by prasathmani** [comment]
`$root_path` pointing to  $_SERVER['DOCUMENT_ROOT'] by default, you change into any path in under web directory.
 ```php
$root_path = '/var/www/html'
//or
$root_path = $_SERVER['DOCUMENT_ROOT']."my-folder";
```
