### ISSUE TITLE
Zip options did not support UTF-8

### ISSUE THREAD

**Issue by illuswing** [prasathmani/tinyfilemanager#45]
trying to create a archive with CJK character filename got these error messages

> Warning: ZipArchive::close() [ziparchive.close]: Failure to create temporary file: Invalid argument in /php/download/file.php on line 1848
>Warning: Cannot modify header information - headers already sent by (output started at /php/download/file.php:1848) in /php/download/file.php on line 1421

it seems the zipper function didn't do the iconv part before proceed

**Comment by prasathmani** [comment]
![image](https://user-images.githubusercontent.com/11345598/41806187-c7a75c66-76d6-11e8-98ce-98dcb2d64f62.png)

I,m able to create zip files using CJK characters, please give me more information, so that i can provide solution. @illuswing
