### ISSUE TITLE
exclude on url some folders i want

### ISSUE THREAD

**Issue by fanelise412** [prasathmani/tinyfilemanager#450]
hello i have a old version of this program
more exactly 2.3.8
and i need some help: i want on url to exclude directly from url some folders i want only folders because i use
tiny.php?p=&m=40&folder=true
i want to add also exclude folders i want.. like 6 folders and if i can do this from url will be great.
thanks

**Comment by prasathmani** [comment]
current application does not support this option, you have to customize the file manager as per needs
