### ISSUE TITLE
Disabling delete option for root folder

### ISSUE THREAD

**Issue by Anan5a** [prasathmani/tinyfilemanager#453]
How can I disable delete option to certain folder? 
Example 
```
/root_folder/abcd
/root_folder/efgh/....
/root_folder/bla blah
```
How can I configure ```tinyfilemanager``` so that a user can delete or write inside ```/root_folder``` but cannot directly delete ```/root_folder```

**Comment by prasathmani** [comment]
currently application does not have the option to set user specific permission
