### ISSUE TITLE
Deafult font-size and everytime open advanced editor

### ISSUE THREAD

**Issue by cancavid** [prasathmani/tinyfilemanager#459]
Hi. Advanced editor default font size is 12, How can I set default font-size 14px. Also how can I set open advanced editor everytime?

**Comment by prasathmani** [comment]
![image](https://user-images.githubusercontent.com/11345598/100951020-ad2ddb80-3533-11eb-9f83-afe5359fe777.png)
Change the default font size in line no: 3917
