### ISSUE TITLE
Suggestion: set headers X-Robots-Tag "noindex, nofollow"

### ISSUE THREAD

**Issue by RealUn2ken** [prasathmani/tinyfilemanager#46]
just for tightening security a bit recommend people to set header X-Robots-Tag "noindex, nofollow" via htaccess on root folder or in the server conf or add the meta tags on the  main file. while i undestand the tinyfilemanager has an athentication already set in place i would assume that most people turns it off for practical reasons like working with a team.

**Comment by alecos71** [comment]
<meta name="robots" content="noindex, nofollow">

This is the correct meta html

**Comment by prasathmani** [comment]
Duplicate #68
