### ISSUE TITLE
cannot empty a txt file

### ISSUE THREAD

**Issue by nk932714** [prasathmani/tinyfilemanager#460]
suppose i have a text file on web and i want to remove the text written in it

![image](https://user-images.githubusercontent.com/29853208/99799469-bb095700-2b58-11eb-99ee-a78b89c2b5fe.png)

I'm able to delete the text inside the txt file but unable to save after removing all written text from file. :(

**Comment by prasathmani** [comment]
Kindly check file manager has write permission

**Comment by nk932714** [comment]
Yes! i file manager have write permissions,
I'm able to save if it contains any text, ( browser is sending post request with contents)
but if the content is empty browser is not sending the POST request after hitting save button.

I'm not sure if the issue with Mozilla Firefox v83.0 or with code
