### ISSUE TITLE
Malware? Recognized by: ImunifyAV

### ISSUE THREAD

**Issue by skerbis** [prasathmani/tinyfilemanager#461]
Oh Oh ... 
<img width="861" alt="Bildschirmfoto 2020-11-26 um 17 05 18" src="https://user-images.githubusercontent.com/791247/100373461-192bb380-300b-11eb-83ba-22fbc31422a0.png">

Beginning Code reported: 
SMW-SA-05072-php.tool.filemanager-6	
```
/redaxo/src/addons/be_explorer/vendor/tinyfilemanager.php
......</b>not deleted’;fm_set_msg(sprintf($msg,fm_enc($del)),‘error’);}}else{fm_set_msg(’Wrong f...```

**Comment by prasathmani** [comment]
#273
