### ISSUE TITLE
Office software online preview error

### ISSUE THREAD

**Issue by guozhenyin** [prasathmani/tinyfilemanager#468]
![image](https://user-images.githubusercontent.com/28732288/101228824-4b5aa680-36d8-11eb-9dde-5705ca9aa341.png)

**Comment by prasathmani** [comment]
check #403 and #420

**Comment by guozhenyin** [comment]
Thank you very much for your reply. I have read the solutions of #403 and #420, but I still can’t solve my online preview problem. I still report the same error as before. Here I use Microsoft’s web view, configuration screenshots and Error message
![image](https://user-images.githubusercontent.com/28732288/101242957-e9318e00-3737-11eb-88ae-ba6a6b92128b.png)
![image](https://user-images.githubusercontent.com/28732288/101242972-f484b980-3737-11eb-937b-4d48eca1142c.png)
![image](https://user-images.githubusercontent.com/28732288/101242984-06665c80-3738-11eb-9fb8-37839b869935.png)
Hope you can help me solve this problem, this is the best file management tool I have ever seen

**Comment by prasathmani** [comment]
change doc viewer into `google` in line no  `100`. e.g. 
```php
$online_viewer = 'google'; 
```
or you can directly check your document file preview using bellow url by replacing `xxxx`
`https://view.officeapps.live.com/op/embed.aspx?src=xxxx`
