### ISSUE TITLE
The settings report an error and cannot be saved. The default language is always English, and other options cannot report errors.

### ISSUE THREAD

**Issue by guozhenyin** [prasathmani/tinyfilemanager#469]
![image](https://user-images.githubusercontent.com/28732288/101228949-dc318200-36d8-11eb-8200-6c8f6129d277.png)

**Comment by prasathmani** [comment]
Application settings will not work if your have separate `config.php` file, remove extra config.php file and then try

**Comment by guozhenyin** [comment]
Remove the redundant config.php file and write all the configuration to the tinyfilemanager.php homepage. After logging in, try again and still cannot save the changed settings

**Comment by guozhenyin** [comment]
![image](https://user-images.githubusercontent.com/28732288/101243215-a07ad480-3739-11eb-932d-8dd1f9dbc4e8.png)
The data configuration of translation.json can be read, but after the language is changed, the configuration cannot be saved, and there is no effect after clicking save

**Comment by guozhenyin** [comment]
It has been resolved. It is a permission problem. After setting tinyfilemanager.php, translation.json, and config.php as web user permissions, you can save the configuration
![image](https://user-images.githubusercontent.com/28732288/101247690-ed6ca400-3755-11eb-9a5b-23396d4e10e4.png)
