### ISSUE TITLE
Added Dutch language [NL]

### ISSUE THREAD

**Issue by timnijland3** [prasathmani/tinyfilemanager#472]
{
      "name": "Nederlands",
      "code": "nl",
      "translation": {
        "Actions": "Acties",
        "AdvancedEditor": "Geavanceerde Editor",
        "AppName": "Bestanden",
        "AppTitle": "Bestanden",
        "Back": "Terug",
        "BackUp": "Backup",
        "Cancel": "Annuleren",
        "Change": "Wijzigen",
        "ChangePermissions": "Wijzig rechten",
        "Check Latest Version": "Controleer laatste versie",
        "Copy": "Kopieren",
        "Copying": "Kopieren",
        "CopyTo": "Kopieren naar",
        "CreateNewItem": "Maak nieuw item",
        "CreateNow": "Nu aanmaken",
        "Delete": "Verwijder",
        "DestinationFolder": "Doel",
        "DirectLink": "Directe link",
        "Download": "Download",
        "Edit": "Wijzigen",
        "File": "Bestand",
        "Files": "Bestanden",
        "Folder": "Map",
        "FreeOf": "Vrij van",
        "FullSize": "Volledige grootte",
        "Generate": "Genereren",
        "Generate new password hash": "Genereer nieuwe wachtwoord hash",
        "Help": "Help",
        "Help Documents": "Hulp documenten",
        "InvertSelection": "Selectie omdraaien",
        "ItemName": "Item naam",
        "ItemType": "Item type",
        "Language": "Taal",
        "Login": "Login",
        "Logout": "Uitloggen",
        "MemoryUsed": "Ruimte gebruikt",
        "Modified": "Aangepast",
        "Move": "Verplaatsen",
        "Name": "Naam",
        "NewItem": "Nieuw item",
        "NormalEditor": "Normale editor",
        "Open": "Openen",
        "Owner": "Eigenaar",
        "PartitionSize": "Partitie grootte",
        "Password": "Wachtwoord",
        "Perms": "Permissies",
        "RememberMe": "Onthoud mij",
        "Rename": "Naam wijzigen",
        "Report Issue": "Probleem rapporteren",
        "Save": "Opslaan",
        "Search": "Zoek",
        "SelectAll": "Alles selecteren",
        "Settings": "Instellingen",
        "Size": "Grootte",
        "SourceFolder": "Hoofdmap",
        "UnSelectAll": "Deselecteer alles",
        "UnZip": "Uitpakken",
        "UnZipToFolder": "Uitpakken naar map",
        "Upload": "Upload",
        "UploadingFiles": "Bestanden uploaden",
        "Username": "Gebruikersnaam"
      }

**Comment by prasathmani** [comment]
@timnijland3 , please raise a pull request

**Comment by timnijland3** [comment]
@prasathmani I cannot create the pull request :(

**Comment by prasathmani** [comment]
try https://opensource.com/article/19/7/create-pull-request-github
