### ISSUE TITLE
Global Config

### ISSUE THREAD

**Issue by impronta48** [prasathmani/tinyfilemanager#481]
Hi, when embedding your script in my cakephp app (php 7.4) i get $CONFIG not defined.

I had to change the first line like this
global $CONFIG;
$CONFIG = '{"lang":"it","error_reporting":true,"show_hidden":false,"hide_Cols":false,"calc_folder":false}';

**Comment by prasathmani** [comment]
don't change the first 3 lines, it will break the application. if you want to change that, make sure change `$config_string` accordingly
