### ISSUE TITLE
Sorting files by size

### ISSUE THREAD

**Issue by luisalvarado** [prasathmani/tinyfilemanager#485]
First amazing file manager. I love how it looks. Currently there is an issue with the sorting by size as you can see by the image, it sorts them by the first digit itself instead of analyzing the whole site:

![image](https://user-images.githubusercontent.com/29236/104817502-47e23100-57e7-11eb-976b-45a31cb906ad.png)

So you can see that KB files are showing below MB files (or vice versa if sorted in a reversed order).

**Comment by alex321test** [comment]
issue with the sorting by date too

**Comment by luisalvarado** [comment]
Was not able to do a fix for it, just waiting for developers to see this.

**Comment by EV-soft** [comment]
Error on line 2034  wrong: `<td data-sort="b-"<?php ...`
Should be: `<td data-sort="b-<?php ...`

**Comment by EV-soft** [comment]
See this:
Fix sorting column size and correct appearance #559
