### ISSUE TITLE
header

### ISSUE THREAD

**Issue by joon49** [prasathmani/tinyfilemanager#487]
hello,
I have a problem with tinymanager.
the web site as 2 erros:
Warning: Constants may only evaluate to scalar values in /var/www/sdb/d/b/akwacrash/essai3/index.php on line 378

Warning: Cannot modify header information - headers already sent by (output started at /var/www/sdb/d/b/akwacrash/essai3/index.php:378) in /var/www/sdb/d/b/akwacrash/essai3/index.php on line 2309

What's the problem?

thanks

**Comment by prasathmani** [comment]
not sure, need to check, meantime you can turn off the errors using settings (Error Reporting)

**Comment by ArlorNaturalScientific** [comment]
Hello,
Arrays cannot be used in "define" function with PHP5.
I will make a commit soon for that :)

**Comment by joon49** [comment]
Hello,

 

Thanks for that.

 

 

De : ArlorNaturalScientific <notifications@github.com> 
Envoyé : dimanche 31 janvier 2021 12:26
À : prasathmani/tinyfilemanager <tinyfilemanager@noreply.github.com>
Cc : joon49 <joon43149@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [prasathmani/tinyfilemanager] header (#487)

 

Hello,
Arrays cannot be used in "define" function with PHP5.
I will make a commit soon for that :)

**Comment by ArlorNaturalScientific** [comment]
Here is the commit:
https://github.com/prasathmani/tinyfilemanager/commit/f45e018153415c1ec058f211819044f2d8359c5d
