### ISSUE TITLE
issue with uploading big files across LAN

### ISSUE THREAD

**Issue by kishoresoma007** [prasathmani/tinyfilemanager#492]
Hi, 

Thanks for this cute and tinyfile manager, it works like charm. 

The only issue i found is, I am using this to download and upload some files to central data folder at home. upload is good for files below 10 MB, but files above 10 MB it gets struck. I am uploading over LAN (server where this is hosted) is connected via ethernet cable and laptop from where i am uploading is connected via WLAN (5 Ghz speed)

Kindly suggest. 

Regards,
Kishore

**Comment by prasathmani** [comment]
check server maximum upload limit.
https://stackoverflow.com/questions/42731188/php-change-max-file-size-upload

**Comment by prasathmani** [comment]
Chunked file upload #714
