### ISSUE TITLE
Path "/" not detected

### ISSUE THREAD

**Issue by OursBlanc42** [prasathmani/tinyfilemanager#493]
Hi there.
In the  config.php, if I write :

```
// Root path for file manager
// use absolute path of directory i.e: '/var/www/folder' or $_SERVER['DOCUMENT_ROOT'].'/folder'
**$root_path = '/';**
```

To have access to have access to all directories ; i have the following error :
**Root path "" not found!**

how i can fix this ? 
Thank you for your advice.
Regards

**Comment by prasathmani** [comment]
filemanager will work under web directory only

**Comment by mul14** [comment]
@OursBlanc42 If you really need that, you can modify the source code.

Change this line:
```php
$root_path = rtrim($root_path, '\\/');
```

To this:
```php
$root_path = $root_path != '/' ? rtrim($root_path, '\\/') : '/';
```

That works perfectly for me.
