### ISSUE TITLE
I don't have zip and other options

### ISSUE THREAD

**Issue by mebleno** [prasathmani/tinyfilemanager#495]
Using tinyfilemanager i don't have all options , features, why?
![obraz_2021-02-12_093427](https://user-images.githubusercontent.com/47222597/107746028-7f27fd00-6d15-11eb-85ea-f3ab1e01e455.png)
Regards
Lucas

**Comment by prasathmani** [comment]
login as admin to get all the features

**Comment by mebleno** [comment]
Thank you very much, now works fine :)
