### ISSUE TITLE
Cannot delete in Plesk admin panel

### ISSUE THREAD

**Issue by felischmi2003** [prasathmani/tinyfilemanager#500]
I have a question.
What are permission must this have?
(Sorry for my English, I'm from German😅)

I can't create Folder/files and I can't delete folder and files. Please help. 
Yours sincerely, 
Felix Schmitt

**Comment by prasathmani** [comment]
set 0755 permission

**Comment by felischmi2003** [comment]
> set 0755 permission 

What must I set the permission, I have lokked in the internet, have nothing found

**Comment by prasathmani** [comment]
read/write permission for owner

**Comment by felischmi2003** [comment]
And on Windows?

> 
> 
> read/write permission for owner
> https://www.hostgator.com/help/article/how-to-change-file-permissions-in-plesk

Thanks, for helping.
I solved the problem myself, the usergroup had not enought permissions.

With best regards,
Felix

**Comment by felischmi2003** [comment]
And on Windows?

> 
> 
> read/write permission for owner
> https://www.hostgator.com/help/article/how-to-change-file-permissions-in-plesk

Thanks, for helping.
I solved the problem myself, the usergroup had not enought permissions.

With best regards,
Felix
