### ISSUE TITLE
Password hash util doesn't work

### ISSUE THREAD

**Issue by alexjamesbrown** [prasathmani/tinyfilemanager#501]
https://tinyfilemanager.github.io/docs/pwd.html

This doesn't work? Due to this being a 404:

https://tinyfilemanager.eu-gb.mybluemix.net/pwd.php?callback=jQuery321011504257009927854_1614005076738&pwd=asdfasd&_=1614005076739

**Comment by prasathmani** [comment]
service restarted, so working now.
