### ISSUE TITLE
Exclude Files & Folders doesn't work

### ISSUE THREAD

**Issue by marcel255** [prasathmani/tinyfilemanager#504]
i Exclude this files, but allways shown

$exclude_items = array(
    'index.php',
    'translation.json'
);

**Comment by prasathmani** [comment]
`$exclude_items` will work, make your added the entry in `config.php`, if `config.php` is not there then fallback config will apply from tinyfilemanager.php.

**Comment by marcel255** [comment]
Hi,
thank you for your reponse. Unfortunately it makes no difference whether I enter it in config.php or in tinyfilemanager.php.
The data will still be listed. The view function only brings the message "File not available". Download and other functions work.
I have no idea where the problem could be. I can also send you a DM with the link and take a look at it :)

I use Microsoft Edge.

**Comment by prasathmani** [comment]
check #528
