### ISSUE TITLE
redirect to "index.php?p=" and get error "File not found."

### ISSUE THREAD

**Issue by arbuzovan** [prasathmani/tinyfilemanager#508]
Try to run FM on url like <some-ip>/admin/services/filemanager/
Then try to open url get redirect to "index.php?p=" and error "File not found."

url controlled by nginx

**Comment by prasathmani** [comment]
make sure `$root_path` configured correctly.
use absolute path of directory i.e: '/var/www/folder' or $_SERVER['DOCUMENT_ROOT'].'/folder'

**Comment by arbuzovan** [comment]
> make sure `$root_path` configured correctly.
> use absolute path of directory i.e: '/var/www/folder' or $_SERVER['DOCUMENT_ROOT'].'/folder'

I got error 
`Error: Cannot load configuration`

If it's important, FM should be running at adress `<ip>/ipbpi-admin/services/restricted/`. Dir is `ipbpi-admin` only. `/services/restricted/ `- is virtual path by nginx.
