### ISSUE TITLE
Blank page on modify

### ISSUE THREAD

**Issue by sebastianomelita** [prasathmani/tinyfilemanager#512]
bye,

when i load a file a see this all code
![image](https://user-images.githubusercontent.com/18554803/112000942-bd87b780-8b1e-11eb-8f51-69c1d40f717c.png)

but, when i modify the same file a see a blank page
![image](https://user-images.githubusercontent.com/18554803/112000893-b1035f00-8b1e-11eb-8a56-856d5889854f.png)

I'm using PHP 8.0 on Apache server.

Seems that some particular char values or string values hangs the editor visualization process.

There is some logic to avoid this behavior?

Sebastiano

**Comment by EV-soft** [comment]
Try with setting PHP to version 7.4
TinyFileManager seems not compatible with PHP 8.0
