### ISSUE TITLE
Integrate authentication with site auth 

### ISSUE THREAD

**Issue by ntskalman** [prasathmani/tinyfilemanager#513]
I'm looking for the possibility to use already in place authentication for a site with TinyFileManager.
My users are already logged in to the administration part of the site with teir MySQL username and passwords and the session cookies are set. Can these be used in conjunction with the $auth_users in the code - and if so - HOW?

**Comment by fab966** [comment]
Hi,
I have the same problem.
I'd like to use this FM in my PHP Application where Sessions already exist.

I get some Warnings:
```
Warning: session_cache_limiter(): Cannot change cache limiter when session is active in xxxxx.php on line 198
Warning: session_name(): Cannot change session name when session is active in xxxxx.php on line 199
Warning: Cannot modify header information - headers already sent by (output started at xxxxx/media.php:36) in xxxxx.php on line 2336
```
I'm trying to find a solution.

**Comment by prasathmani** [comment]
try this, https://github.com/prasathmani/tinyfilemanager/wiki/Embedding
