### ISSUE TITLE
 Wiki duplicate config key allowed_upload_extensions

### ISSUE THREAD

**Issue by LMAdrien** [prasathmani/tinyfilemanager#521]
Hello,

 Great app thanks to you. I don't know if here is good place about the wiki issues. I saw wrong key in Config-Flags.md about "Configure allowed file extensions to create/rename" I think it need to replace by $allowed_file_extensions.

**Comment by prasathmani** [comment]
thanks, will update

**Comment by mscalora** [comment]
issue is still there
