### ISSUE TITLE
How to set the default theme

### ISSUE THREAD

**Issue by ccpplinux** [prasathmani/tinyfilemanager#522]
I want to set the theme tomorrow_night_blue as the default theme for my editor. But in the file config.php I see that the variable $theme is accepting only two values - light and dark. So how to set the default theme of this editor to tomorrow_night_blue? Please help me in this regard.

**Comment by prasathmani** [comment]
add the below code into line no 2895 will work.
```php
editor.setTheme("ace/theme/tomorrow_night_blue");
```
![image](https://user-images.githubusercontent.com/11345598/113543975-136f5b80-9605-11eb-8ea0-213d16607d32.png)

**Comment by michacassola** [comment]
Hey, I tried "ace/theme/monokai", but it just shows the standard one and you can't even select anything else.
Would be something nice in the config/config file and not to sed into the main script.
