### ISSUE TITLE
Upload very big files (20GB) issue

### ISSUE THREAD

**Issue by savonarola27** [prasathmani/tinyfilemanager#523]
I am trying to upload very big file, about 20 GB but the upload starts than progress bar stuck indefinitely.

My configuration:
- CentosOS 8.3
- Apache 2.4.37
- php and php-fpm 7.2.24

php.ini config extract:
max_execution_time = 0
max_input_time = -1
memory_limit = 1000M
upload_max_filesize = 25000M
post_max_size = 21400M

tinymanager.php extract:
$max_upload_size_bytes = 25000000000;

LimitRequestBody in httpd.conf is not present so it takes the default value of 0.

I configured a temp dir in php.ini for uploading file and I noticed that the upload is going but is stopped after about 1.1GB and the temporary file is deleted.

Is all correct? Is possible to upload a file so big?

Thanks to all.

**Comment by EV-soft** [comment]
How about PHP-settings:
**upload_max_size**
**post_max_size**

Ref: Cant upload #441

**Comment by savonarola27** [comment]
upload_max_filesize = 25000M
post_max_size = 21400M

**Comment by prasathmani** [comment]
increase the following values in `php.ini` configuration
```
upload_max_size
post_max_size
upload_max_filesize
```
https://stackoverflow.com/questions/28830804/is-it-possible-to-upload-video-size-20gb-at-a-time-by-using-php-as-technolog

**Comment by savonarola27** [comment]
upload_max_filesize = 21000M
post_max_size = 21400M

upload_max_size daesn't exist as parameter in php.ini (or yes?).

**Comment by EV-soft** [comment]
**difference between “upload_max_size” and “upload_max_filesize”**
https://stackoverflow.com/questions/45712556/difference-between-upload-max-size-and-upload-max-filesize
In php.ini -> upload_max_filesize is used !

**Comment by savonarola27** [comment]
And I have it with the correct size. So, any suggestion?

**Comment by phifogg** [comment]
Has this been solved? I also would like to exchange quite large files for up to 5 GB or so.

**Comment by prasathmani** [comment]
Chunked file upload is available now #714. now big files can uploaded easy
