### ISSUE TITLE
🚨 Potential Security Vulnerability - huntr.dev

### ISSUE THREAD

**Issue by huntr-helper** [prasathmani/tinyfilemanager#525]
#### ⚠️ Potential Vulnerability in tinyfilemanager

👋 Hello, @prasathmani - @ranjit-git has disclosed a potential vulnerability in your repository. To validate or invalidate this potential vulnerability, please visit https://huntr.dev/bounties/2-other-tinyfilemanager and join our community in helping secure open-source code.

---

#### ☎️ Need further support?

Come and join us on our [Discord](https://huntr.dev/discord) and a member of our team will be happy to help! 🤗

cc - @JamieSlome

**Comment by JamieSlome** [comment]
@prasathmani - if you would like further disclosures against your repository from [huntr.dev](https://huntr.dev), feel free to drop our badge in your `README.md`:

[![huntr](https://cdn.huntr.dev/huntr_security_badge_mono.svg)](https://huntr.dev)

```[![huntr](https://cdn.huntr.dev/huntr_security_badge_mono.svg)](https://huntr.dev)```
