### ISSUE TITLE
Search question

### ISSUE THREAD

**Issue by huntson** [prasathmani/tinyfilemanager#527]
It would appear that the search only searches the current folder you're in.  For example, let's say you're viewing directory A but you want to search all the folders within directory A for a file, is this possible?

**Comment by prasathmani** [comment]
yes,  use advance search option.
![image](https://user-images.githubusercontent.com/11345598/115093394-cd38c700-9f37-11eb-9b91-7b0b068a7e65.png)

**Comment by huntson** [comment]
Is there a way to make that there default?

**Comment by prasathmani** [comment]
no, current system does not support,  you have to customize it
