### ISSUE TITLE
Filter certain folder names

### ISSUE THREAD

**Issue by huntson** [prasathmani/tinyfilemanager#528]
Is there a way  to hide folders matching certain strings?  For example, I am trying to run this on a Synology unit and they are littered with the '@eaDir' folders.  It would be nice to be able to prevent the users from seeing those.

**Comment by prasathmani** [comment]
check this out https://github.com/prasathmani/tinyfilemanager/wiki/Exclude-Files-&-Folders

**Comment by huntson** [comment]
Not working.

![Screen Shot 2021-04-16 at 8 20 29 PM](https://user-images.githubusercontent.com/38994011/115095951-36491c00-9ef1-11eb-92c7-dd364a82b39a.png)
![Screen Shot 2021-04-16 at 8 20 16 PM](https://user-images.githubusercontent.com/38994011/115095952-36491c00-9ef1-11eb-8119-f400995a0b9c.png)

**Comment by prasathmani** [comment]
make your your setting configuration in `config.php`
--
The default configuration will be loaded from config.php, it is an additional configuration file, Feel free to remove completely this file and configure "tinyfilemanager.php" as a single file application.

**Comment by huntson** [comment]
I'm not sure how what you wrote helps me.  I showed you a screenshot of my config file which is set to, according to my understanding, filter out '@eaDir' yet when I load your application up in a web browser, as per the other screenshot, it shows the '@eaDir' folder.

**Comment by prasathmani** [comment]
in which file your setting `$exclude_items` ?
basically the tinyfilemanager load configuration form `config.php` if `config.php` file not available, then it use `tinyfilemanager.php`, so if you have `config.php`, make sure your setting all configurations in `config.php` file.

I tried in my local environment with same folder name it is working fine

**Comment by huntson** [comment]
I am setting `$exclude_items` in `config.php.`  In the same file I was able to set `$use_auth = false` and tinyfilemanager.php is behaving properly and honoring that argument.  Is it possible that my syntax for `$exclude_items` is wrong?

**Comment by prasathmani** [comment]
> I am setting `$exclude_items` in `config.php.` In the same file I was able to set `$use_auth = false` and tinyfilemanager.php is behaving properly and honoring that argument. Is it possible that my syntax for `$exclude_items` is wrong?

No syntax error

**Comment by prasathmani** [comment]
replace following code in `fm_is_exclude_items` function
```php
function fm_is_exclude_items($file) {
    global $exclude_items;
    $ext = strtolower(pathinfo($file, PATHINFO_EXTENSION));
    if(!in_array($file, $exclude_items) && !in_array("*.$ext", $exclude_items)) {
        return true;
    }
    return false;
}
```

**Comment by prasathmani** [comment]
fix is available in latest code
