### ISSUE TITLE
The owner column cannot be displayed

### ISSUE THREAD

**Issue by elnayang** [prasathmani/tinyfilemanager#529]
The owner column shows **?:?**

What is the cause of this?

For example, does php need to load a certain module?

BTW: I installed nginx 1.18 and php 7.4 by **YUM**

**Comment by EV-soft** [comment]
It depends of 2 PHP-functions: **posix_getpwuid** and **posix_getgrgid**
in the sourcefile you find this line:: 

`if (function_exists('posix_getpwuid') && function_exists('posix_getgrgid')) {...`

(check your PHP-installation by calling: **phpinfo()** )

**Comment by elnayang** [comment]
> It depends of 2 PHP-functions: **posix_getpwuid** and **posix_getgrgid**
> in the sourcefile you find this line::
> 
> `if (function_exists('posix_getpwuid') && function_exists('posix_getgrgid')) {...`
> 
> (check your PHP-installation by calling: **phpinfo()** )

**Much appreciated !**

_And this feature requires the php-process module to be installed._
