### ISSUE TITLE
Read-only access for Guests (no auth)

### ISSUE THREAD

**Issue by dave-lote-agency** [prasathmani/tinyfilemanager#530]
Hi, is there a way to initiate read-only access when auth is not enabled? My use case is sharing a custom link with an authenticated token similar to a dropbox or wetransfer link but I don't want them to edit or upload to the folder. Thanks!

**Comment by prasathmani** [comment]
check this PR #158

**Comment by dave-lote-agency** [comment]
Thank you! I love this little app. Is there a way to force the download of files without going to the more detailed page where the editor would sit?

**Comment by prasathmani** [comment]
![image](https://user-images.githubusercontent.com/11345598/115657639-dde0a700-a354-11eb-94bb-8adc3ae15a6c.png)
use quick download button

**Comment by dave-lote-agency** [comment]
Thanks, I'll try to tweak the code to make the filename link operate in the same way as the quick download button.

**Comment by prasathmani** [comment]
okay, check line no: `1936` and `1988` to change the behavior of link

**Comment by dave-lote-agency** [comment]
Thanks a lot mate! You're a legend

David Bartlett
General Manager

LOTE AGENCY
11 Mckeon Road, Mitcham VIC 3132
03 9879 6234
0417 488 033
www.loteagency.com.au
<https://www.loteagency.com.au/?&utm_source=signature&utm_medium=email&utm_campaign=db_email>

[image: Trustpilot rating]
[image: Trustpilot Stars]
<https://au.trustpilot.com/review/www.loteagency.com.au?utm_medium=Trustbox&utm_source=EmailSignature2>
[image: Trustpilot Logo]
<https://au.trustpilot.com/review/www.loteagency.com.au?utm_medium=Trustbox&utm_source=EmailSignature2>

**Comment by dave-lote-agency** [comment]
Hi Prasath, I'm getting a 404 response on uploaded files over around 50mb.
All my PHP and config settings have my timeouts and upload sizes much
larger than this.

It's a strange response with no sign of a timeout response or other issues.
It's an MP4 file and other MP4's are uploading ok.

I'm happy to send some money to you through PayPal to help me fix this, I
love your app!

David Bartlett
General Manager

LOTE AGENCY
11 Mckeon Road, Mitcham VIC 3132
03 9879 6234
0417 488 033
www.loteagency.com.au
<https://www.loteagency.com.au/?&utm_source=signature&utm_medium=email&utm_campaign=db_email>

[image: Trustpilot rating]
[image: Trustpilot Stars]
<https://au.trustpilot.com/review/www.loteagency.com.au?utm_medium=Trustbox&utm_source=EmailSignature2>
[image: Trustpilot Logo]
<https://au.trustpilot.com/review/www.loteagency.com.au?utm_medium=Trustbox&utm_source=EmailSignature2>

**Comment by prasathmani** [comment]
react out ccpprogrammers[at]gmail.com
