### ISSUE TITLE
Add ability to decompress an archive file

### ISSUE THREAD

**Issue by olibre** [prasathmani/tinyfilemanager#54]
PHP provides the [`PharData`](http://www.php.net/manual/en/class.phardata.php) class to extract an archive. Maybe there are other alternatives...

Could be nice to just upload a light tarball file and decompress it in a selected remote directory.

I have also proposed the same feature on project [filemanager](/alexantr/filemanager), see [issue #31](/alexantr/filemanager/issues/31).

**Comment by prasathmani** [comment]
Tar support added, now can create, open and extract tar files.
