### ISSUE TITLE
#537 #538 #539 #540

### ISSUE THREAD

**Issue by Roni-Neto** [prasathmani/tinyfilemanager#541]
- Added more words with translations: #537 
- After added in the new words with the Portuguese translation: #538 
- Change the theme directly in the preferences: #539 
- Added in the preferences options to make the action buttons colored: #540 
- Added name of the file being edited and a back button in a better location: #542 

I put them apart and can accept one or more changes

**Comment by prasathmani** [comment]
PR merged
