### ISSUE TITLE
Advanced Search: Returns nothing and Dialog gets weird.

### ISSUE THREAD

**Issue by 17500mph** [prasathmani/tinyfilemanager#547]
Advanced Search returns no results.

Enter a Filename:

<img width="853" alt="1" src="https://user-images.githubusercontent.com/36385273/118449572-25cec180-b6a8-11eb-97fb-1f179123d4a0.png">

<img width="1098" alt="2" src="https://user-images.githubusercontent.com/36385273/118449606-2ebf9300-b6a8-11eb-88be-d441b2ebf37c.png">

"Searching..."

<img width="765" alt="3" src="https://user-images.githubusercontent.com/36385273/118449719-4434bd00-b6a8-11eb-9e7f-275dd71f602a.png">

No Results and the bottom of the dialog is missing:
(Sometimes it stays missing when re-selecting Advanced Search until a page reload) 

<img width="859" alt="4" src="https://user-images.githubusercontent.com/36385273/118450878-83174280-b6a9-11eb-9381-8126f6cb343c.png">

I don't see anything that en/disables it in the config options.

**Comment by 17500mph** [comment]
Any more on this? I get zero results from advanced search. Do I need to produce a php info dump? 

I've tried exact CaseSensitive filenames and just words. #566 seemed similar, though perhaps that was just not being clear about Advanced Search. I know it's not doing anything with file content.

**Comment by prasathmani** [comment]
let me check on this issue, also please check in your developer console is there error on the search.

**Comment by 17500mph** [comment]
There's nothing in the console output when selecting advanced search and submitting a phrase. 
..and like I mentioned above.  Entering anything gives no results and then the dialog is broken until the page is forcibly reloaded.

**Comment by AgentSmith0** [comment]
I also have the same problem in the home directory, but in other folders it does work.
