### ISSUE TITLE
Root path not found!

### ISSUE THREAD

**Issue by desertmedicsgear** [prasathmani/tinyfilemanager#552]
Hello, 
Probably a simple error. I need to assign user specified directories. Root is set to default and works before entering the user specified directory in. Admin is not 

// Root path for file manager
// use absolute path of directory i.e: '/var/www/folder' or $_SERVER['DOCUMENT_ROOT'].'/folder'
$root_path = $_SERVER['DOCUMENT_ROOT'];

The directory I need to access is /public_html/propper_inv

// user specific directories
// array('Username' => 'Directory path', 'Username2' => 'Directory path', ...)
$directories_users = array(
'user' => '/propper_inv/'
);

When I log in as user the result is:

Root path "/propper_inv" not found!

Any suggestions much appreciated! 

Thank you!

**Comment by prasathmani** [comment]
```php
$directories_users = array(
'user' => $_SERVER['DOCUMENT_ROOT'].'/propper_inv'
);
```

**Comment by desertmedicsgear** [comment]
> ```
> $directories_users = array(
> 'user' => $_SERVER['DOCUMENT_ROOT'].'/propper_inv'
> );
> ```

Worked perfectly! Thank you for the fast reply and your time!
