### ISSUE TITLE
Excel and ZIP files

### ISSUE THREAD

**Issue by Crosswell99** [prasathmani/tinyfilemanager#56]
There is an issue with MS Excel files (.xlsx). When I open them directly from drive, there is no problem; but when I download them from TinyFileManager, MS Excel says they are damaged. Also when I zip files from TinyFileManager, they are damaged. This happens when i use it with CodeIgniter.

**Comment by prasathmani** [comment]
try with latest, feel free to open another ticket if the problem persists.
