### ISSUE TITLE
2 security vendors flagged this file as malicious

### ISSUE THREAD

**Issue by hostsistemas** [prasathmani/tinyfilemanager#563]
https://www.virustotal.com/gui/file/7d54a48f597c9e14a8e22b2627681d553765a2943d2d14800486580d68c284ef/detection

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/11345598/202869535-6f652fca-7ea5-4d57-9f69-710cfe0f165c.png">
