### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by kamranjbd** [prasathmani/tinyfilemanager#564]
Error: copy(URL): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden

**please fix this error**

![Screenshot 2021-06-03 072058](https://user-images.githubusercontent.com/76621038/120577866-53549280-c43e-11eb-9a0d-4e97a7542961.jpg)

**Comment by prasathmani** [comment]
you may not have the permission to directly access the file, first check your able to download the file.

**Comment by kamranjbd** [comment]
> you may not have the permission to directly access the file, first check your able to download the file.

https://gp.moddroid.com/Concepts%20-%20Sketch,%20Design,%20Illustrate/Concepts%20-%20Sketch,%20Design,%20Illustrate-2021.03.10.apk

**Comment by kamranjbd** [comment]
> you may not have the permission to directly access the file

please add apk file access

**Comment by amanijoseph87** [comment]
I have this error am trying to upload zip file and i can download the file but i cannot upload it using this way
