### ISSUE TITLE
search basic and advanced search not working

### ISSUE THREAD

**Issue by kamranjbd** [prasathmani/tinyfilemanager#566]
search basic and advanced search not working
![Screenshot 2021-06-04 091244](https://user-images.githubusercontent.com/76621038/120744810-42c31b80-c515-11eb-8b50-3e3f56d98a35.jpg)

**Comment by EV-soft** [comment]
As a new user, you should know:
"Search" means search for f**ile names** in the current folder
"Advanced Search" means searching for **file names** in current _and subfolders_
The function works by filtering the current contents of the table in the file name column
_File **content** is not searched!_
There is no tooltip describing this ...
(however, exist: $tr['en']['Search file in folder and subfolders...']  not in use !)

**Comment by kamranjbd** [comment]
> As a new user, you should know:
> "Search" means search for f**ile names** in the current folder
> "Advanced Search" means searching for **file names** in current _and subfolders_
> The function works by filtering the current contents of the table in the file name column
> _File **content** is not searched!_
> There is no tooltip describing this ...
