### ISSUE TITLE
wrong upload directory and rename of uploaded file

### ISSUE THREAD

**Issue by schmidtdruck** [prasathmani/tinyfilemanager#57]
when uploading a file, the destination path will be created in the upload folder. e.g..
upload to: localhost->tinyfilemanager->uploads 
the file is in: localhost->tinyfilemanager->uploads->tinyfilemanager
and the file ist renamed to the last name of the directory path:
test.pdf was renamed to "uploads" , with missing extension (.pdf).
any ideas how to fix that?

**Comment by prasathmani** [comment]
@schmidtdruck , not able to reproduce the issue, provide more information.

**Comment by schmidtdruck** [comment]
see the screenshots, that explains it better. 
http://www.schmidtdruck.com/tinyfilemanager/pic1.png
http://www.schmidtdruck.com/tinyfilemanager/pic2.png
http://www.schmidtdruck.com/tinyfilemanager/pic3.png
Thanks for your help!
Frank

**Comment by prasathmani** [comment]
@schmidtdruck  configure correctly `$root_url` and `$root_path`.

**Comment by prasathmani** [comment]
try with latest, feel free to reopen if issue is not fixed
