### ISSUE TITLE
upload folder 

### ISSUE THREAD

**Issue by kishoresoma007** [prasathmani/tinyfilemanager#573]
Hi, 

TFM is a wonderful tool, I am using it in my home network for backups, files sharing etc. 

I see that FOLDER upload option is not available. Kindly suggest. 

Regards,
Kishore Soma

**Comment by prasathmani** [comment]
Thanks for using TFM,
There is an upload menu in the top header, check it out. TFM will support folder upload, just drag and drop the folder in the upload section.

**Comment by kishoresoma007** [comment]
HI Prashanth,

Thanks for the response.

I was trying from mobile and it is not allowing me to upload folders from
mobile browser.

Regards,
Kishore Soma
