### ISSUE TITLE
Advance Editor not working

### ISSUE THREAD

**Issue by khanakia** [prasathmani/tinyfilemanager#577]
This url is not found  https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.1/mode-txt.js

<img width="863" alt="Screenshot 2021-06-17 at 11 38 04 AM" src="https://user-images.githubusercontent.com/2174170/122340898-7c0d7980-cf60-11eb-943a-0c2bf9d20785.png">

**Comment by prasathmani** [comment]
thanks, let me check
