### ISSUE TITLE
SiteLock Malware Removal

### ISSUE THREAD

**Issue by codymatthew** [prasathmani/tinyfilemanager#578]
Has anyone else had issues with SiteLock deciding this file is malware and completely deleting it?

**Comment by 17500mph** [comment]
…if this is regarding the WebShell vulnerability… where in simple terms it says ‘PHP file manager’ … I wonder if that’s because, well, it actually is that.

**Comment by saeed74** [comment]
I had same issue

**Comment by FransW5** [comment]
A simple solution:

Open tinyfilemanager.php in a text editor And

Replace All:
fm_redirect(FM_SELF_URL . '?p=' . urlencode(FM_PATH));

With:
$FM_PATH=FM_PATH; fm_redirect(FM_SELF_URL . '?p=' . urlencode($FM_PATH));

**Comment by prasathmani** [comment]
#581
