### ISSUE TITLE
$root_url Array?

### ISSUE THREAD

**Issue by jacobsammon** [prasathmani/tinyfilemanager#579]
I have a system where every user has their own root url.

For example, user `john123` may have the root url `https://content.john123.example.com/static/`.

Is there a way for me to set this up so `$root_url` uses an array?

For example:
```
// Root url for links in file manager.Relative to $http_host. Variants: '', 'path/to/subfolder'
// Will not working if $root_path will be outside of server document root
$root_url = array(
	'john123' => 'https://content.john123.example.com/static/',

);
```

**Comment by prasathmani** [comment]
![image](https://user-images.githubusercontent.com/11345598/122645083-1d99f400-d136-11eb-9ac8-7f53a079705b.png)

**Comment by jacobsammon** [comment]
Just tried this (same as in img) and it isn't working... unchanged
```
$root_url = array(
	'john123' => 'https://content.john123.example.com/static/',
);
if (isset($_SESSION[FM_SESSION_ID]['logged']) && !empty($directories_users[$_SESSION[FM_SESSION_ID]['logged']])){
	$root_url = $root_url[$_SESSION[FM_SESSION_ID]['logged']];
}
```
