### ISSUE TITLE
some bug + feature

### ISSUE THREAD

**Issue by borrougagnou** [prasathmani/tinyfilemanager#58]
Hi ! 
I don't know by what begin...

BUG:
- when I change "root_path" variable, I have access correctly in file and folder but... the picture don't preview ... (try with png, pose png into folder, change the "root_path" variable to this folder, the preview not working)

- [AJAX] when I try to upload something (seem like picture) into folder with just "read" permission
he say me it's okay... but not... this folder is only read permission, I don't found the file, but ajax say me it's upladed...
![screen shot 2018-09-05 at 04 07 24](https://user-images.githubusercontent.com/10796546/45067002-5bcae380-b0c1-11e8-9790-db9e3c7afac2.png)

FEATURE:
Where is the button "Upload" and "Cancel" for validate all file we want really upload (for sure we don't send a wrong file by inadvertance or cancel all because something is wrong
![screen shot 2018-09-05 at 04 11 26](https://user-images.githubusercontent.com/10796546/45067093-cb40d300-b0c1-11e8-928a-ad6dadfe37d1.png)

Thanks for fix all of that ^^
Have a nice day

**Comment by regmibijay** [comment]
@borrougagnou I had same issue, you can add relative path as root path. For example if the file to be previewed is in `/var/www/html/uploads` and `tinyfilemanager.php` is in `/var/www/html`, you can add `'uploads'` as root path. It works just fine. 

@prasathmani the issue with write permission check still persists. Maybe we can figure out a way to probe write permissions to destination folder prior to uploading the file.
