### ISSUE TITLE
use auth and guest access

### ISSUE THREAD

**Issue by naftali100** [prasathmani/tinyfilemanager#582]
is there a way to use auth and allow read only access to guests?

**Comment by prasathmani** [comment]
add users into `$readonly_users` list

**Comment by naftali100** [comment]
Look at the pr
I asked for an option to browse *without* login

**Comment by prasathmani** [comment]
check #158

**Comment by naftali100** [comment]
I saw this. But i want normal user to be "managers" that can upload and edit files and guests that can only read without login
The global read only prevent also registered users from edit files

**Comment by naftali100** [comment]
i meant something like this #61
