### ISSUE TITLE
spanish: translate new string version 2.4.6

### ISSUE THREAD

**Issue by Debaq** [prasathmani/tinyfilemanager#589]
"Advanced Search" : "Búsqueda Avanzada",
        "Error while copying fro" : "Error mientras se copiaba desde",
        "Nothing selected" :"Nada seleccionado",
        "Paths must be not equal" : "Las direcciones no pueden ser iguales",
        "Renamed from" :"Renombrado de",
        "Archive not unpacked" :"Archivo no extraido",
        "Deleted" : "Eliminado",
        "Archive not created" : "Archivo no creado",
        "Copied from" : "Copiado desde",
        "Permissions changed" : "Permisos Cambiado",
        "to" : "a",
        "Saved Successfully" : "Guardado correctamente",
        "not found!" : "¡No se encuentra!",
        "File Saved Successfully" : "Archivo guardado Correctamente",
        "Archive" : "Archivo",
        "Permissions not changed" : "Permisos no cambiados",
        "Select folder" :"Seleccionar Carpeta",
        "Source path not defined" : "Dirección no definida",
        "already exists" : "ya existe",
        "Error while moving from" : "Error mientras se movia desde",
        "Create archive?" : "¿Crear Archivo?",
        "Invalid file or folder name" : "Archivo o Carpeta invalida",
        "Archive unpacked" :"Archivo descomprimido",
        "File extension is not allowed" :"Extención de archivo no permitida",
        "Root path" :"Directorio Raiz",
        "Error while renaming from" :"Error al renombrar desde",
        "File not found" : "Archivo no encontrado",
        "Error while deleting items" : "Erro mientras se eliminaban los items",
        "Invalid characters in file name" : "Caracter invalido nombre de archivo",
        "FILE EXTENSION HAS NOT SUPPORTED" :"ARCHIVO NO SOPORTADO",
        "Selected files and folder deleted" :"Archivos y carpetas seleccionadas han sido eliminas",
        "Error while fetching archive info" :"Error al obtener la información del archivo",
        "Delete selected files and folders?" : "¿Eliminar los archivos y carpetas seleccionadas?",
        "Search file in folder and subfolders..." : "Búscar Archivos en carpetas y subcarpetas...",
        "Access denied. IP restriction applicable" :"Acceso denegado. IP denegada",
        "Invalid characters in file or folder name" :"Caracteres invalidos en los nombres de sus carpetas o archivos",
        "Operations with archives are not available" : "Operaciones con archivos no se encuentras disponibles",
        "File or folder with this path already exists" :"El archivo o carpeta con esta ruta ya existe",
        "Moved from" : "Movido desde",
        "You are logged in" : "Bienvenida/o",
        "Preview" : "Previsualizar",
        "Help" : "Ayuda",
        "not deleted" : "no eliminado",
        "Search a files" : "Buscar Archivo"

**Comment by prasathmani** [comment]
@Debaq thanks for sharing, if possible please create a PR
