### ISSUE TITLE
404 blank page

### ISSUE THREAD

**Issue by MartinKogovsek** [prasathmani/tinyfilemanager#590]
Initially when i upload tinyfilemanager.php it works as it should, but after some time (2,3h), i get a white blank 404 page.

I only renamed tinyfilemanager.php to index.php, everything else I left as it is.

I run it on hosting24 cPanel, with php 7.4 (i'v also tried others).

**Comment by EV-soft** [comment]
check #273

**Comment by MartinKogovsek** [comment]
Addding an exception on Imunify360 fixed the issue, thanks.
