### ISSUE TITLE
Not enable ON Show Hidden Files ( php 7.4 ) 

### ISSUE THREAD

**Issue by nguyenhoangnam3111996** [prasathmani/tinyfilemanager#593]
I press the ON button then save it but the button comes back OFF. Can anyone help me to solve this problem?

**Comment by EV-soft** [comment]
Have you tryed: "Page refresh"
See: #351

**Comment by nguyenhoangnam3111996** [comment]
> Have you tryed: "Page refresh"
> See: #351

Yes, I tried, but still nothing changed

OS:
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.5
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

PHP:
PHP 7.4.19 (cli) (built: May 11 2021 16:58:50) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by 17500mph** [comment]
LOL.. this is an infinite loop. #593 says try #351 .. which ends up referring to #593 again .. and there isn't really anything to even try in #351. I tried doing it 50 times and still can't get it to change anything. I'd be thrilled if even that worked. Three times? I'd be a utopia drinking pure bliss.

**Comment by je2555** [comment]
17500mph @nguyenhoangnam3111996 

I fixed this for us by realizing that you can't change any settings in the web interface if you define the `$CONFIG` array in `config.php`

So if you set a default language or some of the other options you can no longer modify them without modifying `config.php`

These seem to be the defaults if you don't define the array:

```php
$CONFIG = '{"lang":"en","error_reporting":false,"show_hidden":true,"hide_Cols":false,"calc_folder":true}';
```
