### ISSUE TITLE
No webroot folder on my new server

### ISSUE THREAD

**Issue by Adrian3670** [prasathmani/tinyfilemanager#594]
I am using tiny file manager as part of a class I am taking and when I first logged into my server the file manager was completely blank. There was no webroot folder for me to input files into and as far as I can tell there is no other way to get the file manager to recognize my files. It uploads them just fine and I can preview pictures and edit source code all I want but when I link to the file it says the requested resource is not found and the url I was provided goes to the default website. There is no index.html file anywhere I can see in the tiny file manager for me to overwrite with my own. Adding a new folder named webroot also does nothing.

**Comment by prasathmani** [comment]
if your modified the $root_path, then you have to configure $root_url correctly.
i.e:
```php
$root_path = $_SERVER['DOCUMENT_ROOT'].'/test';
```
then root url should be like bellow
```php
$root_url = 'test';
```
