### ISSUE TITLE
use tinyfilemanager in php mvc

### ISSUE THREAD

**Issue by imanmotaqi** [prasathmani/tinyfilemanager#606]
how can i use tinyfilemanger in my php mvc projrct?
is it possible?

**Comment by prasathmani** [comment]
Check this out 
https://github.com/prasathmani/tinyfilemanager/wiki/Embedding

**Comment by dpDesignz** [comment]
> how can i use tinyfilemanger in my php mvc projrct? is it possible?

Did you get this working? I'm also trying to do this but the code keeps injecting itself to the top of my page rather than in the element I have the require in.
