### ISSUE TITLE
Read-only access without login

### ISSUE THREAD

**Issue by hfel** [prasathmani/tinyfilemanager#61]
Hi! 

I'd like to request the creation of a 'guest mode' - i.e. one where visitors can automatically view the files without logging in, but without write permissions, which would require authentication before becoming available. Such a feature has been incorporated into [another](https://github.com/marekrei/encode-explorer) PHP file manager, which however is quite outdated by this point.

**Comment by wmerfalen** [comment]
@prasathmani I can start on this, if you'd like.

**Comment by alecos71** [comment]
Guest that can read htaccess and htpasswd??? This is insane!!! Nobody should access to private folders and files... give the opportunity to hackers to read private and secret files is the right way to have the site compromised by malware!!! or even worse give read access to files containing security data such as user and pass in clear text!!! It is too dangerous!!! Don't release this feature!!!

**Comment by hfel** [comment]
Well, this could be easily circumvented by making an option to blacklist certain files from showing up in the file browser.

**Comment by alecos71** [comment]
I think it's too dangerous, for example, if you oversee to exclude the db.php file that contains login credentials, anyone with read access to that file can access sensitive and reserved areas of their website, who has more of 500 files like me, you can understand that it would become really difficult and quite annoying to exclude all the folders or files from the configuration of the filemanager ... no one should have read access to private files, it would take an inattention to compromise an entire website ... we think about security ...

**Comment by hfel** [comment]
Well the whole feature should be optional, so that the people who want can just keep the auth for read access too and not use the guest mode. No need to worry man, I'm sure we can find some solution that can work for everyone ;)

**Comment by wmerfalen** [comment]
There should probably be a ToS or protective license guarding against mis-use of this script (if one doesn't already exist).

**Comment by wmerfalen** [comment]
Would it make sense to have an array of sensitive file names that we can compare against and not show those if read-only access is granted?

**Comment by hfel** [comment]
Thanks! I wonder though if it would be possible to include a mode where the file manager is visible by default with only read access, with the option to sign in as a user with heightened privileges. At the moment, when I want to direct a guest to the file manager, they have to sign in with a guest account, which just seems like an unnecessary move as it doesn't really confer them any more powers anyway.

**Comment by 17500mph** [comment]
Old thread but this will make that work. If you want to have admin functions too, just use a second version of the script as normal with a different, perhaps obscure filename.. 

----------------------------------

diff --git a/tinyfilemanager.php b/tinyfilemanager.php
index ec5cb72..4e6d8a4 100644
--- a/tinyfilemanager.php
+++ b/tinyfilemanager.php


@@ -208,6 +208,7 @@ if (defined('FM_EMBED')) {
     }
     set_error_handler('session_error_handling_function');
     session_start();
+    $_SESSION[FM_SESSION_ID]['logged'] = 'user';
     restore_error_handler();
 }
