### ISSUE TITLE
PDO query in linked php causes blank page

### ISSUE THREAD

**Issue by Daftus** [prasathmani/tinyfilemanager#616]
Hi,

I implemented a sidebar around the FM which is included in the FM .php file. This sidebar makes a PDO query but when I try to access the FM through the sidebar it results on a blank page with no error. I removed the PDO query and everything just works fine after, but I need the query !
Any guess ?

Thanks

**Comment by prasathmani** [comment]
turn on error reporting in tinyfilemanager setting page and check error log, mostly session start will through error.

**Comment by Daftus** [comment]
Error log throws an error occuring when fm_show_nav_path() is called is the main. I don't why this is an issue with the path of the FM since i'm not modifying it in any way.
![Capture](https://user-images.githubusercontent.com/27859474/129782658-31074772-a0ec-4400-87ce-327c62da18ec.PNG)

**Comment by Daftus** [comment]
Ok it seems like my main.php included in the FM file wasn't trully read by the FM. The path is still messing with with me but atleast I do not have this fatal_error anymore!

Thanks
