### ISSUE TITLE
Wiki page correction needed

### ISSUE THREAD

**Issue by ylavi** [prasathmani/tinyfilemanager#617]
https://github.com/prasathmani/tinyfilemanager/wiki/Security-and-User-Management
states
> If not able to generate password or facing any issue, than generate password using tinyfilemanager itsef on tinyfilemanager > settings > Generate new password hash or alternative password generator here

It should say (as of version 2.4.6)

> If not able to generate password or facing any issue, than generate password using tinyfilemanager itsef on tinyfilemanager > **Help** > Generate new password hash or alternative password generator here

**Comment by prasathmani** [comment]
page updated.
