### ISSUE TITLE
Php 8 Compatibility

### ISSUE THREAD

**Issue by skrlance** [prasathmani/tinyfilemanager#618]
Is TinyFileManager script Php 8 compatible?
If not! Is it possible that I can request you to update and make it?

Sory I am asking you because I am on Php 8 on my server and TinyFileManager can be very useful for my file management works. I am hesitating to use it right now because I don't see it updated from long time and I felt like it won't be Php 8 compatible!

**Comment by EV-soft** [comment]
It is Php 8 compatible
See: #557
