### ISSUE TITLE
Unable to Upload APK Files

### ISSUE THREAD

**Issue by RipoN4** [prasathmani/tinyfilemanager#621]
Unable to Upload Big File size of 50M or above
Showing this error

`<html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>cloudflare</center> </body> </html>      
`
please tell me how to solve it?

**Comment by wangerzi** [comment]
`Request Entity Too Large`, if you are using nginx, you can modify `client_max_body_size` at `nginx.conf`, just like:

```ini
http {
    // ...
    client_max_body_size 200m;
    // ...
}
```
or 

```ini
server {
    // ...
    client_max_body_size 200m;
    // ...
}
```ini
location {
    // ...
    client_max_body_size 200m;
    // ...
}
```

Reference Link: http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by RipoN4** [comment]
I'm Using litespeed server
