### ISSUE TITLE
Missing " @ L1388

### ISSUE THREAD

**Issue by 17500mph** [prasathmani/tinyfilemanager#626]
https://github.com/prasathmani/tinyfilemanager/blob/1db671301975122046d140e5e9ddc3078ca8fbb9/tinyfilemanager.php#L1786-L1793

                        <button type="button" class="btn btn-sm btn-outline-primary name="Save" data-url="<?php echo fm_enc($file_url) ?>" onclick="edit_save(this,'nrl')"><i class="fa fa-floppy-o"></i> Save
                        </button>

....

                        <a title="Plain Editor" class="btn btn-sm btn-outline-primary" href="?p=<?php echo urlencode(trim(FM_PATH)) ?>&amp;edit=<?php echo urlencode($file) ?>"><i class="fa fa-text-height"></i> <?php echo lng('NormalEditor') ?></a>

....

                        <button type="button" class="btn btn-sm btn-outline-primary" name="Save" data-url="<?php echo fm_enc($file_url) ?>" onclick="edit_save(this,'ace')"><i class="fa fa-floppy-o"></i> <?php echo lng('Save') ?>
                        </button>

**Comment by prasathmani** [comment]
possible please create a PR

**Comment by non-bin** [comment]
I believe this has been fixed
