### ISSUE TITLE
Support for SFTP?

### ISSUE THREAD

**Issue by sdwru** [prasathmani/tinyfilemanager#628]
How hard would it be to make this work accessing remote SFTP files/directories instead of local files/directories?

I already have the SFTP client running on the back end using phpseclib and accessing the files/directories remotely.   So I just need the web UI front end part of it and don't want to try code all that from scratch.  Tinyfilemanager has a nice simple UI but it appears tightly integrated with the back end.  

I doubt it would be possible to have everything work but I just need very basic things.  Directory browse, file view, file download.  All authentication is handled by phpseclib so it would not need to do any of that.

**Comment by prasathmani** [comment]
thanks for your query. current application not support SFTP feature.
