### ISSUE TITLE
I want a little change on this perfect filemanager.

### ISSUE THREAD

**Issue by addoloratacalabresi** [prasathmani/tinyfilemanager#64]
Hello sir.
i dont know where to edit and how..
the script is perfect. but I only want to see files older than 30 minutes. and the location where to change it.
i dont know sir if is hard to edit or not. but you understand the script better.
i hope you can help me with this little edit.
thanks sir and thanks again to post this perfect filemanager for us.

**Comment by wmerfalen** [comment]
Hi @addoloratacalabresi . I have implemented this exact feature for you under my forked version of this repo. 
https://github.com/wmerfalen/tinyfilemanager
@prasathmani If you would like this feature in your project, please let me know and I can submit a PR. 

Have a good day. 
Happy hacking :).

--William Merfalen

**Comment by prasathmani** [comment]
@wmerfalen  thanks for your support. track the ticket here: https://github.com/wmerfalen/tinyfilemanager/commit/bf4c1589109afea98f63060fed8683feec55a768
