### ISSUE TITLE
Fatal error: under PHP 8.0.11

### ISSUE THREAD

**Issue by ozgurkazancci** [prasathmani/tinyfilemanager#651]
Hi and many thanks for such a great tool! Truly useful.

I'd just like to report you that, whenever I'm trying to open/view a .txt file, I receive the following PHP error;

"Fatal error: Uncaught TypeError: log(): Argument #1 ($num) must be of type float, string given in tinyfilemanager.php:2442

Stack trace: #0 tinyfilemanager.php(2442):
log() #1 tinyfilemanager.php(1545): fm_get_filesize() #2 {main} thrown in tinyfilemanager.php on line 2442

Please note that I have all recommended/needed PHP extensions installed and they're already active. 

TinyFileManager ver: 2.4.3

Any idea would be much appreciated.
Best,
Özgür.

**Comment by Langlais115** [comment]
I can't reproduce the issue with 2.4.8 and PHP8.1
