### ISSUE TITLE
Is it possible if every single user have max quota in their directory?

### ISSUE THREAD

**Issue by nopal98** [prasathmani/tinyfilemanager#658]
I have 12gb in my shared hosting. Let's say that User A only have 3Gb quota in my directory. If user A overlimit quota storage (>3Gb), he can't upload in my Directory. It's Possible, dude?

**Comment by prasathmani** [comment]
currently it is not supported, in bottom there is total size of the files in directory, you can use that to validate the users limits.

**Comment by SithX** [comment]
Is the implementation of this function planned? I'm very interested
