### ISSUE TITLE
<b>Notice</b>:  ob_flush(): failed to flush buffer. No buffer to flush in <b>/www/tinyfilemanager.php</b> on line <b>2785</b><br />

### ISSUE THREAD

**Issue by ghost** [prasathmani/tinyfilemanager#664]
hi, where every download files, in the end of line will containt these script ? how to solve?
<b>Notice</b>:  ob_flush(): failed to flush buffer. No buffer to flush in <b>/www/tinyfilemanager.php</b> on line <b>2785</b><br />

![image](https://user-images.githubusercontent.com/54843055/141682714-31296600-7234-4ec6-a10d-5c8601fe81c2.png)

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
