### ISSUE TITLE
button cannot be clicked because these JS files cannot be loaded

### ISSUE THREAD

**Issue by AdminHcat** [prasathmani/tinyfilemanager#667]
button cannot be clicked because these JS files cannot be loaded：
https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.slim.min.js
https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js

Chinese users cannot access Google's website in China for well-known reasons

It should be changed to cdnjs.cloudflare.com or cdn.bootcdn.net or other Global CDN

Thank

**Comment by rampageX** [comment]
Try my versioin:

https://github.com/rampageX/tinyfilemanager-chs

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
