### ISSUE TITLE
Danish translation Tiny File Manager

### ISSUE THREAD

**Issue by helmuthm** [prasathmani/tinyfilemanager#669]
[translation.json.zip](https://github.com/prasathmani/tinyfilemanager/files/7576901/translation.json.zip)

the attached translation.json.zip includes the Danish translation

I also have sent an e-mail with the same subject ;-)

**Comment by helmuthm** [comment]
` {
      "name": "Dansk",
      "code": "da",
      "translation": {
        "AppName": "Tiny File Manager",
        "AppTitle": "Fil behandler",
        "Login": "Log ind",
        "Username": "Brugernavn",
        "Password": "Kodeord",
        "Logout": "Log ud",
        "Move": "Flyt",
        "Copy": "Kopier",
        "Save": "Gem",
        "SelectAll": "Vælg alt",
        "UnSelectAll": "Fravælg alle",
        "File": "Fil",
        "Back": "Tilbage",
        "Size": "Størrelse",
        "Perms": "Tilladelser",
        "Modified": "Ændret",
        "Owner": "Ejer",
        "Search": "Søg",
        "NewItem": "Ny",
        "Folder": "Folder",
        "Delete": "Slet",
        "Rename": "Omdøb",
        "CopyTo": "Kopier til",
        "DirectLink": "Direkte link",
        "UploadingFiles": "Uploader filer",
        "ChangePermissions": "Skift tilladelser",
        "Copying": "Kopierer",
        "CreateNewItem": "Opret ny",
        "Name": "Navn",
        "AdvancedEditor": "Avanceret tekstbehandler",
        "RememberMe": "Husk mig",
        "Actions": "Handlinger",
        "Upload": "Upload",
        "Cancel": "Fortryd",
        "InvertSelection": "Inverter valgte",
        "DestinationFolder": "Destinationsfolder",
        "ItemType": "Filtype",
        "ItemName": "Filnavn",
        "CreateNow": "Opret nu",
        "Download": "Download",
        "Open": "Åbn",
        "UnZip": "Pak ud",
        "UnZipToFolder": "Pak ud til folder",
        "Edit": "Rediger",
        "NormalEditor": "Normal tekstbehandler",
        "BackUp": "Sikkerhedskopier",
        "SourceFolder": "Kildefolder",
        "Files": "Filer",
        "Change": "Ændre",
        "Settings": "Indstillinger",
        "Language": "Sprog",
        "MemoryUsed": "Hukommelse brugt",
        "PartitionSize": "Partitionsstørrelse",
        "ErrorReporting": "Fejlrapportering",
        "ShowHiddenFiles": "Vis skjulte filer",
        "Full size": "Fuld størrelse",
        "Help": "Hjælp",
        "Free of": "Fri fra",
        "Preview": "Forhåndsvisning",
        "Help Documents": "Hjælpedokumenter",
        "Report Issue": "Rapporter problem",
        "Generate": "Generer",
        "FullSize": "Fuld størrelse",
        "FreeOf": "Fri fra",
        "CalculateFolderSize": "Beregn folderstørrelse",
        "ProcessID": "Proces ID",
        "Created": "Oprettet",
        "HideColumns": "Skjul kolonner",
        "Folder is empty": "Folder er tom",
        "Check Latest Version": "Se efter opdateringer",
        "Generate new password hash": "Generer ny adgangskode-hash",
        "You are logged in": "Du er logget ind",
        "Login failed. Invalid username or password": "Log ind mislykkedes. Ugyldigt brugernavn eller kodeord",
        "password_hash not supported, Upgrade PHP version": "password_hash understøttes ikke, opgrader PHP-version"
      }
   },`

**Comment by prasathmani** [comment]
@helmuthm thanks for sharing, will check.

**Comment by EV-soft** [comment]
I prefer #569
