### ISSUE TITLE
Provide version tags for Docker image

### ISSUE THREAD

**Issue by ssams** [prasathmani/tinyfilemanager#672]
At the moment Docker images are only available using a single `master` tag on https://hub.docker.com/r/tinyfilemanager/tinyfilemanager. 

It would help deploying this via Docker when the typical version tags would be provided on the images to select a stable version (as the application itself already seems to have a proper version number, as indicated in the footer of the page and the related constant in its source). E.g.:
* `tinyfilemanager/tinyfilemanager:2.4.3` -> version 2.4.3
* `tinyfilemanager/tinyfilemanager:2.4` -> latest version from the 2.4.x line
* etc.
 
Having more of these tags available certainly helps, but at least one of the example variants would already greatly improve usability as you can rely on getting a known version when you start it (instead of suddenly receiving an update which could break a config, etc.).

Also note that the `master` tag is somewhat unusual for Docker, typically the default tag would be `latest` (selected by default when specifying no tag by most/all? container engines).

**Comment by prasathmani** [comment]
@ssams  can you share the docker action configuration with you suggestions, so i can update the github actions.

**Comment by prasathmani** [comment]
@ssams thanks for the PR.
