### ISSUE TITLE
Doesn't Extracts ZIP File

### ISSUE THREAD

**Issue by skrlance** [prasathmani/tinyfilemanager#676]
On the description it's written:

Ability to compress, extract files (zip, tar).

But, I don't see any option to extract ZIP or TAR files? How to do it?

Thanks.

**Comment by prasathmani** [comment]
![image](https://user-images.githubusercontent.com/11345598/144564866-ec70db09-0071-4f2a-a646-fe86d83b3866.png)

@skrlance You can find the option at the bottom toolbar on the page. PHP server should support, zip/tar.

**Comment by skrlance** [comment]
That option will only compress and won't extract.

**Comment by prasathmani** [comment]
![image](https://user-images.githubusercontent.com/11345598/144565972-6eab2f5f-cb93-4364-86f8-973e12070370.png)
you can find extract option on details page.

**Comment by skrlance** [comment]
I don't see details page or such options anywhere? Please check these screenshot. It's nowhere!!

```
https://ibb.co/q7TNfg7
https://ibb.co/wL9ZNKJ
```
Please help me with this!!

**Comment by skrlance** [comment]
I am so sorry! I should have download 2.4.6 directly from code. There was old version kept on releases. My apologies!

Regards
