### ISSUE TITLE
Recommendations for the dark theme.

### ISSUE THREAD

**Issue by SuperJumpBros** [prasathmani/tinyfilemanager#678]
I know this might not be a big concern, but in my opinion the dark theme should look a bit better. Right now it has style inconsistencies and other annoying things. I'll give some examples below.

![image](https://user-images.githubusercontent.com/54546501/145334408-b4fd6789-616c-4101-9e02-5764309a03dd.png)
![image](https://user-images.githubusercontent.com/54546501/145334721-1b61054f-10ea-4139-8c7b-17ac42a59960.png)

- Inconsistent text color (sometimes green, sometimes white)
- White on black where there should be a more grayish (as shown by the text background for folder / disk sizes, and table intersections)
- White checkboxes on a black background
- And obviously, the text box at the top right.

For a new update, I'd recommend ditching the green text. It looks okay, but in my opinion, the dark theme should look a bit more like a modern website. Bluish black, like the dark GitHub or Discord background. Thanks for reading, and I hope to see some of these changes in a future version. Cheers!

**Comment by prasathmani** [comment]
latest version improved lot on dark theme
