### ISSUE TITLE
<meta name="robots" content="noindex, nofollow">

### ISSUE THREAD

**Issue by alecos71** [prasathmani/tinyfilemanager#68]
Many people put your app in public folders exposing themselves to possible hacker attacks ... because without a specific directive Google and other search engines index your app that appears in search results ... my idea is to use an html meta tag that prevents any possible indexing ...

`<meta name="robots" content="noindex, nofollow">`

**Comment by prasathmani** [comment]
@alecos71  thanks for your valuable inputs.
