### ISSUE TITLE
Folder lists not fully rendered

### ISSUE THREAD

**Issue by esyede** [prasathmani/tinyfilemanager#680]
![Screenshot_5](https://user-images.githubusercontent.com/10582583/145691988-bf997060-11bf-4206-aaed-5be18ec9cde4.png)

Any advice?

**Comment by prasathmani** [comment]
make sure you are not added php in `$exclude_items`

**Comment by esyede** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/10582583/145711755-eae61379-0dc1-4751-bbd5-a5a9aa718080.png)

No, of course not 😃 . Any other advice?

**Comment by esyede** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/10582583/145711945-ba8c2474-5728-4a85-bb62-9e48d34cd974.png)

For additional information:
Last visible row is also missing the details, and this happens only in the parent (outer) folder, subfolders are working fine

**Comment by michael-milette** [comment]
Hi @esyede ,

I was unable to reproduce the issue. Have you tried it with the latest version of TinyFileManager?

If it still happens, how long exactly does it take for the problem to occur and how many items are missing? If it is longer than 30 seconds, you may need to increase the PHP timeout.

Another thing you can try is to turn off the display of folder size in the settings. This skips summing up all the files in the directory tree resulting in your files listings appearing much quicker.

Best regards,

Michael Milette

**Comment by esyede** [comment]
Hi Mike.

I don't have access to the server anymore unfortunately
Tried tinyfilemanager to all my other servers but still I can't reproduce that behaviour, sorry :(

Regards,

Suyadi

**Comment by prasathmani** [comment]
thanks @michael-milette  and @esyede for the update.
