### ISSUE TITLE
Modal "New Item" opens only if "Upload" dialog is opened first

### ISSUE THREAD

**Issue by devnull4242** [prasathmani/tinyfilemanager#689]
I use Tiny File Manager on different systems and on some systems it works fine. Thank you for the great software.

But on one system (only http:// and not https://) (free provider https://bplaced.net, PHP 8) i have got the issue that if i see the listed folders and files and i click on "New Item" nothing does happen. But if i first click on "Upload" and then i click on "New Item" all works fine. Modal for files/folder is opened and i can create a file or a folder.

Perhaps the problem is in line 3391. Sorry i can not insert the line in this post.

**Comment by michael-milette** [comment]
Hi @devnull4242 ,

I noticed recently that TinyFileManager is not fully PHP 8 compatible yet. Your issue might be related. Try it out with the recently released version to see if that helps (though still not fully PHP 8 yet).

Very happy to see that @prasathmani has been busy applying fixes in the last week or so. 👍 

Best regards,

Michael Milette
