### ISSUE TITLE
This page is trying to load scripts from unauthenticated sources

### ISSUE THREAD

**Issue by alecos71** [prasathmani/tinyfilemanager#69]
Chrome reports this...

**_This page is trying to load scripts from unauthenticated sources_**

and here you can see how appears your app on Firefox and Chrome...

![fm](https://user-images.githubusercontent.com/9997666/46869907-76fde100-ce2d-11e8-8b72-968e3f801c96.png)

**Comment by wmerfalen** [comment]
@alecos71 ah, i see what they are now... if you look in the source code of the script and search for things like `<script`, you'll find that the script is pulling from sources like cloudfare, jquery, bootstrap, etc. Not sure how I feel about that given that the philosophy of this project seems (at least to me) that it should be an all-in-one solution with very little/no deps.

**Comment by alecos71** [comment]
With previous version this did not happen... the fm did load any kind of script... with this new version fm cannot load the remote scripts (blocked by Firefox and Chrome...) I'm still using the previous version since I test drive your new version and your fm didn't work properly...

**Comment by alecos71** [comment]
> 
> 
> @alecos71 I can look into it a bit more if you let me know what went wrong with my version?
> 
> Also, can you verify that the blocked scripts are the CDN URL's in the fm source code?

Chrome doesn't let me know what are the script blocked, limit itself to say

**_This page is trying to load scripts from unauthenticated sources_** 

![tinyfilemanager-master-10 10 2018](https://user-images.githubusercontent.com/9997666/46943032-00502600-d06f-11e8-8d1d-92ba782ab88b.png)

**Comment by alecos71** [comment]
Found the guilty...

http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css

should be:

https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css

Chrome and Firefox cannot load remote urls if they aren't in https...

**Comment by alecos71** [comment]
Confirmed!!! Must be: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css

the resources must be in https...

**Comment by wmerfalen** [comment]
@alecos71 I just committed to my master branch a version of the tinyfilemanager that serves all cdnjs urls over https.
