### ISSUE TITLE
fm_get_filesize expects a float but string given.

### ISSUE THREAD

**Issue by jellehak** [prasathmani/tinyfilemanager#703]
First of all great tool. I got a small error when running with PHP build in server on line 1546: ```fm_get_filesize($filesize)```

Argument #1 ($num) must be of type float, string given.

Solved by removing the line.

**Comment by michael-milette** [comment]
Hi @jellehak ,

Can you still reproduce this in the current version of TinyFileManager? If so, could you please provide information on how to reproduce the issue?

Best regards,

Michael Milette

**Comment by jellehak** [comment]
Yes is works with the current version indeed.
