### ISSUE TITLE
Upload a folder structure

### ISSUE THREAD

**Issue by Slowrider1969** [prasathmani/tinyfilemanager#717]
I am trying to upload a folder structure, with subfolders, under an existing folder.  It appears that since all folders are empty, it will not process.  Is there a way to upload a folder structure so that my researchers can then upload their files into the appropriate folder or subfolder.  Maybe I am missing something pretty obvious.
Richard

**Comment by prasathmani** [comment]
try to upload the zip file with your folder structure with sub folder and files.  then extract the zip will work.

**Comment by Slowrider1969** [comment]
Yes, I just figured out the same yesterday.  Create the folder structure on my computer using explorer.  Highlight the file structure and create a zip file.  The zip can then be uploaded and then unzipped to create the folder structure.  Since the folders are empty the file is relatively small and does not bump the file size limit.   If you would happen to include some larger files in the zip, then need to check your file size and time out limits.   Thanks.
