### ISSUE TITLE
[tinyfilemanager.github.io] 

### ISSUE THREAD

**Issue by simon511000** [prasathmani/tinyfilemanager#72]
There is a 404 error when we click on "Docs"
![30bac96d-83e5-4616-90f4-8c3fa08a663c](https://user-images.githubusercontent.com/31013205/47145425-055ce180-d2ca-11e8-9ca7-fd3674942eb7.gif)

**Comment by prasathmani** [comment]
@simon511000 , docs under development, will get soon.

**Comment by simon511000** [comment]
ok thank you

**Comment by prasathmani** [comment]
fixed - https://tinyfilemanager.github.io/docs/
