### ISSUE TITLE
Excluding File Extensions for upload

### ISSUE THREAD

**Issue by aman-sharma3108** [prasathmani/tinyfilemanager#731]
How can we exclude a set of file extensions for upload instead of including them?

I tried changing 

![image](https://user-images.githubusercontent.com/89823422/155035582-8bf9a60b-6018-43b8-bb23-6d2788c6b600.png)

and 
![image](https://user-images.githubusercontent.com/89823422/155035617-f75c5724-e444-47f9-9c49-27705141786d.png)

but it didn't work.

**Comment by devnull4242** [comment]
I think it is not possible. Also it is a high risk if you forget to exclude .php ;-)
