### ISSUE TITLE
can not upload large file when using 2.4.7 with docker

### ISSUE THREAD

**Issue by flymaxty** [prasathmani/tinyfilemanager#733]
Hi,
I'm using tinyfilemanager 2.4.7 with docker, and can not upload large file.
It only shows "opps Try again!" with “√“.
I also changed max_upload_size_bytes on config.php to 10485760, and nothing changed.

![image](https://user-images.githubusercontent.com/6258335/155676064-ef7758a2-6215-43df-aefe-dfd361792d3b.png)

![image](https://user-images.githubusercontent.com/6258335/155676133-b1e08f59-4687-437f-9da6-c3082672a0dc.png)

**Comment by flymaxty** [comment]
@prasathmani Thanks for your reply!

I also tried native way to run tinyfilemanager, and PHP showed a warning message:
PHP Warning:  POST Content-Length of 10001089 bytes exceeds the limit of 8388608 bytes in Unknown on line 0

I'm a freshman on PHP.
Is that mean I still need change php.ini post_max_size on docker container, even 2.4.7 using file chunks?

Here's the console log, if I don't misunderstand.
[native_run.log](https://github.com/prasathmani/tinyfilemanager/files/8140080/native_run.log)
[docker_run.log](https://github.com/prasathmani/tinyfilemanager/files/8140081/docker_run.log)

**Comment by flymaxty** [comment]
> can you attached console.log error as well

**Comment by pjygithub** [comment]
maybe you need change a new dropzone.min.js
