### ISSUE TITLE
Duplicate config variable "$directories_users"

### ISSUE THREAD

**Issue by guretalde** [prasathmani/tinyfilemanager#734]
Variable "$directories_users" is duplicated in "tinyfilemanager.php".

Line 44 and line 73.

**Comment by prasathmani** [comment]
thanks for reporting, will fix it in next commit

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
