### ISSUE TITLE
Name too long

### ISSUE THREAD

**Issue by anizourida** [prasathmani/tinyfilemanager#739]
You have to enhance the file uploader from url to get the correct file name.

Ex website/file.mp4?login=10&date=1725383y3739

The file name must be just 
file.mp4 
not the whole 
file.mp4?login=10&date=1725383y3739
(If query parameters are long the file name will be long)

**Comment by dotcomUNDERGROUND** [comment]
I am also having this issue.

file.jpeg?bla=blebleeble&bloo=bloobloo gets saved with all URL parameters in filename.

**Comment by prasathmani** [comment]
[fixed](https://github.com/prasathmani/tinyfilemanager/commit/610cea8ecd8cefcd8b72efedfb8da7b0b9a66857)
