### ISSUE TITLE
addition of a translation system

### ISSUE THREAD

**Issue by simon511000** [prasathmani/tinyfilemanager#74]
It would be really cool to be able to add translations to tinyfilemanager

**Comment by prasathpree** [comment]
@simon511000  Multiple language option was there in initial releases, later it was removed due to dependencies with many language files.

**Comment by simon511000** [comment]
I was thinking more about storing languages in arrays. => no dependencies, no other file.
What do you think ?

**Comment by simon511000** [comment]
like
```
<?php
$lang = "fr";
$en = ["home"=>"home","login"=>"login"];
$fr = ["home"=>"accueil","login"=>"identifiant"];

switch($lang){
  case "fr":
    $translate = $fr;
  break;
  default:
    $translate = $en;
}

echo $translate["login"];
echo $translate["home"];
```

**Comment by simon511000** [comment]
nice thank you very much

**Comment by prasathmani** [comment]
@simon511000 multi language option available now, check the latest [release](https://github.com/prasathmani/tinyfilemanager/releases)

**Comment by simon511000** [comment]
Niiiice Thank you very much :D
