### ISSUE TITLE
 archived .zip, but where. ???

### ISSUE THREAD

**Issue by The-Exterminator** [prasathmani/tinyfilemanager#741]
Where can I find the file after extracting it to .zip. ???
it is not on my server either, but it writes it is archived
![billede](https://user-images.githubusercontent.com/6666710/156928518-0aa26160-c738-4296-a6e2-5764004298c0.png)
and you can make a "download button" on the far right when it writes it is made. ???

**Comment by Simi5599** [comment]
Hi,
The file should be located into the same directory of the file you zipped.
