### ISSUE TITLE
Can download only one file at a time / cannot browse while downloading

### ISSUE THREAD

**Issue by zkrx** [prasathmani/tinyfilemanager#744]
I can only download one file at a time. If I download a file, I can't browse tinyfilemanager anymore. If I try to click anywhere while downloading a file (or if I try to download a second file), the action will be queued until the download finishes. However, if I start a new private window while downloading a file, I can simultaneously download another file/browse tinyfilemanager. That's why I think this may be related to session management. See:
https://stackoverflow.com/questions/1610168/downloading-files-with-php-only-downloading-one-at-a-time

**Comment by phifogg** [comment]
+1 - download of multiple files would be great!
