### ISSUE TITLE
Suggestion to add parameters for Dropzone and max upload size

### ISSUE THREAD

**Issue by smefa** [prasathmani/tinyfilemanager#75]
Perhaps it would be nice to have the maxFilesize and timeout options for Dropzone already in the script. I had to do some searching before I understood how the max upload size worked.

        Dropzone.options.fileUploader = {
			maxFilesize: 500,
			timeout: 600000,
            init: function () {
                this.on("sending", function (file) {
                    let _path = (file.fullPath) ? file.fullPath : file.name;
                    document.getElementById("fullpath").value = _path
                }).on("success", function (res) {
                    console.log('Upload Status >> ', res.status);
                })
            }
        }

**Comment by smefa** [comment]
Dropzone 5.5 is also available
https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.0/min/dropzone.min.js

**Comment by prasathmani** [comment]
Timeout and new version of dropzone cdn url are updated. maxFilesize will depend upon server max upload file size,  so maxFilesize not added in dropzone configuration
