### ISSUE TITLE
$global_readonly not working

### ISSUE THREAD

**Issue by kc9ryt** [prasathmani/tinyfilemanager#753]
Hello,
I am running v. 2.4.7 and $global_readonly = true does not seem to be working with auth turned off.

**Comment by prasathmani** [comment]
@kc9ryt , check this #583

**Comment by shadowvfx** [comment]
Full disclosure, I'm an idiot. I followed the link to issue 583 and I don't understand what it's getting at. Why doesn't setting global_readonly to true make it....read only? I am not a PHP expert, but I want to share a collection of files with a local club and I want them to be able to access the file directories, but NOT have any kind of editing privileges. I just want them to view the documents and download. All the file management stuff I can handle via FTP.

**Comment by alex-reach** [comment]
This in not working for me either @prasathmani . Or are we doing something wrong?

**Comment by mrlawrencelam** [comment]
Yes, this feature is seriously missing.

I want only the Administrator to be able to manage files (requires login).

But for public users, don't need to log in. They can go directly to the file list but can't edit/delete/upload files.

I tried pointing to the link tinymanager.php?fm_usr=user&fm_pwd=user123 but this doesn't work.

How can public users bypass the login form?

**Comment by andymcca** [comment]
$global_readonly isn't currently referenced anywhere in the PHP file apart from the initial definition.

To get this to work I think you just need to change line 396 to the following -

define('FM_READONLY', ($use_auth && !empty($readonly_users) && isset($_SESSION[FM_SESSION_ID]['logged']) && in_array($_SESSION[FM_SESSION_ID]['logged'], $readonly_users)) || $global_readonly);

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
