### ISSUE TITLE
File set 0 bytes

### ISSUE THREAD

**Issue by crispa** [prasathmani/tinyfilemanager#754]
Hello,
I have my project in cpanel and after upload tinyfilemanger.php to storage cloud, after I access, file is seted to 0 bytes...
I change option $use_auth true or false but it's the same.
If I upload file in filemanager from cpanel, it wasn't uploaded.
If I create new file in filemanager in cpanel and past content of tinyfilemanager.php, I receive the error: "BAILOUT malware detected".
How can I resolve this situation?
I have cpanel version 100.0.11

Thank you.

**Comment by xenDE** [comment]
looks like a cpanel. ask there for "how to whitelist tinyfilemanager"

**Comment by prasathmani** [comment]
duplicate #273

**Comment by crispa** [comment]
Resolved.
Add file tinyfilemanager.php to ignore list at cpanel, in Imunify360.
Thank you everyone

**Comment by FransW5** [comment]
Solution:

Open tinyfilemanager.php in a text editor And

Replace All:
fm_redirect(FM_SELF_URL . '?p=' . urlencode(FM_PATH));

With:
$FM_PATH=FM_PATH; fm_redirect(FM_SELF_URL . '?p=' . urlencode($FM_PATH));
