### ISSUE TITLE
How to avoid false detection by Imunify360

### ISSUE THREAD

**Issue by hexclann** [prasathmani/tinyfilemanager#759]
Hello, I'm trying to use tinyfilemanager in a shared hosting environment. Cpanel has an antivirus, Imunify360 which is detecting the tinyfilemanager.php as a malware. There's no way to whitelist the file and the support is not willing to disable Imunify for my account. Is there any way I can use tinyfilemanager?

**Comment by prasathmani** [comment]
#273, #754

**Comment by crispa** [comment]
Add file tinyfilemanager.php to ignore list at cpanel, in Imunify360.

**Comment by FransW5** [comment]
Solution for cPanel firewall:

Open tinyfilemanager.php in a text editor And

Repace All:
fm_redirect(FM_SELF_URL . '?p=' . urlencode(FM_PATH));

With:
$FM_PATH=FM_PATH; fm_redirect(FM_SELF_URL . '?p=' . urlencode($FM_PATH));

**Comment by codedivinetech** [comment]
@FransW5 the solution you have mentioned is now obsolete. @prasathmani or @FransW5 Kindly Update With a newer solution on this thread

**Comment by FransW5** [comment]
> @FransW5 the solution you have mentioned is now obsolete. @prasathmani or @FransW5 Kindly Update With a newer solution on this thread

I tested on (cPanel 106.0.8 + cPGuard + imunify360 Malware scanner) and with the following replacement, solves the problem.

What hosting management system are you using?
What antivirus and firewall is running on your host?


```
Replace All:
fm_redirect(FM_SELF_URL . '?p=' . urlencode(FM_PATH));

With:
$FM_PATH=FM_PATH; fm_redirect(FM_SELF_URL . '?p=' . urlencode($FM_PATH));
```

**Comment by codedivinetech** [comment]
![image](https://user-images.githubusercontent.com/74067051/196252825-9080214b-1db3-41bd-8c2d-bd4a21f57aaf.png)
![image](https://user-images.githubusercontent.com/74067051/196253704-0c5415fe-5fec-4188-8e88-b77bb9beff38.png)


@FransW5 You can find the exact info on the above pics

**Comment by FransW5** [comment]
@codedivinetech 

Access to your host is required to check the issue!

**Comment by codedivinetech** [comment]
@FransW5 Please Msg me on telegram https://t.me/spartancinemax

**Comment by sohailsarwar101** [comment]
> @codedivinetech
> 
> I tested on (cPanel 106.0.8 + cPGuard + imunify360 Malware scanner) and with the following replacement, solves the problem.
> 
> What hosting management system are you using? What antivirus and firewall is running on your host?
> 
> ```
> Replace All:
> fm_redirect(FM_SELF_URL . '?p=' . urlencode(FM_PATH));
> 
> With:
> $FM_PATH=FM_PATH; fm_redirect(FM_SELF_URL . '?p=' . urlencode($FM_PATH));
> ```

Still the same issue even after replacing the mentioned code. (Cpanel with cPGuard). Any other suggestion please?
