### ISSUE TITLE
subdirectory search does not work

### ISSUE THREAD

**Issue by alex321test** [prasathmani/tinyfilemanager#76]
example - 
https://tinyfilemanager.herokuapp.com/Demo/index.php?p=Images
search does not work.

**Comment by prasathmani** [comment]
The search will work only on the current directory. it does not have a sub-directory search option.

**Comment by alex321test** [comment]
Current directory "\"
https://tinyfilemanager.herokuapp.com/Demo/index.php?p=
does work

Current directory -  "Images" 
https://tinyfilemanager.herokuapp.com/Demo/index.php?p=Images
search does not work.

**Comment by prasathmani** [comment]
Search files in sub-folders available in new release.

**Comment by PierreJURY** [comment]
Hello, 
Searching for it in subfolders no longer works.
Thanks
