### ISSUE TITLE
 Critical security Vulnerability 

### ISSUE THREAD

**Issue by ranjit-git** [prasathmani/tinyfilemanager#763]
Few high severity security vulnerability has been reported on huntr
https://www.huntr.dev/bounties/6-other-prasathmani/tinyfilemanager/
https://www.huntr.dev/bounties/7-other-prasathmani/tinyfilemanager/
https://www.huntr.dev/bounties/8-other-prasathmani/tinyfilemanager/
https://www.huntr.dev/bounties/9-other-prasathmani/tinyfilemanager/
https://www.huntr.dev/bounties/10-other-prasathmani/tinyfilemanager/

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
