### ISSUE TITLE
*directories_users* variable shows up twice.

### ISSUE THREAD

**Issue by fosley** [prasathmani/tinyfilemanager#765]
In _tinyfilemanager.php_, the variable _directories_users_ shows up on line 46, then again on line 75. I presume setting anything on 46 is ignored, since line 75 will just over-write it with an empty array. It's trivial to just delete one line, but it's probably better to have it that way be default.

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
