### ISSUE TITLE
turning off error_reporting is not a good idea...

### ISSUE THREAD

**Issue by alecos71** [prasathmani/tinyfilemanager#77]
Warnings or errors can help to discover bugs, if you turn off those we cannot help you to fix bugs...

if you want you can use this trick:

`$report_errors = false; // false = Turns off Errors, true = Turns on Errors`

```
if ($report_errors == true) {
  @ini_set('error_reporting', E_ALL);
  @ini_set('display_errors', 1);
} else {
  @ini_set('error_reporting', E_ALL);
  @ini_set('display_errors', 0);
}
```
 
This a safe mode to display errors... hope this helps...

**Comment by TigersWay** [comment]
> Warnings or errors can help to discover bugs, if you turn off those we cannot help you to fix bugs...

Which is fine while developing, but rather dangerous in production #40
