### ISSUE TITLE
HTML tag attribute quote error

### ISSUE THREAD

**Issue by alex-itboy** [prasathmani/tinyfilemanager#774]
https://github.com/prasathmani/tinyfilemanager/blob/a65f8ff8b5c5ab644a0d5ad0e8d7aa79d50c2a6f/tinyfilemanager.php#L2100

In this line the attribute data-sort is set to 
```html
data-sort=b-"<?php echo str_pad($filesize_raw, 18, "0", STR_PAD_LEFT); ?>"
```
the `b-` is outside the quote, should it be ?

**Comment by prasathmani** [comment]
fixed, thanks for reporting
