### ISSUE TITLE
unable to upload mp4 video

### ISSUE THREAD

**Issue by ebonyrod123** [prasathmani/tinyfilemanager#780]
site seems to always crash when I attempt to upload a video.

**Comment by prasathmani** [comment]
please check, you have write permission to upload files.

**Comment by oleksandr-omelchenko** [comment]
This could be a bug with dropzone.js. I have similar problem while uploading files because dropzone it tries to use http but not https.
![Screenshot_1](https://user-images.githubusercontent.com/18086156/167137187-55b83530-2946-41f7-9344-4acff9faaef7.jpg)

**Comment by oleksandr-omelchenko** [comment]
> @oleksandr-omelchenko This seems more an issue with the server tinyfilemanager is served on. You probably need a certificate on the server or you would need to change your browser configuration to allow uploading to non-https endpoints.

No. You're wrong. This is an issue with $is_https detection in tinyfilemanager. I've described it here: https://github.com/prasathmani/tinyfilemanager/issues/229#issuecomment-1119627904
