### ISSUE TITLE
How to use advanced editor offline?

### ISSUE THREAD

**Issue by oresteafrica** [prasathmani/tinyfilemanager#781]
Advanced editor is only available when online, I tried to replace all external files calls (js, css, etc..) with internal calls by uploading all external files but it did not succed, I do not know what is missing.

**Comment by prasathmani** [comment]
add following files 

- jQuery
- Bootstrap
- Font Awesome
- Highlight js
- ace js
- DropZone js
- ekko-lightbox js
- DataTable js

**Comment by oresteafrica** [comment]
Thanks
