### ISSUE TITLE
upload of large files (1 GB+)

### ISSUE THREAD

**Issue by phifogg** [prasathmani/tinyfilemanager#787]
Hi,
i have some issues with uploading of larger files. Smaller files work flawless.
Large files (1 GB+) seem to work fine from a client side, the upload takes approx as long as I would expect it to take, but the files arriving on the server are either way too small (i.e. less than 5 MB) or not existent at all.
How can I help find the root cause of this?
Thanks

**Comment by phifogg** [comment]
as some form of detail, I am running 2.4.7 of tinyfilemanager on a debian based linux host.

**Comment by vyv2000** [comment]
uploading of larger files < 3M.         use docker

**Comment by Langlais115** [comment]
I can't reproduce the issue on 2.4.8...
If you are using Nginx, make sure to add **client_max_body_size 2G;** in the **http** section of your **nginx.conf**.
and in your **php.ini**
**post_max_size = 2G
upload_max_size = 2G**
