### ISSUE TITLE
how can multiple clients use the tinyfilemanger at the same time?

### ISSUE THREAD

**Issue by mut9bu** [prasathmani/tinyfilemanager#789]
Hello
I want that multiple users can use the same php page at the same time. But User-1 can connect to Rootpath-1, and at the same time User-2 can connect to another Rootpath-2.  at the same time . Is that possible? If yes how? I'm new in php, so i couldn't find a solution yet. Would be happy if someone can help.

**Comment by prasathmani** [comment]
```php
$auth_users = array(
    'user1' => '...',
    'user2' => '...'
);

$directories_users = array('user1' => 'folder-1', 'user2' => 'folder-2');
```

**Comment by mut9bu** [comment]
Thanks for the answer. Two additional questions:
1) How should we define the general $root_path variable in this case? Should we comment it out? (because each user will have its own root path.??)
2) In my usecase each user will connect to a different production machines shared folder (user1 --> //10.92.114.73/E$, user2 -->//10.92.114.75 ...,.)
In order to connect to this remote network paths, I am using the 'net use' command (for User1):
exec('net use "'.$root_path_user1.'" /user:"'.$user_M.'" "'.$password_M.'" /persistent:no');
opendir($root_path_user1);

If I have for each user another $root_path_userX, then I have to query the logged in username and connect then to the related $root_path_userX. How can I query the user that is logged on? Accordingly I want to write:

switch ($logged_user) {
  case user1:
    $root_path=$root_path_user1
    break;
  case user2:
    $root_path=$root_path_user2
    break;
  case user3:
    $root_path=$root_path_user3
    break;
    ...
exec('net use "'.$root_path.'" /user:"'.$user_M.'" "'.$password_M.'" /persistent:no');
opendir($root_path);
}

**Comment by mut9bu** [comment]
Thanks for the quick support. Tinifilemanager is realy the best web based file manager.
