### ISSUE TITLE
Advanced editor 

### ISSUE THREAD

**Issue by xylle** [prasathmani/tinyfilemanager#799]
Helo, i have some issue with the advanced editor : 
When i open some file i have a 404 :
- txt
- js
- md
Thanks for your job.

**Comment by paolostefanucci** [comment]
> https://cdnjs.cloudflare.com/ajax/libs/ace/1.7.0/ace.js

better the min version:
https://cdnjs.cloudflare.com/ajax/libs/ace/1.9.6/ace.min.js
