### ISSUE TITLE
noob: How do I set $root_path = '/';

### ISSUE THREAD

**Issue by alcatraz-zz** [prasathmani/tinyfilemanager#800]
Hey!

This is a simple question. I'd like to set the root_path to my actual root directory. Not a subfolder. Default is /www which I don't need to explore. 

Setting
$root_path = '/';
just ends in an error.

What am I doing wrong?

Thanks for reading and commenting.

**Comment by prasathmani** [comment]
`/etc/www` or `/usr/home/`

**Comment by alcatraz-zz** [comment]
> 

I tried both and get errors that they don't exist. So weird. Unable to explore all the directories. tinyfilemanager.php is in /www and $_SERVER['DOCUMENT_ROOT'] for me just opens /www with no ability to go to other important directories through the web interface.

I really appreciate the help though. It's a very nice file explorer. I'm on OpenWRT 19.7 by the way.

**Comment by eyalsch** [comment]
try
$root_path = '/.';
