### ISSUE TITLE
PHP "divide by zero" error when unzipping 0 byte (very small) .zip files

### ISSUE THREAD

**Issue by steiner2004** [prasathmani/tinyfilemanager#803]
The problem arises when calculating compression rate to show message in the interface (view attached image).
Here is the offending code line (1674):
`Compression: <?php echo round(($total_comp / $total_uncomp) * 100) ?>%<br>`

https://github.com/prasathmani/tinyfilemanager/blob/50ccd29623becd216f313bbea292ed7c0dc56d5c/tinyfilemanager.php#L1674

Probably you can write something like:
`Compression: <?php echo round(($total_comp / max($total_uncomp, 1)) * 100) ?>%<br>`

Thanks
![tfm](https://user-images.githubusercontent.com/108336816/176160895-60a88a46-bdc6-46f7-9d6d-89f6a8317407.png)

**Comment by prasathmani** [comment]
@steiner2004, thanks for the input.
