### ISSUE TITLE
SECURITY Demo version

### ISSUE THREAD

**Issue by we-sell-bags** [prasathmani/tinyfilemanager#810]
this CVE site says there are CVE errors. as far as 2.4.6
https://cve.report/software/tinyfilemanager_project/tinyfilemanager

your "demo" on github is showing version 2.4.0

also  can you display your current version some place.

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
