### ISSUE TITLE
directories structure not working & upload many file will stuck & file size incorrect

### ISSUE THREAD

**Issue by phken91** [prasathmani/tinyfilemanager#824]
hi,
using this app with docker, but during testing, i facing 3 issues
1. bulk upload with multiple directories but in the end all files is staying on file root, same issues with #755 
2. if upload many file, after seldom file then upload will stuck and not continue any more
3. upload single zip file(100mb +-) show successful, but during uncompressed will getting error

for `1.` said 2.4.6 work fine but i can't found the version on docker hub or i need to build my self?

example directories tree
```
├── config.php
├── docker-compose.yml
└── web
    ├── header.php
    ├── images
    │   ├── logo.jpg
    │   ├── b4.jpg
    │   ├── b5.jpg
    │   ├── m.jpg
    │   └── title_ico.jpg
    ├── index.php
    └── js
        ├── config.js
        ├── function.js
        ├── function2.js
        ├── hark.js
        ├── login.js
        ├── mainTab.js
        ├── mock.js
        ├── register.js
        └── validation.js
```

**Comment by WolfgangDpunkt** [comment]
I can confirm the bug, unfortunately this makes the 2.4.7 version unsuitable for (me) everyday use. I am looking forward to the fix. :-)

**Comment by TheIronFlo** [comment]
Works in 2.5.0
