### ISSUE TITLE
Skipping login form for public users (but Admininstrator needs to log in to manage files)

### ISSUE THREAD

**Issue by mrlawrencelam** [prasathmani/tinyfilemanager#825]
What I want:

1) The Administrator must log in to manage files.

2) Public users can only VIEW and DOWNLOAD files. They can't manage files.

3) Public users DO NOT need to log in (skip the login form). They can go directly to the file list.

I tried pointing to the URL */tinyfilemanager.php?fm_usr=user&fm_pwd=user123 but it didn't work.

**Comment by lordzpipo** [comment]
hi @mythsmith , 
In your situation, it would be preferable to have a different page where the file is shown or listed to allow for public download.

**Comment by mrlawrencelam** [comment]
Thanks for the hint.

I have just duplicated the script and renamed it view.php. I turn auth to OFF. But viewers, when arriving at the main file list, have the power to manage files. I guess I have to manually remove the codes for DELETE, RENAME, UPLOAD , SETTING etc. I wonder why users still have the power to manage files when global read-only is turned ON.
