### ISSUE TITLE
can help me

### ISSUE THREAD

**Issue by YinHeng89** [prasathmani/tinyfilemanager#83]
Warning: is_file(): open_basedir restriction in effect. File(/home/www/htdocs/..) is not within the allowed path(s): (/tmp/:/home/www/htdocs/) in /home/www/htdocs/filemanager.php on line 749 
Warning: is_dir(): open_basedir restriction in effect. File(/home/www/htdocs/..) is not within the allowed path(s): (/tmp/:/home/www/htdocs/) in /home/www/htdocs/filemanager.php on line 751

**Comment by prasathmani** [comment]
mostly problem with folder path, try to host tinyfilemanager in different path and check.

**Comment by prasathmani** [comment]
It has been fixed in Release [2.2.0](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.2.0)

**Comment by YinHeng89** [comment]
thanks
