### ISSUE TITLE
How to know mailserver from my webserver?

### ISSUE THREAD

**Issue by Tieu-Mai-Nhi** [prasathmani/tinyfilemanager#830]
I used function mail() in PHP to send mail, and with Xampp I sent it successfully. But when I sent it from your web server, I did not receive mail.
With Xampp, I configure my email name and password to send Mail, but in the webserver, where?

I searched and they said on a web server with a built-in mail server

Hope to receive your answer soon,
Thank you.

**Comment by WebCrew** [comment]
You should ask your hosting provider, server provider about that info - it is different from hoster to hoster.

Good luck man ;)
