### ISSUE TITLE
Issue with image preview when configuring user specific directories

### ISSUE THREAD

**Issue by redherring917b** [prasathmani/tinyfilemanager#831]
### Discussed in https://github.com/prasathmani/tinyfilemanager/discussions/827

<div type='discussions-op-text'>

<sup>Originally posted by **redherring917b** July 26, 2022</sup>
Just wondering if this issue of not being able to preview images when configuring user specific directories is expected to be addresses in an upcoming release?  I've seen other discussions from users experiencing the same issue, and some mention of fixes, but I've been unable as of yet to properly sort any of those out.

Nice app by the way!  Just struggling with this one aspect right now.

Perhaps if not a new release that incorporates such a fix, maybe someone would be willing to provide me with their modified config file that sets user specific directories yet still allows image previews to function?

Thanks!</div>

**Comment by ANDOR360** [comment]
test this version, it fix the mini preview, the extended preview, the open link and de direct download for the images,
download this link and replace the .php files inside with de originals: https://grupoviamar.com/filemanager/config.zip
remember enter the config.php and change your domain path, the relative root and the absolute root, just like that:

$directories_users = array('admin'=> '/home2/grupoviamar/public_html/p/promociones'); (this is the root)

$relative_directories_users_host = array('admin'=> 'https://grupoviamar.com'); (this is the domain)

$relative_directories_users_without_host = array('admin'=> '/p/promociones'); (this is the link page where the user will have access but without the domain)

**Comment by redherring917b** [comment]
@ANDOR360 

Thanks!  Fantastic.  I'll give it a go.

**Comment by ANDOR360** [comment]
I optimized the code a little more and gave it more stability with all kinds of images and absolute image links, besides it is more clear now.
https://grupoviamar.com/filemanager/config2.0.zip

**Comment by redherring917b** [comment]
@ANDOR360

Even better.  Thanks again!  :)

**Comment by redherring917b** [comment]
@ANDOR360 

Hi again!  Sorry, but I was temporarily diverted to another task and am just getting back to this now.  Thanks so much again for what you've already provided as I can confirm that this is now in fact working as it should.  I do have a follow-up question though.

Below is a code snippet showing settings for just 2 users.  This works.  But what if I had a lot of users and I didn't want to have to explicitly set each user's configuration... would it be possible to use variables in these array-setting statements?  I've included my attempt at doing so, which does NOT work, just to try to explain what I mean.

**This works - explicitly setting each user's configuration:**

$directories_users = array(
'userA'=> 'E:\websitedata\www.mywebsite.com\web\tinyfilemanager\userfiles\userA',
'userB'=> 'E:\websitedata\www.mywebsite.com\web\tinyfilemanager\userfiles\userB'
);

$relative_directories_users_host = array(
'userA'=> 'https://www.mywebsite.com',
'userB'=> 'https://www.mywebsite.com'
);

$relative_directories_users_without_host = array(
'userA'=> '/tinyfilemanager/userfiles/userA',
'userB'=> '/tinyfilemanager/userfiles/userB'
);

**This does NOT work - trying to set the current user's configuration using variables:**

$directories_users = array(
$user => 'E:\websitedata\www.mywebsite.com\web\tinyfilemanager\userfiles\'.$user
);

$relative_directories_users_host = array(
$user => 'https://www.mywebsite.com'
);

$relative_directories_users_without_host = array(
$user => '/tinyfilemanager/userfiles/'.$user
);

Thanks in advance!

**Comment by ANDOR360** [comment]
Put a text like this: [[USERS]]  in a php file and name it master_conf.php and copy all the config code on it, and then make php to look for this text [[USERS]] on replace it with te array you want and then overwrite the config.php with all the data configuration dynamically.

**Comment by redherring917b** [comment]
So sorry, but my earlier post was due simply to not being terribly familiar with PHP syntax (it's not my historical language of choice).  While your suggestion is likely "better" @ANDOR360, I ended up simply looping through my SQL query in config.php, adding elements to the arrays as appropriate for my users and their directories.  Seems to work like a charm.

Thanks a lot for your reply.
