### ISSUE TITLE
Ctrl+S to save file in normal editor

### ISSUE THREAD

**Issue by AgentSmith0** [prasathmani/tinyfilemanager#835]
It would be nice to use Ctrl+S in the normal file editor to save the file, like in the advanced editor.

**Comment by JMcrafter26** [comment]
I can relate 🙌

**Comment by prasathmani** [comment]
[fixed](https://github.com/prasathmani/tinyfilemanager/commit/610cea8ecd8cefcd8b72efedfb8da7b0b9a66857)
