### ISSUE TITLE
New version detected even it's the latest

### ISSUE THREAD

**Issue by JMcrafter26** [prasathmani/tinyfilemanager#838]
This isn't a big bug,
But when checking for a new version, it shows a message to download the newest version, even if I am using the latest version.

**Comment by smalos** [comment]
How/where do you check for a new version?

**Comment by JMcrafter26** [comment]
Log in -> click the burger menu -> click on your account and then click on help.
There should be a [check for new version] button

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
