### ISSUE TITLE
Sort folders before files

### ISSUE THREAD

**Issue by fn-ix** [prasathmani/tinyfilemanager#84]
Hi!

Would it be possible to have an option for sorting folders before files whilst otherwise retaining the alphabetical order?

**Comment by carlsue** [comment]
me too
2.3.1 only admin like this

**Comment by orionseye** [comment]
i spent the whole day to understand some of the logic behind this 'easy' app .. and it's getting better and better..
first i scratched my head with the complex 'move' file proceedure, which actually resides in 'copy' function, and now scratching the head, behind the 'sorting' logic, which seems to be false by default, as i see from the comments.
who had this briliant idea, to sort files like that, when the whole world list everything FIRST by folder, then by file name (as default)?
![Clipboard02](https://user-images.githubusercontent.com/48511159/99583950-f4bd4f00-29ec-11eb-90ff-fba6b9b13503.jpg)

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
