### ISSUE TITLE
Idea From Easy Method of user creation

### ISSUE THREAD

**Issue by blacklovertech** [prasathmani/tinyfilemanager#844]
Hi ! I'm Janarthanan, a junior developer, I'm using this repo for my clients and Friends in order to deploy or share any thing through this project .

In that case , i have to goto  coding for everytime i used to create a New user . jus need a Add menu and listing them under admin .. Pls check out here [File gator](https://filegator.io)  
just a. Suggestion for Interaction .....

Since I am Student, i uses this for my Class Purpose kinda Subject wise Sharing with Frnd and Mates ....

Still everything is Well and Fine , But juz mine suggestion to person who doesn't know coding ....

**Comment by prasathmani** [comment]
@blacklovertech , thanks for sharing the suggestion, will consider future release
