### ISSUE TITLE
image preview does not work when it specifies a different root_path

### ISSUE THREAD

**Issue by yigitcevik** [prasathmani/tinyfilemanager#847]
I am giving the path to a different file for the directory path. However, when I do this, previews of the images do not work. The preview works only if $root_path = $_SERVER['DOCUMENT_ROOT'].

$use_auth = false;
$root_path = '/xampp/htdocs/website/images';
$root_url = '';

[Image1](https://raw.githubusercontent.com/yigitcevik/issues/main/preview1.png)
[Image2](https://raw.githubusercontent.com/yigitcevik/issues/main/preview2.png)

**Comment by prasathmani** [comment]
update `$root_url` accordingly to work. #329

**Comment by yigitcevik** [comment]
> update `$root_url` accordingly to work. #329

I've tried what you said and researched the problems and tried other solutions, but it's still the same. I tried to enter all kinds of root_url but it didn't work. I uploaded the files to hosting, the new root_path is as follows. What kind of a root_url do I need to write for this?

$use_auth = false;
$root_path = '/home/user/public_html/new/website/images';

**Comment by prasathmani** [comment]
I hope `$_SERVER['DOCUMENT_ROOT']` and `home/user/public_html` are pointing to same path.
```php
$root_path = $_SERVER['DOCUMENT_ROOT'].'/new/website/images';
$root_url = 'new/website/images';
```

Image preview will not working if `$root_path` will be outside of server document root
