### ISSUE TITLE
Redirection error (Please help!)

### ISSUE THREAD

**Issue by SithX** [prasathmani/tinyfilemanager#849]
Hello, I have recently installed a new installation on the Raspberry, using linux, but now it does not work for me. I have the following structure
/var/www/html/upload                /cloud (inside will have the files)
there is the index.php
but when I try to access it returns me to the root domain.

domain/?p=

returns me to the root of the domain. The only way to make it work is to put the php index in: /var/www/html/index.php
but no work in /var/www/html/upload/index.php

$root_path = '/var/www/html/upload';
$root_url = 'files/cloud';

**Comment by SithX** [comment]
it say me in all moments 
https://aerialtraining.ddns.net/upload/

**Comment by YsrMe** [comment]
Hello!
i faced this problem before & solved it by:

Changing:
$root_url = '';

To:
$root_url = '/var/www/html/upload';

Good luck...

**Comment by SithX** [comment]
Not run, only run when index.php is in /var/www/html


De: Yaser ياسر ***@***.***>
Enviado el: domingo, 4 de septiembre de 2022 7:31
Para: prasathmani/tinyfilemanager ***@***.***>
CC: Eduardo ***@***.***>; Author ***@***.***>
Asunto: Re: [prasathmani/tinyfilemanager] Redirection error (Please help!) (Issue #849)


Hello!
i faced this problem before & solved it by:

Changing:
$root_url = '';

To:
$root_url = '/var/www/html/upload';

Good luck...

**Comment by SithX** [comment]
I have tried everything even in the NGINX configuration

**Comment by SithX** [comment]
I have found a solution and it works. Using "visual studio" code to edit the file. I have replaced everything in the code that says '?p=' to '/upload?p='
And in the ($root_url = 'upload';)
Which is the subfolder where I have the code and within it the subfolders with the documents.
Thanks all the same.
