### ISSUE TITLE
Renaming folders?

### ISSUE THREAD

**Issue by redherring917b** [prasathmani/tinyfilemanager#859]
### Discussed in https://github.com/prasathmani/tinyfilemanager/discussions/858

<div type='discussions-op-text'>

<sup>Originally posted by **redherring917b** September 20, 2022</sup>
Hi there.

I find myself unable to rename an existing folder.  I had a similar issue with renaming files, until I realized that I had to add to my allowed list of $allowed_file_extensions in the config.php file that I'm using.  But allowing extensions wouldn't apply to folders, obviously.  Any thoughts on how to successfully rename a folder?

**EDITED**: To perhaps be clearer, when attempting to rename a folder I'm just getting the "Error while renaming from [oldname] to [newname]" message, so it would seem to be failing on this condition in tinyfilemanager.php:  

`if (fm_rename($path . '/' . $old, $path . '/' . $new)) {`

I've output both the old and new paths and they are identical save for the changed folder name.

Thanks!</div>

**Comment by redherring917b** [comment]
Pretty sure the problem is that renaming a folder calls the function **fm_is_valid_ext** which doesn't find the fold name extension as being in the list of allowed extensions (since it's a folder and has no extension), and rejects the rename.  I can change my **$allowed_file_extensions** settings to an empty list and then successfully rename a folder, but if I do that I can also then rename a file to one with an undesirable file extension.  So it seems that the renaming of a folder needs to be identified and handled differently than the renaming of a file.

Anyone have suggestions / a fix for this?

Thanks!

**Comment by redherring917b** [comment]
I sure thought this would work to exclude the renaming of folders from the check on allowed extensions for filenames, but sadly it does not.

```
function fm_rename($old, $new)
{	
	if(!is_dir($new)) {
    	        $isFileAllowed = fm_is_valid_ext($new);
    	        if(!$isFileAllowed) return false;
	} else {
		return (!file_exists($new) && file_exists($old)) ? rename($old, $new) : null;	
   	}    
}
```

**Comment by redherring917b** [comment]
Cool!  Thanks.  Is there any chance you'd be able to pass on the specific changes that were required? I've made a number of minor revisions on this end that I don't want to lose in any "merge", so if the changes for this fix were minimal it might make me most comfortable to just implement those manually into my file.

Thanks again.

**Comment by Langlais115** [comment]
Just have a look in the commit.

But here it is anyway:
```
    if(!is_dir($old))
    {
        if (!$isFileAllowed) return false;
    }
```

**Comment by redherring917b** [comment]
Ah yes, of course.  Sorry about that!  And thanks again.  Very appreciative of the fix.

**Comment by redherring917b** [comment]
Oh man.  My bad.  So sorry about that.  Clearly I'm not familiar enough with the workings of Github.  Reopening, and again, thank you.

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).

**Comment by Joey-Ma** [comment]
Thanks
