### ISSUE TITLE
$global_readonly is ignored

### ISSUE THREAD

**Issue by Nibbik** [prasathmani/tinyfilemanager#861]
_$global_readonly_ is ignored: when set to TRUE, editing is still allowed.

Please consider adding _**$global_readonly**_ to definition in line 395:
`define('FM_READONLY', $global_readonly || ($use_auth && !empty($readonly_users) && isset($_SESSION[FM_SESSION_ID]['logged']) && in_array($_SESSION[FM_SESSION_ID]['logged'], $readonly_users)));`

**Comment by andymcca** [comment]
Duplicate issue - https://github.com/prasathmani/tinyfilemanager/issues/753

**Comment by prasathmani** [comment]
This issue is addressed in the new [release](https://github.com/prasathmani/tinyfilemanager/releases/tag/2.5.0).
