### ISSUE TITLE
problem with advanced search (find nothing)

### ISSUE THREAD

**Issue by robdi123** [prasathmani/tinyfilemanager#869]
root search works excelent but advanced search brings nothings and i have an error on the console related to de JSON.

![error tiny](https://user-images.githubusercontent.com/42899303/196167367-3f20d229-22a8-4060-8154-8dd116c94212.jpg)

i hope someone can help me. thanks.

**Comment by rizrmd** [comment]
I think the problem lies here:

https://github.com/prasathmani/tinyfilemanager/blob/2c0e6d216ec96ac2057d90c9f3ffaff9ad173080/tinyfilemanager.php#L3023

Somehow RegexIterator is not picking up right file for searches.

**Comment by rizrmd** [comment]
Naah.

This is the problem: ajax searches is being preceded by another ajax request and never executed, so the solution is just to move ajax search to the top

**Comment by robdi123** [comment]
hi, thanks for the answer. so you mean i should move the fm_search function to the top?

**Comment by rizrmd** [comment]
I mean, add this:

```

if (isset($_POST['ajax'])) {
    //search : get list of files from the current folder
    if(isset($_POST['type']) && $_POST['type']=="search") {
        $dir = FM_ROOT_PATH;
        $response = scan(fm_clean_path($_POST['path']), $_POST['content']);
        echo json_encode($response);
        exit();
    }
}

```
before  this:

https://github.com/prasathmani/tinyfilemanager/blob/2c0e6d216ec96ac2057d90c9f3ffaff9ad173080/tinyfilemanager.php#L426

That should fix this issue. I'm sorry for putting it right here instead of proper pull request.

**Comment by rizrmd** [comment]
I just created ad-hoc pull request https://github.com/prasathmani/tinyfilemanager/pull/878

**Comment by rizrmd** [comment]
Can you show response body of that 500 error ? You can open network tab, click item that has red color (500 error) and show the body

**Comment by rizrmd** [comment]
> is this?
> 
> ![response 1-2](https://user-images.githubusercontent.com/42899303/200339528-58c6c5c5-3ddf-4611-9506-488fec8e9f61.jpg) ![response 2-2](https://user-images.githubusercontent.com/42899303/200339545-d779eee0-bf26-4b00-ac28-8017db2beb4a.jpg)
> 
> Thanks.

Sorry, I mean request and response body, not the header. After you click that, make sure to screenshot "Request" and "Response" Tab

**Comment by rizrmd** [comment]
I mean Payload

**Comment by rizrmd** [comment]
> I mean, add this:
> 
> ```
> 
> if (isset($_POST['ajax'])) {
>     //search : get list of files from the current folder
>     if(isset($_POST['type']) && $_POST['type']=="search") {
>         $dir = FM_ROOT_PATH;
>         $response = scan(fm_clean_path($_POST['path']), $_POST['content']);
>         echo json_encode($response);
>         exit();
>     }
> }
> ```
> 
> before this:
> 
> https://github.com/prasathmani/tinyfilemanager/blob/2c0e6d216ec96ac2057d90c9f3ffaff9ad173080/tinyfilemanager.php#L426
> 
> That should fix this issue. I'm sorry for putting it right here instead of proper pull request.

Are you sure have done this ? 
because it looks like your request just somehow skipped this line:

```
if (isset($_POST['ajax'])) {
     //search : get list of files from the current folder
     if(isset($_POST['type']) && $_POST['type']=="search") {
```

If you check in payload, we have $_POST['ajax'] and $_POST['type'] set to "search", It should work.
Maybe replace your tinyfilemanager.php with [latest one from master branch](https://github.com/prasathmani/tinyfilemanager/blob/master/tinyfilemanager.php).

**Comment by robdi123** [comment]
yes, i did that.
![ajax](https://user-images.githubusercontent.com/42899303/200562835-2f1d239a-8a9b-4b18-8d89-9db7e97851e6.jpg)

yesterday i compare the lastest file with mine one and thers not to many changes, all the changes are basically made by me (i modify the login, some icons, not to much)

**Comment by rizrmd** [comment]
That's weird, I need to do some debugging. If you are available, I'm willing to help you with live coding session.

**Comment by robdi123** [comment]
when can you help me? and how we can do it? i have the production site on my computer to.

**Comment by rizrmd** [comment]
https://pop.com/j/834-225-930 <- I will remove this after we are done.

**Comment by rizrmd** [comment]
Okay, after we do our live session. It's concluded that tinyfilemanager cannot be "injected" to view or controller inside your framework. So you should directly visit tinyfilemanager.php or embed it using <iframe />

**Comment by robdi123** [comment]
@rizrmd Hi, i made it work with a controller, and advanced search work if i go in a folder, but it doesnt work on root 😮‍💨...

i think something here `<a class="dropdown-item" href="<?php echo $path2 = $path ? $path : '.'; ?>` is not working for me, do you have any idea  of what can be wrong?

Tnaks in advanc.

**Comment by AwaisHaider1** [comment]
> @rizrmd Hi, i made it work with a controller, and advanced search work if i go in a folder, but it doesnt work on root 😮‍💨...
> 
> i think something here `<a class="dropdown-item" href="<?php echo $path2 = $path ? $path : '.'; ?>` is not working for me, do you have any idea of what can be wrong?
> 
> Tnaks in advanc.

@robdi123 For advanced search to work also in the root folder just remove the condition in scan function.
```
function scan($dir, $filter = '') {
    $path = FM_ROOT_PATH.'/'.$dir;
    $ite = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path));
    $rii = new RegexIterator($ite, "/(" . $filter . ")/i");

    $files = array();
    foreach ($rii as $file) {
        if (!$file->isDir()) {
            $fileName = $file->getFilename();
            $location = str_replace(FM_ROOT_PATH, '', $file->getPath());
            $files[] = array(
                "name" => $fileName,
                "type" => "file",
                "path" => $location,
            );
        }
    }
    return $files;
}
```

**Comment by prasathmani** [comment]
@AwaisHaider1 thanks for the answer,  it is already fixed in latest version.

**Comment by robdi123** [comment]
> > @rizrmd Hi, i made it work with a controller, and advanced search work if i go in a folder, but it doesnt work on root 😮‍💨...
> > i think something here `<a class="dropdown-item" href="<?php echo $path2 = $path ? $path : '.'; ?>` is not working for me, do you have any idea of what can be wrong?
> > Tnaks in advanc.
> 
> @robdi123 For advanced search to work also in the root folder just remove the condition in scan function.
> 
> ```
> function scan($dir, $filter = '') {
>     $path = FM_ROOT_PATH.'/'.$dir;
>     $ite = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path));
>     $rii = new RegexIterator($ite, "/(" . $filter . ")/i");
> 
>     $files = array();
>     foreach ($rii as $file) {
>         if (!$file->isDir()) {
>             $fileName = $file->getFilename();
>             $location = str_replace(FM_ROOT_PATH, '', $file->getPath());
>             $files[] = array(
>                 "name" => $fileName,
>                 "type" => "file",
>                 "path" => $location,
>             );
>         }
>     }
>     return $files;
> }
> ```

Thanks!!! it works!
