### ISSUE TITLE
Fatal error: Call to undefined function disk_total_space()

### ISSUE THREAD

**Issue by timint** [prasathmani/tinyfilemanager#873]
Fatal error: Uncaught Error: Call to undefined function disk_total_space() in tinyfilemanager.php:2146

Using latest master build

**Comment by ririko5834** [comment]
I have the same issue.
Using php v8.0

**Comment by smalos** [comment]
This 
`fm_get_filesize(@disk_total_space($path))`

could be replaced with:

`function_exists('disk_total_space') ? fm_get_filesize(@disk_total_space($path)) : 'n/a'`

**Comment by ririko5834** [comment]
It should be fixed

**Comment by smalos** [comment]
> It should be fixed

How did you fix it?

**Comment by ririko5834** [comment]
I didn't, but I want to say that some contributor should fix it, make PR.

**Comment by timint** [comment]
This is the line to edit:

`
                            <?php echo lng('PartitionSize').': <span class="badge badge-light">'.fm_get_filesize(@disk_free_space($path)) .'</span> '.lng('FreeOf').' <span class="badge badge-light">'.fm_get_filesize(@disk_total_space($path)).'</span>'; ?>
`
https://github.com/prasathmani/tinyfilemanager/blob/805308a01318b22b08218243e0cd81a0432de522/tinyfilemanager.php#L2152

Replace it with something like this:

```
                            <?php if (function_exists('disk_free_space') && function_exists('disk_total_space')) { ?>
                            <?php echo lng('PartitionSize').': <span class="badge badge-light">'.fm_get_filesize(@disk_free_space($path)) .'</span> '.lng('FreeOf').' <span class="badge badge-light">'.fm_get_filesize(@disk_total_space($path)).'</span>'; ?>
                            <?php } ?>
```

I don't have a cloned repo to commit this.
