### ISSUE TITLE
Unable to extract files with spaces in the name

### ISSUE THREAD

**Issue by nguyentranchung** [prasathmani/tinyfilemanager#886]
<img width="534" alt="Screen Shot 2022-11-22 at 22 28 48" src="https://user-images.githubusercontent.com/9611224/203325977-501b8372-f622-4b48-a76c-65da25099d09.png">

When extracting a file with a space in the name, an error like this will appear

**Comment by nguyentranchung** [comment]
Files with spaces in the name cannot be renamed.

**Comment by prasathmani** [comment]
[fixed](https://github.com/prasathmani/tinyfilemanager/commit/610cea8ecd8cefcd8b72efedfb8da7b0b9a66857)
