### ISSUE TITLE
Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported

### ISSUE THREAD

**Issue by nguyentranchung** [prasathmani/tinyfilemanager#897]
Fatal error: Unparenthesized `a ? b : c ? d : e` is not supported. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in tinyfilemanager.php on line 2136

**Comment by NFu1nLfdcinVtUqlH1CQ** [comment]
Replace line #2136:
`<td class="gray" colspan="<?php echo (!FM_IS_WIN && !$hide_Cols) ? FM_READONLY ? '6' :'7' : FM_READONLY ? '4' : '5' ?>">`

with:
`<td class="gray" colspan="<?php echo (!FM_IS_WIN && !$hide_Cols) ? FM_READONLY ? '6' :'7' : (FM_READONLY ? '4' : '5') 
?>">`

**Comment by prasathmani** [comment]
#898 898
