### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by alecos71** [prasathmani/tinyfilemanager#9]
```
<b>Notice</b>:  Undefined variable: languages in <b>D:\Web\test\tinyfilemanager.php</b> on line <b>148</b><br />
<br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>D:\Web\test\tinyfilemanager.php</b> on line <b>148</b><br />
```
This is because the fm_get_available_langs () function is never called, so foreach waits for the array and can not cycle the values. Also, the "languages" variable is not initialized anywhere.

Fix: find line 141
`?>`

and just after put:

`<?php $languages = fm_get_available_langs(); ?>`

Hope this helps.

**Comment by prasathmani** [comment]
#fee3728
