### ISSUE TITLE
Date display

### ISSUE THREAD

**Issue by mfor** [prasathmani/tinyfilemanager#900]
2018 displayed as 1818
2019 displayed as 1919
2020 displayed as 2020
2021 displayed as 2121
2022 displayed as 2222

changed 'yy' to  'yyyy' on 78: $datetime_format = 'm/d/yyyy g:i A';
now 2018 displayed as 18181818 
2019 displayed as 19191919
2020 displayed as 20202020 
2021 displayed as 21212121 
2022 displays 22222222

**Comment by mfor** [comment]
changing line 78 to $datetime_format = 'm/d/Y g:i A';
has solved it

**Comment by smalos** [comment]
I agree, `yy` is an invalid format

`$datetime_format = 'm/d/yy g:i A';`
