### ISSUE TITLE
Rename doesn't work

### ISSUE THREAD

**Issue by RenHoekNL** [prasathmani/tinyfilemanager#903]
Expected result: A window pops up allowing you to change a name

Actual result: You click the button and nothing pops up. No errors in the JS console even.

Tried in the most recent Firefox and Chrome. Renaming even doesn't work on the demo page (https://tinyfilemanager.github.io/demo/)

**Comment by smalos** [comment]
No renaming issues here with PHP version: 8.0.6
Do you see any errors in the server logs?

**Comment by jackyhuynh0407** [comment]
I got the same issue. But I found that only folder and file on root can't rename. On sub folder rename is work.

**Comment by smalos** [comment]
Comparing an older version with the latest, there was a change in the JavaScript function rename() :

In the root folder,  an empty argument e is passed and the added check prevents the rename dialog form popping up:
`if(e && t)`
