### ISSUE TITLE
Download doesn't work

### ISSUE THREAD

**Issue by RenHoekNL** [prasathmani/tinyfilemanager#904]
Expected result: File downloads when I click the button

Actual result: 0 byte file is downloaded and apache spits out PHP errors:

`[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2044
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2044
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107, referer: https://x/index.php?p=
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107, referer: https://x/index.php?p=
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107, referer: https://x/index.php?p=
[php7:notice] [client x] PHP Notice:  Trying to access array offset on value of type bool in /xxx/index.php on line 2107, referer: https://x/index.php?p=
[php7:notice] [client x] PHP Notice:  Undefined variable: download in /xxx/index.php on line 3120, referer: https://x/index.php?p=x
[php7:warn]   [client x] PHP Warning: readfile(): Filename cannot be empty in /xxx/index.php on line 3120, referer: https://x/index.php?p=x
`

`
php --version
PHP 7.4.3 (cli) (built: Nov  2 2022 09:53:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
`

This on: Tiny File Manager 2.5.2

**Comment by smalos** [comment]
I get this error:
> PHP Warning:  Undefined variable $download

Try replacing
`readfile($download);`

with 
`readfile($fileName);`

in the function fm_download_file()

**Comment by carlpeer** [comment]
**$download** variable doesn't exist in the script, but replacing it with **$filename** doesn't solve the problem.  

I see this error when I use the download button: 

This site is not accessible https://www.xxxxxxx.xx/ex/index.php?p=&dl=index.htm is not working for a while, or the page may have moved to a new web address.

ERR_INVALID_RESPONSE

**Comment by jackyhuynh0407** [comment]
To fix this we need 2 step.
1. Replacing ```readfile($download);``` with ```readfile($fileName);```
2. Find ```$('#wrapper').append(template(tpl,tplObj));``` replace ```$('#wrapper').prepend(template(tpl,tplObj));```

**Comment by carlpeer** [comment]
> To fix this we need 2 step.
> 
> 1. Replacing `readfile($download);` with `readfile($fileName);`
> 2. Find `$('#wrapper').append(template(tpl,tplObj));` replace `$('#wrapper').prepend(template(tpl,tplObj));`

These steps doesn't work for me.  I see the download dialog now, but after clicking the Okay button, I still see this error: 

This site is not accessible https://www.xxxxxxx.xx/ex/index.php?p=&dl=index.htm is not working for a while, or the page may have moved to a new web address.

ERR_INVALID_RESPONSE

**Comment by mano1979** [comment]
This solution works for me!
