### ISSUE TITLE
Download and Direct link problems when using with a subfolder...

### ISSUE THREAD

**Issue by carlpeer** [prasathmani/tinyfilemanager#907]
**Case 1:** 

$root_path = $_SERVER['DOCUMENT_ROOT'].'/subfolder';
$root_url = '';

When using this: **download works**, but **direct link doesn't work**.

**Case 2:** 

$root_path = $_SERVER['DOCUMENT_ROOT'].'/subfolder';
$root_url = '/subfolder';

When using this: **download works**, and **direct link works**, but when you login with this config you will receive a page not found, because the path to the script becomes: **http://url/subfolder/subfolder/index.php**
So, the subfolder is a second time in the path. 

**Problem 2:** 

Download doesn't work when you click on a filename, and use 'download' on that screen... No download starts and the script returns to the main view with all the files.

**Comment by prasathmani** [comment]
@carlpeer thanks for reporting the issue. try following config, 
```php
$root_path = $_SERVER['DOCUMENT_ROOT'].'/subfolder';
$root_url = 'subfolder';
```
please share some screenshots, it will be helpful to fix.

**Comment by carlpeer** [comment]
@prasathmani Thank you for your support!

Ok.  Go to [https://www.artwerp.be/subfolder](https://www.artwerp.be/subfolder) 
Username: user
Password: demo

You will see the **page not found error**

See the screenshot below for the download button that doesn't work...

![download](https://user-images.githubusercontent.com/93937583/205260097-b8eb89ac-5575-4886-a7d6-a3f39e5cee98.jpeg)

**Comment by prasathmani** [comment]
@carlpeer , thanks for sharing, Let me check.

**Comment by prasathmani** [comment]
@carlpeer, download issues is fixed now. try with latest version.
