### ISSUE TITLE
Directory Users does not work

### ISSUE THREAD

**Issue by kimaniidaniel** [prasathmani/tinyfilemanager#908]
Direcotry Users does not work for me. I created a user, then restricted where this user can access using directory_users. However whenever I log in as this user I'm dropped directly on the root /public_html/. Any ideas of what I'm doing wrong?

`$directories_users = array([
    'mortgagee-dropbox@netherlands.co.gd' => '/home/856260.cloudwaysapps.com/fzhzabfrey/public_html/mortgagee_report/dropbox/'
]);`

**Comment by prasathmani** [comment]
path should start from web root directory 
```php
directories_users = array([ 'mortgagee-dropbox@netherlands.co.gd' => '/mortgagee_report/dropbox' ]);

**Comment by kimaniidaniel** [comment]
Thank you for the reply and this is an AWESOME one page application, i'm soo impressed! However, after making your suggested change it still doesn't work. Now let me explain the setup, I'm not sure if it matters.
I have Tiny File Manager in (root)/dropbox/ folder (so I tell the client log into www.website.com/dropbox/, but the folder I want to give them access to is (root)/mortgagee_report/dropbox/. I'm not sure if this is the problem? I can add you as a user if you want to check it out,

**Comment by prasathmani** [comment]
#724
