### ISSUE TITLE
Version 2.5.2 Embed Problem

### ISSUE THREAD

**Issue by bcarrion12** [prasathmani/tinyfilemanager#917]
I recently tried to embed the browser inside my system. There is very little information on how to do it. Only problem #118 talks about this. I have embedded the explorer, but functions such as editing, creating folders, uploading files, do not work.
I don´t know what could be the probleam.
![image](https://user-images.githubusercontent.com/117275009/207823928-81d1336a-e805-4190-89a7-9b780877884b.png)
![image](https://user-images.githubusercontent.com/117275009/207824092-e43c410b-17c6-47b1-9539-8ad4f6fd9baa.png)
![image](https://user-images.githubusercontent.com/117275009/207824191-fee3f112-d5ee-4ade-8421-c6f97f40f6d4.png)

**Comment by prasathmani** [comment]
did you get any error, please share some screenshot of error.

**Comment by bcarrion12** [comment]
![issue](https://user-images.githubusercontent.com/117275009/208384131-21eac4cc-88e7-4ca6-be93-3e6aa99a8d10.gif)

**Comment by bcarrion12** [comment]
It is also not possible to navigate between subfolders
![issue_2](https://user-images.githubusercontent.com/117275009/208384778-79109fd0-017e-4c6a-87ee-989e0377cf1c.gif)
