### ISSUE TITLE
Define external dependencies in the config file

### ISSUE THREAD

**Issue by smalos** [prasathmani/tinyfilemanager#919]
Tiny File Manager has some external dependencies (jquery, dropzone etc.). If used offline, it is not fully functional or styles are not applied.
It would be nice if alternative locations could be defined in the configuration file.

Another advantage is that you can use other versions without having to modify tinyfilemanager.php.

E.g. define in the config file:

`$path_dropzone = "https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.9.3/min/dropzone.min.js";`

Use the path in tinyfilemanager.php:
`<script src="<?php echo($path_dropzone ); ?>"></script>`

**Comment by prasathmani** [comment]
added this feature in latest version, and for offline use - https://github.com/prasathmani/tinyfilemanager/tree/offline branch
