### ISSUE TITLE
Not looking good on phones

### ISSUE THREAD

**Issue by DecodeMehh** [prasathmani/tinyfilemanager#93]
I am using a phone and the older versions of your project are looking better on phone.

you can resolve some issues by adding this 

`<meta content='width=device-width, initial-scale=1' name='viewport'/>`

it is not looking right?
https://i.imgur.com/zO4P4pf.jpg

Edit:
Oh you already have 
`<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">`
mmh well it seem to not fix the issue.

also the advanced editing text is almost impossible on phone.
https://i.imgur.com/ZvULeXJ.jpg

**Comment by prasathmani** [comment]
@DecodeMehh  try with latest code.

**Comment by DecodeMehh** [comment]
Look like everything as been fixed :)
Thanks.

**Comment by simon511000** [comment]
I can't click on the buttons (on iPad) : 
![54381825-9d12-4f7f-858b-016a687fc6f9](https://user-images.githubusercontent.com/31013205/49490201-20ba8680-f84f-11e8-891f-908cc7d3ccaa.png)

**Comment by simon511000** [comment]
@prasathmani , you can test your file manager with the development tools. You can test with any phone / tablet, portrait or landscape mode : CTRL+SHIT+I

**Comment by DecodeMehh** [comment]
The buttons are showing only when i am going all the way up to the page in editing mode.

**Comment by simon511000** [comment]
good job 👍, but it's not perfect : 
![3dc8cb32-c6d0-406f-ad4a-5fc6aede6640](https://user-images.githubusercontent.com/31013205/49568644-e4138b80-f931-11e8-9695-7f8a8ef6aa51.jpeg)
![b741bd3c-a442-4829-9d5a-a3ddb76c58b4](https://user-images.githubusercontent.com/31013205/49568645-e4138b80-f931-11e8-9bd3-746e9f7e0752.jpeg)

**Comment by simon511000** [comment]
In iPad : 
![temp](https://user-images.githubusercontent.com/31013205/49581849-914acb80-f953-11e8-88a2-75bddbd21714.PNG)

**Comment by prasathmani** [comment]
@simon511000, today I got a chance to test the app in iPad, So finally alignment issue is fixed now.

**Comment by simon511000** [comment]
Great!! Thank you very much !! I think you can close the issue
