### ISSUE TITLE
Embedded Content is too small 

### ISSUE THREAD

**Issue by Kai20061** [prasathmani/tinyfilemanager#930]
I am unfamiliar with php coding so cannot fully explain the issue however the window in which content is displayed vvv

![image](https://user-images.githubusercontent.com/90457669/210390548-5b4ef37c-1583-4a5b-bee8-6a40b41f22fa.png)

is too short.Is there a way to enlarge the winow as there is in  html under length and width style sheets (css) ??

**Comment by prasathmani** [comment]
you can increase the height of the container by changing the `min-height` on following line.

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/11345598/211125450-a54feab4-75e5-4289-9822-15d050d0e368.png">
