### ISSUE TITLE
[Solved] Docker install : Error Invalid Token when uploading a file

### ISSUE THREAD

**Issue by nemocorp** [prasathmani/tinyfilemanager#936]
I used Tinyfilemanager without problem for several month but need to reinstall my docker deployment of tinyfilemanager. I disable user auth and authenticate with ip whitelist.

While it used to work like a charm, it didn't with the last version. I get Invalid token error when trying to upload a file.

Any Idea.

**Comment by prasathmani** [comment]
can you clear a cache and check once, I tried my local and it's working fine(with and without auth). I have introduced token validation in recent releases. can you possible to share screenshot of the payload.

**Comment by nemocorp** [comment]
Same behaviour after cleaning the cache.

![image](https://user-images.githubusercontent.com/1446550/211592586-f4bc3a91-8d75-43a1-b334-b544d0af75d3.png)

The progress bar mimic the file upload and reach 100% then the invalid token message is displayed and no file on the server.

**Comment by ibukanov** [comment]
Can it be that the Docker config does not create or make it writable the php session directory?

**Comment by nemocorp** [comment]
Seems to write correctly to the default /tmp

```
/usr/local/etc/php # ls /tmp
sess_cgpkj71v94id7s8fjspbgv8067
```

**Comment by nemocorp** [comment]
I deleted the session file present in /tmp, since  then no new session file it was created.

**Comment by ibukanov** [comment]
The default for `session.save_path` depends on Linux distribution. What session_save_path() returns? `echo session_save_path();` should print it.

**Comment by nemocorp** [comment]
echo session_save_path(); returns nothing.

**Comment by nemocorp** [comment]
Solved : tinyfilemanger/tinyfilemanager:master buggy. Update container to tinyfilemanger/tinyfilemanager:latest solved my problem. Anyway thanks for your answers.

**Comment by nemocorp** [comment]
Solved : tinyfilemanger/tinyfilemanager:master buggy. Update container to tinyfilemanger/tinyfilemanager:latest solved my problem. Anyway thanks for your answers.
