### ISSUE TITLE
doubt about the latest version

### ISSUE THREAD

**Issue by cataalin** [prasathmani/tinyfilemanager#939]
what is the latest stable version? because I downloaded the master from the main directory, and it appears that it is 2.5.2, which should be the latest, but then I see that the 2.5.0 of the branch is the most up-to-date, I'm confused, in 2.5.2 I have several problems like the direct link or hover in the images, which is the best version? 2.5.0 fixes all this it seems.

**Comment by smalos** [comment]
I see `define('VERSION', '2.5.2');` in the php file.
