### ISSUE TITLE
`The requested resource /data/ was not found on this server.` with docker-compose

### ISSUE THREAD

**Issue by Akashic101** [prasathmani/tinyfilemanager#943]
I tried to boot TinyFileManager with docker-compose on my F:/ drive at port 8007 with following file
```Containerfile
version: '3'
services:
  tinyfilemanager:
    image: tinyfilemanager/tinyfilemanager:master
    container_name: tinyfilemanager
    restart: always
    volumes:
    - F:/TinyFileManager/data:/var/www/html/data
    ports:
      - 8007:80
```

While I see the splashscreen asking me to log in and this all works, after logging in all I see is following message:

`The requested resource /data/ was not found on this server.` with the error `Failed to load resource: the server responded with a status of 404 (Not Found)` in the console. My folder structure is as following:

```
F:
|-- TinyFileManager
    |-- docker-compose.yml
    |-- data
``` 

How can I fix this issue?

**Comment by prasathmani** [comment]
#948
