### ISSUE TITLE
Copying large files stops at 4GiB (INT_MAX bytes).

### ISSUE THREAD

**Issue by gerion0** [prasathmani/tinyfilemanager#958]
I just tried to copy a file greater than 4GiB and tinyfilemanager stops doing that at exactly 4294967296 bytes (that is INT_MAX + 1 byte) so I strongly assume that is has to do something with it.

Of course I would find it great, if you fix that limitation. Otherwise I think that an error message would be helpful that copying files >4GiB is not supported.

**Comment by smalos** [comment]
You have hit a bug:  https://bugs.php.net/bug.php?id=81145

Workaround: https://forums.phpfreaks.com/topic/314286-php-not-able-to-copy-files-more-than-4gb/
