### ISSUE TITLE
Max file size?

### ISSUE THREAD

**Issue by TheXisco** [prasathmani/tinyfilemanager#96]
Has Tiny File Manager a size limit? I ask this because I can not upload files whose size is 3mb or higher.

Thanks.

**Comment by gbrault** [comment]
have a look to the php.ini file. You need to fix two values
max_upload_size and max_post_size (not sure of the exact naming pls check)
put them as you want
php.ini location depends on your os context usually /etc/php/<version> directory
You may also get this limit in your web server (depends on apache2 or nginx or the like)

**Comment by gbrault** [comment]
in fact see the 'bug' I opened with dropzone.js default timeout to 30 seconds as well

**Comment by damianmiles** [comment]
Yes I found the same issue, even we modify what you say, it's still restricted

**Comment by gbrault** [comment]
check you have dropzone setup
you should add timeout (in msec)
Dropzone.options.fileUploader = {
timeout:120000, // 2 minutes
init: function () {...
within fm.php

**Comment by carlsue** [comment]
Yes I found the same issue, even we modify what you say, it's still restricted

**Comment by jfg-fimac** [comment]
Hi, i have the same problem.
I have change parameters in my Plesk but no change...
Thanks for your help.

**Comment by psycholyzern** [comment]
Found the problem.
We should edit dropzone configuration [in here](https://github.com/prasathmani/tinyfilemanager/blob/1b9e0f5e7672353c9018b5c0d56f9a55ab247faa/tinyfilemanager.php#L936)

check this configuration example on [https://www.dropzonejs.com/](https://www.dropzonejs.com/#configuration)
What you are looking for is `maxFilesize`.

**Comment by MRDarck** [comment]
To upload more than 256mib you should change memory_limit in php.ini

**Comment by psycholyzern** [comment]
@MRDarck  tinyfilemanager also limiting upload size in the front-end. I explained it in the reply above you.

Need to set `maxFilesize` in dropzonejs configuration or you will not be able to upload file as big as what you set in php.ini

**Comment by prasathmani** [comment]
Updated `maxFilesize`  has 2GB now.

**Comment by carlsue** [comment]
> Updated maxFilesize  has 2GB now.

why not let us to modify freely?

**Comment by prasathmani** [comment]
@carlsue new config flag is added now for `MAX_UPLOAD_SIZE`

**Comment by carlsue** [comment]
<img width="817" alt="批注 2019-03-12 223030" src="https://user-images.githubusercontent.com/17507066/54260482-01489d80-45a4-11e9-8f7b-1da200098325.png">

get another error

**Comment by prasathmani** [comment]
increase your `MAX_UPLOAD_SIZE` in configuration and then try

**Comment by carlsue** [comment]
> increase your `MAX_UPLOAD_SIZE` in configuration and then try

![TIM截图20190313163929](https://user-images.githubusercontent.com/17507066/54264672-96509400-45ae-11e9-83d0-b844e2f7276a.jpg)

**Comment by prasathmani** [comment]
[Server responded with 0 code #701](https://github.com/enyo/dropzone/issues/701)

**Comment by mahyard** [comment]
@prasathmani 
Another hardcoded value that will cause an "Error: Server Timeout" message is located [here](https://github.com/prasathmani/tinyfilemanager/blob/2046bbde72ed76af0cfdcae082de629bcc4b44c7/tinyfilemanager.php#L1227).
What do you think about making it configurable as well?
