### ISSUE TITLE
How to make Tiny File Manager fully offline with offline resources?

### ISSUE THREAD

**Issue by helmiau** [prasathmani/tinyfilemanager#972]
i already make tinyfilemanager.php scripts to offline resources like these

![image](https://user-images.githubusercontent.com/20932301/220316985-f5631f9d-fd39-4a31-a495-33a3daf1c49c.png)

and also downloaded scripts and fontawesome resources

![image](https://user-images.githubusercontent.com/20932301/220317448-468baf61-6717-4556-a379-6d9b1e3eb526.png)

![image](https://user-images.githubusercontent.com/20932301/220317542-182df743-00f9-4695-a9cf-bddc78c5263d.png)

but the results is like this

![image](https://user-images.githubusercontent.com/20932301/220316863-8836348c-8bf0-4d09-8480-4c005ccc0643.png)

so, can you make different branch containing main tinyfilemanager.php with all resources inside to make sure this project can be run without internet.
thank you.

**Comment by smalos** [comment]
Any errors in the developer console (F12) ?

**Comment by prasathmani** [comment]
use offline branch: https://github.com/prasathmani/tinyfilemanager/tree/offline

**Comment by smalos** [comment]
@prasathmani , @helmiau :

Ace requires some other files (themes, extensions, syntax highlighting etc.)

It's probably better to place them in a subfolder within assets/js/

[ace.zip](https://github.com/prasathmani/tinyfilemanager/files/10811431/ace.zip)

and then replace

`  'js-ace' => '<script src="assets/js/ace.js"></script>',`
  
  with
  
`    'js-ace' => '<script src="assets/js/ace/ace.js"></script>',
`
