### ISSUE TITLE
Issue while Preview Files and Advanced Search

### ISSUE THREAD

**Issue by Rohitgowda** [prasathmani/tinyfilemanager#974]
Hi First, Thank you for the plugin. This is my first time using it. I am using it in an Iframe inside a web apllication of PHP, I have 2 issues while Implimenting it.

1. I have an **unauthorized** issue shown while doing an advanced search and Files preview is not working even in the deployed server. Please check the Image
2. Can you please let us know how can I do the .Zip and .Tar download? Do i need to connect to another plugin or do I need to access the click outside and work on it. 

![image](https://user-images.githubusercontent.com/20566050/220346307-dc4a8bdb-f0bf-4427-a2bf-02e98b0bc920.png)

Thank you,
Rohit

**Comment by Rohitgowda** [comment]
Hi Thank you for the reply, I did remove the line now I am getting the error like this shown below


![image](https://user-images.githubusercontent.com/20566050/220355154-bb1ad611-6a6e-4cb1-820a-f5eda0b5de04.png)

**Comment by prasathmani** [comment]
can you share the api response screenshot.

**Comment by Rohitgowda** [comment]
Here it is 
![image](https://user-images.githubusercontent.com/20566050/220360623-072b7871-4f10-42e0-9f5b-2e652f3cd54f.png)

**Comment by prasathmani** [comment]
Thanks for sharing, can you share the screenshot of "Payload" and "Response"

**Comment by Rohitgowda** [comment]
It shows here as Error line.
![image](https://user-images.githubusercontent.com/20566050/220363168-a1bc08a7-8bd7-4777-a1bc-cf3deeb2fd8f.png)

**Comment by prasathmani** [comment]
@Rohitgowda, thanks for sharing.  through this logs i couldn't find anything. please reach out ccpprogrammers[at]gmail.com,   if possible I can help you through on call.

**Comment by Rohitgowda** [comment]
Hi sure, Thank you very much for your support. I hope it is not to much task for you.

**Comment by Rohitgowda** [comment]
Thank you very much Prasath. He connected one on one and solved the Issue. I wish i could give a like somewhere.

The issue was caused due to FM_READONLY upon removing it started to work.

![image](https://user-images.githubusercontent.com/20566050/220560727-97582fcd-6437-4126-8467-4859da476ffb.png)
