### ISSUE TITLE
HTTP ERROR 500 Php 5.6

### ISSUE THREAD

**Issue by zentasuken** [prasathmani/tinyfilemanager#977]
I have this error HTTP ERROR 500 in php 5.6. what should I do? Thanks

**Comment by smalos** [comment]
TFM uses a function random_bytes() that was introduced with PHP7 ([reference](http://php.net/manual/en/function.random-bytes.php)).

Alternatively for PHP versions below 7.0 like 5.6, 5.5 etc, you can use custom function to generate random number using function below.


i```
f( !function_exists('random_bytes') )
{
    function random_bytes($length = 6)
    {
        $characters = '0123456789';
        $characters_length = strlen($characters);
        $output = '';
        for ($i = 0; $i < $length; $i++)
            $output .= $characters[rand(0, $characters_length - 1)];

        return $output;
    }
}
```

If you add it to tinyfilemanager.php, the error should be gone.

**Comment by zentasuken** [comment]
worked. I saw the login page. but when i logged in i got this error.

ERR_TOO_MANY_REDIRECTS

**Comment by zentasuken** [comment]
Worked thanks. I don't think there is an logout button.

**Comment by smalos** [comment]
Check the server logs to see if they contain any additional error messages. Depending on the server software you are using, the logs may be located in different places. Consult the documentation for your server software to find out where the logs are located.

**Comment by smalos** [comment]
I can see the "Sign Out"

<img width="156" alt="tfm" src="https://user-images.githubusercontent.com/45562597/221348448-eb1de980-89b3-4cf4-b5a6-c0ecbae8f94d.png">

**Comment by pwnsauce403** [comment]
> TFM uses a function random_bytes() that was introduced with PHP7 ([reference](http://php.net/manual/en/function.random-bytes.php)).
> 
> For PHP versions below 7.0 like 5.6, 5.5 etc, you can use a custom function to generate random number using function below.
> 
> ```
> if( !function_exists('random_bytes') )
> {
>     function random_bytes($length = 6)
>     {
>         $characters = '0123456789';
>         $characters_length = strlen($characters);
>         $output = '';
>         for ($i = 0; $i < $length; $i++)
>             $output .= $characters[rand(0, $characters_length - 1)];
> 
>         return $output;
>     }
> }
> ```
> 
> If you add it to tinyfilemanager.php, the error should be gone.

hi i got the same 500 error, where do i have to put this code? anywhere?

**Comment by EV-soft** [comment]
Find this:
`//Generating CSRF Token`
and put it just before.

**Comment by pwnsauce403** [comment]
> Find this: `//Generating CSRF Token` and put it just before.

worked, thanks.
