### ISSUE TITLE
Missing in v2.5.3

### ISSUE THREAD

**Issue by dxdydado** [prasathmani/tinyfilemanager#983]
Missing "Partition size" and "Free of"

Picture from 2.4.7 version:
https://i.postimg.cc/g0hXWFFf/Snap1509.jpg

Is possible to get back this option.? Thx.

**Comment by smalos** [comment]
It was excluded in [this commit](https://github.com/prasathmani/tinyfilemanager/commit/fce0f5bacb726a5ca3bb9c2743960fca5e7edf82)

However, I saw no comment as to why it was excluded.

**Comment by prasathmani** [comment]
This feature has been removed.
