### ISSUE TITLE
cant upload file

### ISSUE THREAD

**Issue by amylene12** [prasathmani/tinyfilemanager#990]
Hi, i cant upload php on my shell

**Comment by smalos** [comment]
I'm sorry to hear that you are having trouble uploading PHP files to your shell. Without more information about the specific error you are encountering, it's difficult to provide a specific solution, but here are a few troubleshooting steps you can try:

Make sure that the file you are uploading has the .php extension. PHP files will not execute properly if they do not have this extension.

Check that your shell account has the appropriate permissions to upload and execute PHP files. Your web host or system administrator should be able to help you with this.

Make sure that your PHP code is error-free. You can check for errors by running your code through a syntax checker or using error reporting functions in PHP.

Check that the version of PHP installed on your server matches the version required by your PHP script. You can usually find this information in the script's documentation or by contacting the script's developer.

If none of the above steps resolve the issue, try contacting your web host or system administrator for further assistance. They may be able to provide more specific guidance based on your particular setup and configuration.
